### ISSUE TITLE
Cache files downloaded by the installers

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1025]
Re-downloading a heavy executable every time you reinstall the game with the installer can be very time consuming and expensive for people with slow and limited internet connection.
It would be nice to have those files that the installers download be permanently cached and use local copies instead of re-downloading them each time.

**Comment by strycore** [comment]
That's essentially what the Personal Game Archives should do. Some of the code is there and we also had caching at some point but that would sometimes mess up installs in case of an incomplete download, we also need a way to validate files (we have code to validate md5 checksums)

**Comment by sorsasampo** [comment]
@strycore this would be very useful for local development.

Strong checksums (sha256/sha512) would also be nice. Perhaps support everything that can be found in python's `hashlib`.

**Comment by sorsasampo** [comment]
I opened issue #1383 for the checksum part.

**Comment by sbolokanov** [comment]
I'm trying to write a LINUX GOG installer for Observer.

Since I don't know how to write it properly I fail and have to do it from scratch. Every time redownloading a 10 GB game and having to wait just to see if it work.

This is kind of a pain. Can we have a checkbox in Preferences for storing GOG installers?

**Comment by strycore** [comment]
I actually want that for the upcoming release too
