### ISSUE TITLE
Tests failing on a clean installation

### ISSUE THREAD

**Issue by FFY00** [lutris/lutris#1067]
Hello, I am packaging lutris to move it to the `[community]` repo in Arch Linux. When running the tests, `test_dialog.py` fails with a core dump. On my machine it works fine, apart from a few warnings. Here are the dependencies that I'm using, do you remember anything that might be missing?

`python-gobject` `python-yaml` `python-evdev` `gtk3` `glib2` `psmisc` `cabextract` `unrar` `unzip` `p7zip` `curl`

**Comment by FFY00** [comment]
Updated the dependencies, should match the debian ones now. Still fails

**Comment by strycore** [comment]
uh? for some reason it's failing to create the sqlite db? is this some kind of read only system?

**Comment by FFY00** [comment]
No. Where is it trying to install the db? It runs inside a container so it should be able to write to system paths.

**Comment by eli-schwartz** [comment]
> It runs inside a container

"It runs as non-root" should be sufficient to cause issues writing to system paths... I certainly hope that's not the problem. :/

@FFY00 our makechrootpkg container user does have full write permissions to its own user directory, and according to this project's README the sqlite database should be in the (writable) `~/.local/share/lutris` not in `/usr` or anything. That being said, obviously program testsuites should endeavor to use temporary directories with generated test data rather than writing to the user's dotfiles... no idea what lutris does here, though.

**Comment by eli-schwartz** [comment]
Software that coredumps when there's no X11 display? :(

Granted there's software which fails with "cannot open display" and that's generally a sign you should run the tests with xvfb-run.

**Comment by strycore** [comment]
yeah, my jenkins instance uses xvfb-run to run the test. It seems pretty obvious that a Gtk app would need some sort of X server to run tests tbh.

**Comment by strycore** [comment]
Also, is it a hard requirement to have the tests pass for the package to build? None of the other distributions have this requirement, the tests are only run automatically from a private Jenkins instance or manually by devs but I don't think they should affect the outcome of a package build. 
If it *is* a requirement then it's still possible to achieve this by adding xvfb in some sort of BuildDep and make sure that ~/.local/share/lutris, ~/.config/lutris and ~/.cache/lutris are writable during the test run.

**Comment by FFY00** [comment]
Thes issues were fixed by running `xvfb-run`, perhaps the change to `nose` also helped with the last one :smile:

@strycore it's not a hard requirement but it something we should do. `lutris` was in the repos [already](https://www.archlinux.org/packages/community/any/lutris/).
