### ISSUE TITLE
[SSL: certificate] error specifying an action (when downloading runners & trying to login)

### ISSUE THREAD

**Issue by goldsteal** [lutris/lutris#1109]
Hello everyone!

A few days ago my PC randomly died – because I broke something software related and it was just too much of a hassle to fix it I ended up freshly installing my main OS completely (Linux Mint 19 Tara).

Here is the output of `uname -a`:

> Linux xx-0x-linuxmint 4.18.7-041807-generic #201809090930 SMP Sun Sep 9 09:33:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

No runners in Lutris work giving the following output whenever I try to configure/install them i.e Wine, Steam, Retroarch etc.:

> "*" not available on the X86_64 architecture

Lutris used to work fine and even survived the update from Linux Mint 18.3 through the process in the Update Manager and now it just won’t work.

Is this something fixable and just a quirky issue on my side of things? I recall similar bug reports from a while back. Just don't know what went wrong.

Problem persists with the kernel versions `4.18.8-041808-generic` and kernel `4.18.10-041810-generic`. But the kernel has probably nothing to with it anyways.

Issue persists in what is according to synaptic version `0.4.20` of Lutris. 
Has anyone any way of fixing this? 
cheers,

goldsteal

**Comment by goldsteal** [comment]
Problem persists with the newest kernel version (`4.18.8-041808-generic`)

**Comment by goldsteal** [comment]
Issue persists in what is according to synaptic version `0.4.20` of Lutris. 
Has anyone any way of fixing this?

**Comment by jon2kx** [comment]
So winesteam now defaults to 64 bit, so the developers decided that this problem was going to solve itself. I am on 0.4.19 from the Ubuntu repos, and Kernel 4.15.0-34, and I also have the same problem. When I visit the install locale, there is a 64bit wine prefix. 

`jon2kx@jon2kx-desktop:~/git/FFXIV-Lutris$ lutris -i ffxiv-steam.json 
INFO     2018-09-28 02:42:30,042 [lutriswindow]:Connected to lutris.net as surf_turtle
INFO     2018-09-28 02:42:30,239 [lutriswindow]:Installing /home/jwindham/git/FFXIV-Lutris/ffxiv-steam.json
WARNING  2018-09-28 02:42:30,398 [extract]:Overwrite existing path /home/jwindham/.local/share/lutris/runtime/winetricks
WARNING  2018-09-28 02:42:33,580 [winesteam]:wine is not installed
INFO     2018-09-28 02:42:33,580 [runner]:Getting runner information for wine(version: esync-3.16-x86_64)
ERROR    2018-09-28 02:42:34,080 [interpreter]:wine is not available for the x86_64 architecture
ERROR    2018-09-28 02:42:34,080 [errors]:wine is not available for the x86_64 architectureNone
Gtk-Message: 02:42:34.089: GtkDialog mapped without a transient parent. This is discouraged.
^C
jon2kx@jon2kx-desktop:~/git/FFXIV-Lutris$ uname -r
4.15.0-34-generic
jon2kx@jon2kx-desktop:~/git/FFXIV-Lutris$`

This has my script dead in the water. It's a show stopper.

**Comment by goldsteal** [comment]
Thanks so much Jon. I am afraid that that won't do the trick in my case. After running debug mode we found out that this is an SSL certificate error and has likely nothing to do with the architecture, wine or any other runner. Again the error is regardless of runner. Here is the output of ´lutris -d´ while it runs: 

> ERROR 2018-09-26 16:30:10,741 [dxvk]:<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
> ERROR 2018-09-26 16:30:11,088 [http]:Unable to connect to server (https://lutris.net/api/runtime 1): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
> DEBUG 2018-09-26 16:30:11,090 [api]:Fetching game library
> DEBUG 2018-09-26 16:30:11,255 [steam]:Watching Steam folder /home/goldsteal/.local/share/Steam/steamapps
> DEBUG 2018-09-26 16:30:44,205 [runner]:Installing libretro (version=None, downloader=None, callback=<function libretro.install..install_core at 0x7f01077da7b8>)
> INFO 2018-09-26 16:30:44,205 [runner]:Getting runner information for libretro
> ERROR 2018-09-26 16:30:45,288 [http]:Unable to connect to server (https://lutris.net/api/runners/libretro): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
> DEBUG 2018-09-26 16:31:01,827 [runner]:Installing higan (version=None, downloader=None, callback=None)
> INFO 2018-09-26 16:31:01,827 [runner]:Getting runner information for higan
> ERROR 2018-09-26 16:31:01,879 [http]:Unable to connect to server (https://lutris.net/api/runners/higan): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
> DEBUG 2018-09-26 16:31:07,308 [runner]:Installing dolphin (version=None, downloader=None, callback=None)
> INFO 2018-09-26 16:31:07,308 [runner]:Getting runner information for dolphin
> ERROR 2018-09-26 16:31:07,361 [http]:Unable to connect to server (https://lutris.net/api/runners/dolphin): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
> DEBUG 2018-09-26 16:31:10,676 [runner]:Installing ags (version=None, downloader=None, callback=None)
> INFO 2018-09-26 16:31:10,676 [runner]:Getting runner information for ags
> ERROR 2018-09-26 16:31:10,729 [http]:Unable to connect to server (https://lutris.net/api/runners/ags): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>

Additional info: 
`python --version`
> Python 2.7.15rc1

`python3 --version`
> Python 3.6.6

**Comment by goldsteal** [comment]
Likely same as #1140

**Comment by strycore** [comment]
yes, duplicate issue, closing this one
