### ISSUE TITLE
Login Failed - Service returning 403

### ISSUE THREAD

**Issue by mmcdole** [lutris/lutris#1111]
Apparently 3 people have reported the same issue on Discord including myself.

I'm running Lutris 0.4.19 on Arch linux (4.18.6 kernel).

I'm able to create an account on Lutris.net's website and login via the website.  However, when I attempt to login via the Lutris application, I get a "Login Failed".  When I run it with the debug parameter I get:

ERROR    2018-09-14 15:43:37,793 [api]:Unable to connect to server (https://lutris.net/api/accounts/token): HTTP Error 403: Forbidden

Let me know if you need any further information.

**Comment by ExZiByte** [comment]
I get the exact same error

OS: Debian 9 Stretch

**Comment by tannisroot** [comment]
I experience the same. 
OS is Arch but I don't see how it's related.

**Comment by mmcdole** [comment]
I was able to succesfully make a call to https://lutris.net/api/accounts/token via [Postman](https://www.getpostman.com/) and was returned a token.  Not why the Lutris client call fails when Postman does not.

**Comment by athompson11** [comment]
Running a call to the appropriate API url via requests yields the appropriate JSON.
`>>> r = requests.post('https://lutris.net/api/accounts/token', data={"username":"MyUsername","password":"MyPassword"})
>>> r.content
b'{"token":"MyToken"}'
But URLLIB in particular yielded 403, so I went and took a look at the HTTP request that the library makes through Wireshark (since I already had it open), and found out that Lutris.net yields 403 to the URLLIB Useragent.
Spoofing a Useragent via a Request object then produces the correct results.
`>>> req = urllib.request.Request(login_url,data=None,headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36'})
>>> request = urllib.request.urlopen(req, credentials, 10)
>>> request.read()
b'{"token":"MyToken"}'`
So this is a problem on the Website's end, not the client's.
A simple fix would be spoofing a Useragent, or simply changing it to something different (i.e. "Lutris")

**Comment by strycore** [comment]
I switched the CloudFlare security level to Low. Let me know if this changes anything

**Comment by mmcdole** [comment]
@strycore I'm still getting 403s.

**Comment by athompson11** [comment]
@strycore - Unfortunately, that results in the same problem.
```
>>> from lutris.api import *
>>> credentials = urllib.parse.urlencode({'username': "AbbieAdams",'password':'radarada1'}).encode("utf-8")
>>> login_url = settings.SITE_URL + "/api/accounts/token"
>>> try:
...     request = urllib.request.urlopen(login_url, credentials, 10)
... except (urllib.error.URLError) as Exception:
...     with open("response.html", "w") as file:
...         file.write(str(Exception.read()))
... 
3198
>>> import webbrowser
>>> webbrowser.open("response.html"
... )
True
>>> Created new window in existing browser session.
```
![This is the full text of the response](https://imgur.com/a/n3MJtZC)

**Comment by athompson11** [comment]
The changes made to the settings have now solved this issue.
