### ISSUE TITLE
Icon sync blocks the UI

### ISSUE THREAD

**Issue by Medath** [lutris/lutris#1292]
I've been noticing for a few weeks now that Lutris *sometimes* takes quite long to launch. It does not always happen and does not seem to follow a certain pattern but it is very definitely real. It also does not happen to everyone, but I'm [certainly not alone with it](https://forums.lutris.net/t/lutris-is-opening-very-slow/3602).
I started noticing it around the time when all stuff got moved to CloudFlare or something but I thought it would magically disappear over time.

[I also recorded it in case someone does not believe me](https://www.youtube.com/watch?v=J4l5qwsZpco)

**Comment by sigmaSd** [comment]
for now as an ugly hack u can hardcode `self.timeout` https://github.com/lutris/lutris/blob/master/lutris/util/http.py#L28 to low value maybe 1, I'm curious whats the solution to these network behaviors

**Comment by sigmaSd** [comment]
If my guess is right and this issue is really bothering u u can do something better since its probably only lutris sever you're having problem with, 
```python
if 'lutris' in self.url:
    self.timeout = 1
else:
    self.timeout = timeout
```

**Comment by strycore** [comment]
> The runtime update could then be done in the background while the client is running.

This is *exactly* what we're doing <_<

**Comment by manuelVo** [comment]
I had a closer look at the code that's responsible for this. You're right, runtimes get already downloaded in the background. However [checking for new runtimes](https://github.com/lutris/lutris/blob/2e8ae0a12f905ee71f971fbeeee3e6b5eb1ae7ef/lutris/runtime.py#L149) isn't which is enough to slow down the start significantly if the connection to the server is bad for some reason.

**Comment by sigmaSd** [comment]
I played around with this I added an `Asynccall` inside the update fn https://github.com/lutris/lutris/blob/2e8ae0a12f905ee71f971fbeeee3e6b5eb1ae7ef/lutris/runtime.py#L134 when calling `iter_runtime` it solved the first issue , but there are other problems, turns out `Asynccall` in https://github.com/lutris/lutris/blob/master/lutris/gui/lutriswindow.py#L382 and https://github.com/lutris/lutris/blob/master/lutris/gui/lutriswindow.py#L411 have some weird interaction when more than one callback have `glib.idle_add` basicly the fn becomes blocking, removing one of the `glib.idle_add` solves the issue, I actually don't understand `glib.idle_add` utility here the fn is already called in another thread can't we just remove it or I'm missing something?

**Comment by strycore** [comment]
https://youtu.be/WVp4KtAiF2M

**Comment by Medath** [comment]
@sigmaSd Should be done now.
