### ISSUE TITLE
Lutris doesn't show icons embedded in .exe when you manually add a game

### ISSUE THREAD

**Issue by setsunati** [lutris/lutris#1318]

**Comment by setsunati** [comment]
Creating a desktop shortcut and application menu shortcut doesn't show correct icon.

**Comment by Myrddin-Wyllt** [comment]
I have a question regarding this. In the process of migrating from PlayOnLinux4 to Lutris, I ran into an issue where games are given the wrong icon by Lutris. I'm fairly certain Lutris isn't using icotools currently. I know you can manually set the icons to the ones used by PlayOnLinux, but is icotools support planned as a feature for Lutris for manually added games?

### Here's a screenshot of what I'm talking about:
![image](https://user-images.githubusercontent.com/42914865/65395753-baaed980-dd64-11e9-895e-2a8b48ce3b5e.png)
The top is PlayOnLinux's icon; the bottom is Lutris' incorrect icon.

**Comment by Myrddin-Wyllt** [comment]
Many games have missing or incorrect icons because Lutris doesn't have icoutils integration yet. The best solution would allow the user to choose an embedded icon from a selected exe with previews for convenience. Often icons are embedded into the main executable, but other times, the icon resides in another exe; so there needs to be an option to select which exe to extract icons from (independent of the executable chosen for the game).

**Comment by toyo-chi** [comment]
There is a small Python project for extract icons from executables.
https://github.com/firodj/extract-icon-py
May be it would be useful.

**Comment by fschaupp** [comment]
nice 💪
