### ISSUE TITLE
Not possible to set custom runner without downloading and installing Lutris' default

### ISSUE THREAD

**Issue by Freso** [lutris/lutris#132]
Only tested for Wine, but looks like the same is true for other runners. If you're on a limited bandwidth connection (or just a sucky one), you may wish to reduce your net usage to a minimum, which also means not downloading things already lying around on your disk.

**Comment by strycore** [comment]
We have dropped support for system-wide installed runners because we can't know for sure what version will be installed (scummvm and mame/mess come to mind). We could eventually add an 'override_executable' as a runner option to let the user customize the runner path.

**Comment by Xodetaetl** [comment]
This is now possible for Wine (in the `next` branch): I made the Configure button available even when the runner is not installed, so you can globally configure the "Wine version" to System.

**Comment by strycore** [comment]
What's the status on this issue? We're not going to fallback to system-wide runners and wine is the only runner that can use a custom location. My proposed solution for little to no internet connection would be to offer an archive containing all runners + the runtime along with a script to extract them in the correct locations. Of course, this assumes that the user has access to a proper internet connection for at least a few minutes in order to download the archive.
Something similar will be available for games in the next releases so it would be nice to have that for runners as well.

**Comment by Xodetaetl** [comment]
Adding a `Custom executable` option to all runners wouldn't be a big deal, would it ?

**Comment by strycore** [comment]
It wouldn't but that would qualify as adding a new feature and we're a bit late to add new features to 0.3.7 (unless you really want to add it then go for it!)
