### ISSUE TITLE
Downloads stall when the machine under high load

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#1369]
There goes a really fucked up one.

Whenever my machine is under heavy load, the downloads stall. I wasn't able to download any Wine build while I was compiling other builds of wine on the same machine.

I think this might be because GLib.timeout_add or something else in the Gtk event handling loop is rendered completely useless by the heavy load.

I have **zero** clue how to fix this.

**Comment by sigmaSd** [comment]
I tested with cpuburn and maxed out all cores to almost 100% and I still  could download wine builds normally.

**Comment by strycore** [comment]
Maybe it's something more than just high CPU, I'll have to find a way to reproduce this consistently.

**Comment by strycore** [comment]
Also, it seems that downloads can stall when the machine isn't under load, @tannisroot mentioned the 3.20 build stalling but the 3.20 build is fine.

**Comment by sigmaSd** [comment]
Also tested on high disk I/O and the downloading still works fine.
Couldn't be just a random network issue?

**Comment by LoveIsGrief** [comment]
Looking at Dowloader, it uses [Request::get](https://github.com/lutris/lutris/blob/9ce1cd8394d2a65b6c5e8959549a797a7c74ab81/lutris/util/http.py#L48), which is a custom downloader implementation. Instead of rolling your own request lib, it might be prudent to simply use [`requests`](http://docs.python-requests.org/en/master/) which handles many usecases.

I resigned to downloading wine simply with `aria2c` instead of writing prints all over the place and trying to debug. My opinion might be worth nothing here, but I cannot recommend `requests` highly enough.

**Comment by strycore** [comment]
lutris.util.http is a wrapper around python's urllib. requests is a wrapper around python's urllib. 
If there is a bug in the lutris HTTP wrapper it has to be fixed, switching to requests is just not worthwhile just on the basis of a supposition that it might eventually fix a bug. 
I will oppose a lot of resistance when it comes to introducing new 3rd party dependencies to the project.

**Comment by LoveIsGrief** [comment]
When a mature lib exists that has most likely treated a host of bugs that a custom lib is bound to run into, I advocate for the mature lib. I'm not trying to disrespect the effort lutris devs poured into their wrapper.

In any case, that's all I have to say on that topic. To stay on the topic of the bug, I ran into it with a slow as hell internet connection. The downloads stalled at a speed < 0.07MB/s. If you have a way to throttle speed, maybe you'll reproduce it.
