### ISSUE TITLE
[0.5.0-beta] UI fix, show last game log is awkward

### ISSUE THREAD

**Issue by Vosester** [lutris/lutris#1460]
Show last game log, is now really awkward to use, as the button only show when running an game.  
That means I have to press the button before the game launches. 
If I forget to press the button the headbar disappeared after quitting the a game, there is now, no way I see of getting the log up. 

It would be nice if the old menu bar style could toggled for people that don't like the new GTK style.

**Comment by strycore** [comment]
I know about this problem but the lack of the old menu is not the problem here. The old UI was built around a single game being run at one given time. Now, Lutris properly handles multiple games running at the same time more properly, we have to account for that in the UI as well. 
The UI updates I have planned should solve this issue

**Comment by strycore** [comment]
The log button now stays on the game panel even after it has quit. I does goes away when another game is selected and when going back to the original game, might change that behavior by keeping a cache of previously executed games (say, the last 5 games) where the logs can still be accessed, just need to keep a reference in memory of the running games.
