### ISSUE TITLE
Add DXUP's D3D9 implementation as an option

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1614]
- Introduce DXUP option in the Configuration menu
- Allow to choose from multiple versions, host them on Lutris servers
- Copy DXUP's d3d9.dll and replace Wine's dlls with it if the option is activated, override with WINEDLLOVERRIDES=
- Force activate DXVK as Wined3d does not function correctly with DXUP.
- Code from DXVK option could be reused.

**Comment by tannisroot** [comment]
Very similar to https://github.com/lutris/lutris/issues/1400 but it's worth creating a separate issue specifically for DXUP.

**Comment by Bumbadawg** [comment]
- VK9 code is far from being mature
- DXUP's D3D10 is less feature-complete than DXVK's D3D10 integration.
- DXUP's D3D9 is less feature-complete than Wine with PBA patches and doesn't improve on that last's performance.
- DXUP dev hasn't contacted VK9 dev but that's not important.
- DXVK dev has looked up DXUP work and doesn't want to merge since he wants to complete DXVK first.

**Comment by tannisroot** [comment]
@Bumbadawg 
1. I don't mention VK9, it is indeed way too incomplete atm.
2. I only request support for DXUP's D3D9, not D3D10
3. The project is maturing at a rapid pace and it's not unlikely that it will be mature enough by the time 0.5.1 ships
4. Huh???? Joshua sometimes helps Chris with VK9 on VKx discord.
5. Ok so???

**Comment by strycore** [comment]
this project is not mature enough to be included in lutris
