### ISSUE TITLE
GTK 2.0 support?

### ISSUE THREAD

**Issue by orbea** [lutris/lutris#164]
Would it be possible to add support for GTK 2.0 themes for Lutris?

**Comment by Xylemon** [comment]
I would love this as well, but I remember reading the devs completely switched over to GTK3 and it seems like they have no interest in GTK2 anymore sadly. I know of other applications such as SpaceFM that support compiling a GTK2 or GTK3 version, would be awesome if lutris could support this too.

**Comment by skybon** [comment]
AFAIK SpaceFM is written in pure C and therefore can use a subset of GTK+ 3 classes. In case of Lutris this can hardly be achieved because GTK+ 2 and 3 have different Python bindings: PyGTK and PyGObject respectively. Adding GTK+ 2 support would effectively mean a major rewrite and maintenance of two separate GUIs.

**Comment by TingPing** [comment]
Yes, I would say it is entirely unreasonable.

**Comment by strycore** [comment]
The plan is to make Lutris more toolkit agnostic and provide an API usable from any kind of UI. People have shown an interest in a Qt frontend and Kodi or CLI frontends would also be made possible. This will probably happen for Lutris 0.5. Other than that, no, GTK 2.0 support is not coming back (at least not as a part of the official frontend)
