### ISSUE TITLE
Steam gets launched after shutdown of games that use Steam Wine runner

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1643]
This also affects games that have DRM-less option enabled and it's especially annoying.

**Comment by strycore** [comment]
The steam shutdown should not be here. The Steam shutdown doesn't even have a way of being called right now, since we can't monitor Steam games. I'll just remove the stop method since that was the wrong thing to do. (Running `steam -shutdown` has never quit a game ever, it doesn't have a force shutdown feature like lutris has)
