### ISSUE TITLE
Integrate protontricks

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1646]

**Comment by strycore** [comment]
protontricks is now abandoned software, its author didn't care about the project enough to assign a successor. I think we might as well re-implement the protontricks functionality since in Lutris, it's just a thin wrapper over winetricks. Also, I tried protontricks and it plain didn't work.

**Comment by telanus** [comment]
There is this fork that seems to be the spiritual successor 

https://github.com/Matoking/protontricks

**Comment by strycore** [comment]
Sure looks a lot better than it used to. Doesn't mean we'll use it. We're not gonna use protontricks.

**Comment by Yajo** [comment]
What would be the way to run winetricks today for a proton game? And how to specify its proton version?

**Comment by mihawk90** [comment]
One issue that arises with protontricks is that it requires the game being started in Steam once, so the prefix is created and it creates a `pfx.lock` file in the Proton Prefix. Protontricks will not work unless this file is present.

In the mean time, what is the best way of applying a winetrick to a game via Proton?
Since we don't know the prefix-location beforehand (i.e. the SteamLibrary location being used, especially if multiple are defined), it is impossible to specify the wineprefix for winetricks...

I'm running into this issue with [Grounded](https://lutris.net/games/grounded/), which requires dotnet472 for the audio to work. For now I just placed it in the technical notes, but I would like to implement it in the install script.

**Comment by tannisroot** [comment]
This should probably be a part of a Steam runner overhaul that will improve Proton support

**Comment by R1kaB3rN** [comment]
@strycore I believe it's fine to close this or mark this as completed. 

Since https://github.com/Open-Wine-Components/umu-launcher/commit/f4fb1585c6e4627f577ec80f8228f8c72bf83001, umu-launcher added support for running winetricks verbs with the only requirements being GE-Proton/UMU-Proton and the umu runtime.

With this feature added, Lutris can also become the GUI for winetricks instead of zenity and even create its own whitelist of winetricks verbs since some of them are useless and dubious.

**Comment by strycore** [comment]
Yeah, I agree, we should focus on building our own GUI that can handle winetricks / protonfixes / something else.
