### ISSUE TITLE
Possible to import multiple times from GOG

### ISSUE THREAD

**Issue by thom-github** [lutris/lutris#1705]
Trying out the new GOG integration (THANKS FOR THIS!), but I find it a bit cumbersome right now.

Most importantly (to keep to one single issue): It looks as if every time I click
 "+"
"Import Games"
"GOG icon"
"Select all"
"Import games"

All 79 games get added to my library (which, btw, is well less than what I have on GOG).
Is that intended behaviour? I mean, I have those games 4 times in my lib now, took me that long to realize what's happening. And that just neither feels nor looks right.

**Comment by 8BitCerberus** [comment]
It grabbed 197 of my 271 games... I'm wondering if it's only grabbing the games with native Linux versions? I keep trying to get it to import Hellblade but it refuses to. I had been trying to just import Hellblade instead of the entire library until now, kept wondering what I was doing wrong.

Hmm... no, I just checked and it imported Jade Empire which doesn't have a Linux version.

**Comment by thom-github** [comment]
Since you've been fiddling with it as well: Does "Importing" multiple ......

Interesting. It's gone. All my games are only showing up once, even if I import over and over again. Still on 0.5, btw.

Well, that leaves the "not importing all games" bit, but there is / was an issue for that already
[https://github.com/lutris/lutris/issues/1458]
but that's been closed. Looks to me as if the issue is actually not fully resolved?

**Comment by 8BitCerberus** [comment]
I think the duplicate import is just a visual bug, I did the same but restarting Lutris everything was back to the single icon/banner.
