### ISSUE TITLE
Linux system-installed games added to library on every Lutris startup

### ISSUE THREAD

**Issue by xalmat** [lutris/lutris#1712]
On my system, I have several games installed directly from my OS's package manager (in this case, the KDE games).

Every time I launch Lutris, it re-adds these games to the library. Its to the point that my library is overloaded with duplicates.

![image](https://user-images.githubusercontent.com/38041907/52177556-fd915200-277f-11e9-80e2-bce8bebb72c1.png)

**Comment by basxto** [comment]
Maybe disable the `Sync all games at startup` for now. (Add game -> Import Games… -> Desktop games)

**Comment by rliden** [comment]
I have this same issue. I've disabled 'sync on startup' and that seems to have halted the issue.

**Comment by xalmat** [comment]
Confirmed, disabling 'sync on startup' halts the issue.

**Comment by MartinX3** [comment]
Confirmed

**Comment by thom-github** [comment]
The same happens with Linux versions of games installed from GOG. And yes, disable sync fixes this.
version 0.5.0.1

**Comment by thom-github** [comment]
Oh, also: When I removed all but one of my "Pillars 2" game entries (without deleting game data, obviously) and I kept the one that had "x hours played" on it, suddenly that starter didn't work anymore. It had lost the game path in the settings, so I had to set it correctly again, after which it worked just fine.

**Comment by Anarch157a** [comment]
This issue is still happening with GOG in Lutris 0.5.6 and master.

I tried debugging the issue and figured out that in commit  6dae319, in the line:

`if game["configpath"] == params.get("configpath"):`

`params.get("configpath")` does not return a configpath, because the function `add_or_update` is not receiving configpath as parameter.

This happens because the method `sync` in `lutris/services/gog.py` does not pass a configpath. The parameters that `sync` passes are the ones it gets from the GOG API, which obiously doesn't have such information.

Removing the line mentioned above apparently fixed the issue with GOG games being added multiple times.
