### ISSUE TITLE
[RFE] Start Lutris minimized when a game is launched using an application menu shortcut

### ISSUE THREAD

**Issue by AsciiWolf** [lutris/lutris#1720]
Previously, when running a game using application menu shortcut without having the Lutris application open, the game was launched without opening a Lutris window. This is not the case since Lutris 0.5 - Lutris window is now opened, then the game is launched. Please, consider implementing an option to launch the Lutris window minimized or to not launch it at all just like before 0.5.

**Comment by Videonauth** [comment]
Yes please, I would love to have this behavior as it was before, otherwise making shortcuts makes no sense at all if then the lutris main window pops up anyways.

**Comment by dylanparry** [comment]
I use a couple of applications via Lutris that I have set to open on startup, and as the Lutris window now also appears I have to close it each time I boot my laptop. Previous behavior was to not have any extra windows appear, and was far better imho.

**Comment by foresto** [comment]
This also applies to launching a game with a "lutris lutris:rungame/game-name" command line.

Half the point of launching this way is to avoid Lutris' launcher menu, so the fact that version 0.5 opens the menu anyway effectively breaks the feature.

It is especially annoying with games that have their own launchers. For example, my linux desktop's menu (which is a launcher) opens lutris (another launcher) in order to open Battle.net (a third launcher) to log in to Overwatch. Yo dawg, I heard you like launchers.

This is ridiculous. I hope the old behavior is restored soon. Bonus points if we can tell lutris to exit immediately instead of continuing to run in the background after launching a game directly.

**Comment by kerozoli** [comment]
@foresto It's already in the "to do" list for 0.5.1 so I think no need to write upset comments

**Comment by foresto** [comment]
Not upset. Just describing the current user experience.
