### ISSUE TITLE
Origin Installation Failing

### ISSUE THREAD

**Issue by Mr-Pyro** [lutris/lutris#1762]
I have been trying to install Battlefield 1. The installation script keeps failing with "PermissionError(13, 'Permission Denied')".

https://forum.level1techs.com/t/lutris-permission-error/138754/11

https://forum.level1techs.com/uploads/default/optimized/3X/e/7/e730b22f2dfb70b8dfbce44ea49e7d796b92d6ba_2_720x297.png

**Comment by tannisroot** [comment]
did you try running lutris as root?

**Comment by Mr-Pyro** [comment]
Yes, Origin then runs, but does not progress past the loading screen. Lutris also complains about not needing to be ran as root.

**Comment by tannisroot** [comment]
Well, you really weren't supposed to do that. It can mess up your whole system and is very dangerous.
The reason you were getting permission is well, because your permissions were messed up.
I suggest deleting everything lutris and wine related in your home folder and trying it again.

**Comment by strycore** [comment]
how are we sure that the permissions were messed up?

**Comment by tannisroot** [comment]
>Running /usr/bin/wine /home/*****/.cache/lutris/installer/battlefield-1/OriginThinSetup.exe /silent

ok, I am blind. Another person on Discord had the same issue and it was because there was something wrong with their System Wine (and Lutris is using it because of https://github.com/lutris/lutris/issues/1760). After you get your system cleaned up after running lutris as root, I suggest to first download Wine from Wine Versions menu and only then run the installer.
Here's how you do it:
![peek 2019-02-12 04-24](https://user-images.githubusercontent.com/10602045/52839352-e0a53900-3106-11e9-8c98-f6e3cc413cbb.gif)

**Comment by Mr-Pyro** [comment]
> (really sorry my message kind of implied to run it as root :( ). 
its all good.

So I tried your suggestion and now it will install and run, but no gui or anything visual opens.

**Comment by tannisroot** [comment]
Can you hop on Lutris' Discord or IRC? It's a better place to troubleshoot stuff.

**Comment by Mr-Pyro** [comment]
Could I get a link to the Discord?

**Comment by tannisroot** [comment]
https://discord.gg/Pnt5CuY

**Comment by strycore** [comment]
this is considered solved.
