### ISSUE TITLE
Potential for Epic Games runner

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1794]
I know how to launch a game but still need to figure out the other two.

- [x] Launch
- [ ] Install
- [ ] Uninstall

```
com.epicgames.launcher://apps/Tulip?action=launch&silent=true
```

This is proving more difficult than Uplay and Origin. I've given up for the time being. You can close this if you want.

**Comment by strycore** [comment]
is the flickering issue resolved on the Epic launcher?

**Comment by AccountOneOff** [comment]
No, but there's a workaround I found. If you use that argument it'll launch Epic in the background then you use the tray icon to open it and the flickering doesn't happen.

**Comment by Alexander88207** [comment]
To solve the flickering issue the launcher must be started with dxvk like in Origin.

**Comment by Odelpasso** [comment]
I have a problem with Epic Launcher. When i connect to my account, the application crashes. I have the same issue if i decide to launch Epic without to connect to my account.

It works for you ?
I use Wine-Staging 4.2.

**Comment by Alexander88207** [comment]
Now it flickers for me also maybe the launcher no longer use directx 11.

**Comment by buxel** [comment]
Is there still any interest in this? I started working on this as a side project and this is how far i got:

**Works**
+ Installing EGS as runner
+ Importer for installed games to lutris
+ Launching games
    + DRM free
    + Trough EGS

**Issues**
- still (ab)using steamId in some places
- save/load settings takes a while because wine registry is initialized each time
- lutris does not see game exiting thinks its still running when launched wtrough EGS
- most likely some dead code from winesteam

**Not working**
- quit EGS after game exits
