### ISSUE TITLE
Lutris can't stop unresponsive processes 

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1798]
If the process for some reason isn't responsive or refuses to close, pressing `Stop` won't work and Lutris will never be able to shut down the game without manual intervention.
Should probably mention @AaronOpfer.

**Comment by AaronOpfer** [comment]
Does right clicking the game and using the "Kill all wine processes" option
stop unresponsive applications?

**Comment by tannisroot** [comment]
Nope, it doesn't.

**Comment by tannisroot** [comment]
But using `WINEPREFIX=the_prefix wineserver -k9` works.

**Comment by AaronOpfer** [comment]
So for a generic solution for all runners: maybe the stop button should become disabled when clicked and change the text to "stopping..." while also revealing a disabled "Force Quit 3" button, which counts down over three seconds ("Force Quit 2", "Force Quit 1") and then becomes enabled. Then, clicking that button would force kill the whole watched process tree without interacting with lutris_wrapper (besides killing it as well). Other options involve actually showing users which processes are still running in the GUI, but adding IPC to `lutris_wrapper` to pull that off sounds like gross overkill. We should just try a simple `kill -9` style tool to users instead.

**Comment by tannisroot** [comment]
Ok, I am so sorry, it seems like `Kill all wine processes` actually does kill the process and I just fucked up when I was testing it.
Does that change anything about how the issues should be approached?

**Comment by AaronOpfer** [comment]
Hmm... not really, other than it being a viable workaround for wine games.
I think what I'd do is add a 30-second waiting period to lutris-wrapper
while it's waiting for processes to close before switching to SIGKILL, but
I don't really like this solution since users will have no idea why
applications are not closing for 30s. Plus, some applications could
legitimately take 30s to clean up after themselves and we'd possibly
interrupt that to some fatal effect.

 Don't DEs usually prompt you to kill unresponsive GUI applications? Does
this need to be lutris' responsibility?

**Comment by tannisroot** [comment]
Oh actually, some processes aren't even exactly unresponsive. They just refuse to close. For example, this happens with Origin all the time, and also with Sims 3 launcher. Origin won't stop unless I press "Quit Origin" in the app itself and Sims 3 Launcher won't quit because it tries to download some data but fails and retries all over again, and it won't shut down unless you manually "Quit" in the UI it as well.

**Comment by strycore** [comment]
This should be considered one of the highest priority bug of the project at this moment.
There are several problems here:
* The UI does sometimes become unresponsive, this should never happen and should be treated in the most critical manner
* There is indeed a missing "stopping" state for the stop button
* The stop button should **already** be a force quit button, it's the reason it's here. It shouldn't have to be used under normal circumstances.
* I'm not changing the Stop button into a "Force quit" button but I would agree to have a dialog open when "Stop" is pressed and show "Stopping [game]..." with a "Force quit" button at the bottom, which could be clicked at any time.

**Comment by AaronOpfer** [comment]
OK; In that case I recommend that the lutris-wrapper be changed so that
when it receives a second SIGTERM it sends SIGKILL to child processes.
Then, the GUI can be taught to make the "Force Quit" button simply send
another SIGTERM. I think this is pretty simple. I'm on vacation right now,
so if you prefer I make the changes to lutris-wrapper, I can do those when
I get back to a computer. In either case I'd like to leave the GUI changes
to other maintainers.

**Comment by AaronOpfer** [comment]
This issue isn't fixed yet. Looks like I accidentally tripped github's auto
issue close feature in my commit message.

**Comment by strycore** [comment]
Reopening

**Comment by tannisroot** [comment]
That PR helped with Sims 3 launcher but yeah, some apps still don't quit after pressing Stop (was testing WoW today when that happened).

**Comment by AaronOpfer** [comment]
So the UX is terrible, but pressing the stop button twice will perform a force kill after my PR. (We should update the GUI so that the button flows from Play -> Stop -> Force Stop to show users what pressing Stop twice actually does).

If you find that pressing stop twice doesn't fix your problem, can you try this patch and tell me if it fixes the issue for you?

```diff
diff --git a/bin/lutris-wrapper b/bin/lutris-wrapper
index 34674e44..52fccb16 100755
--- a/bin/lutris-wrapper
+++ b/bin/lutris-wrapper
@@ -86,7 +86,7 @@ def main():
         signal.signal(signal.SIGTERM, hard_sig_handler)
         signal.signal(signal.SIGINT, hard_sig_handler)
         monitor.refresh_process_status()
-        for child in monitor.children:
+        for child in monitor.children + monitor.ignored_children:
             log("passing along signal to PID %s" % child.pid)
             os.kill(child.pid, signum)
         log("--terminated processes--")
```

**Comment by tannisroot** [comment]
@AaronOpfer yep, that patch helped!

**Comment by strycore** [comment]
ok, closing then

**Comment by tannisroot** [comment]
What? No, that patch is not in master yet and this still needs UI changes that Aaron requested.

**Comment by AaronOpfer** [comment]
I put a better version of that patch into my PR but as @tannisroot said, there's GUI changes that really should be made still and I'm generally not comfortable messing with the GUI and think another maintainer should do it.

**Comment by strycore** [comment]
is there still stuff going on with this issue?

**Comment by tannisroot** [comment]
Yes. Best test app for this is Origin, it just doesn't respond to the button whatsoever.

**Comment by strycore** [comment]
Started Origin, pressed Stop, it stopped, closing
