### ISSUE TITLE
Witcher 3: Black screen if DXVK 'enabled'; if 'disabled' DXVK still appears to load

### ISSUE THREAD

**Issue by DucDuNord** [lutris/lutris#1824]
* System: Kubuntu 18.10, x64 architecture, 16 GB RAM, Intel and Vega56 GPUs.
* Lutris version: 0.5.0.1
* DXVK versions tried: 0.94, 1.0.
* Runners tried: Wine-Staging 4.2, tkg-4.0, tkg-4.2.
* Vega56 GPU enabled by setting DRI_PRIME=1 from within the Lutris interface. 
* Witcher 3 version: GOG GOTY, installed with Lutris installer on website (current version).

**Description**
If The Witcher 3 is launched from within Lutris with DXVK set to 'enabled' only a black screen is produced. No audio can be heard playing. The DXVK HUD gives the FPS as approx. 0.5-1.5.

If The Witcher 3 is launched from within Lutris with DXVK set to 'disabled', however, the game runs correctly. The performance is excellent at 2560x1440, which leads me to believe that the game is, in fact, still using the DXVK dll files: there is no stuttering, and shaders function as expected. 

Interestingly, DXVK produces no log files if set to 'disabled' from within Lutris and the HUD won't load, so I am not sure how to 'prove' this.

All in all, what I suspect happens is that Lutris somehow attempts to load DXVK twice.

**Comment by DucDuNord** [comment]
**EDIT/ADDITIONAL INFORMATION**
If, in the Witcher user.settings file **vsync** is set to false, The Witcher 3 _will_ load with DXVK enabled in the Lutris menu. 

Of course, this still does not explain why DXVK would load even if 'disabled', or why Lutris produces a blackscreen if DXVK is set to 'enabled'.

**Comment by DucDuNord** [comment]
I don´t know why you wouldn't want to fix this (there is a report at https://lutris.net/games/the-witcher-3-wild-hunt/ that suggests other persons have run into the same issue), but if you require more or different information, please let me know what kind of information is needed.

Vsync=true is a default setting which is enabled by the game installer. This makes it likely that other persons who run into this problem will not know what to do - they will probably not even have had the opportunity to change any of the in-game settings.

Finally, I just discovered that the problem does not occur if the game is launched using the command **DRI_PRIME=1 wine witcher3.exe** from a console: the game will run normally irrespective of whether vsync is enabled. In other words, it does appear that there is a problem with how Lutris launches the game.

**Comment by tannisroot** [comment]
>Interestingly, DXVK produces no log files if set to 'disabled' from within Lutris and the HUD won't load, so I am not sure how to 'prove' this.

DXVK will always produce log files. If it doesn't, it's not used for sure. The fact than it runs fine without it just means that your system is powerful enough to compensate perfomance loss with it.
> Vega56 GPU enabled by setting DRI_PRIME=1 from within the Lutris interface.

Lutris will override DRI_PRIME value set in the envars section because of PRIME option. So if you haven't enabled that feature in the config, DRI_PRIME will always be set to 0.
Also, that option is a bit bugged out in 0.5.0.1 as some for some users it's greyed out even if PRIME is available. Fortunately, it's fixed in master, so you should using that.
Since this is not an actual bug, as it turned out, I am going to close this.
If you wish, we may continue discussion about this either right here on Lutris's Discord (preferably).
