### ISSUE TITLE
Tone down gradient effect on coverart

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1831]
It's a liiittle too dark. Just a touch on the bottom.

![screenshot from 2019-03-02 17-46-02](https://user-images.githubusercontent.com/15083452/53690011-4f91ad00-3d17-11e9-991c-bf3d9036f75b.png)

**Comment by strycore** [comment]
This is just about adjusting a PNG image so it should be pretty easy for anyone to fix, it only requires GIMP

**Comment by AccountOneOff** [comment]
I was gonna ask. I've been searching around on how to do it. Still don't know how.

**Comment by tannisroot** [comment]
@AccountOneOff this is the file for the gradient mask https://github.com/lutris/lutris/blob/master/share/lutris/media/mask.png

**Comment by tannisroot** [comment]
In my opinion, it looks fine? I wouldn't change anything.

**Comment by AccountOneOff** [comment]
I know what file it is I just don't know how the fuck to do it.

**Comment by tannisroot** [comment]
You could either adjust the transparency of the picture to make the gradient lighter or create a new gradient using https://docs.gimp.org/2.2/en/gimp-tool-blend.html

**Comment by strycore** [comment]
The picture is a mask, so the areas with full opacity will show the original image and the parts with full transparency will show none of it.

To make the background image more visible, you have to darken the gradient a bit, which will make the original more visible (it's not really appropriate to reason in terms of dark / bright here because this varies based on the Gtk theme variant being used).

**Comment by strycore** [comment]
This doesn't need a ticket, if someone wants to change the gradient they can just do it.
