### ISSUE TITLE
Big logs freeze Lutris' UI

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1858]
Perhaps Lutris could do logging in a separate thread?

**Comment by AaronOpfer** [comment]
I can look into this.

**Comment by AaronOpfer** [comment]
Does #1861 improve the situation for you? There's more performance improvements that can be made still, it may be possible to squeeze another 3x improvement out of it before we have to consider other threading options.

**Comment by tannisroot** [comment]
It's noticeably less laggy, but something as huge as WINEDEBUG=+d3d9 still completely locks it up. Although it's not really something that a regular Lutris user would enable.

**Comment by AaronOpfer** [comment]
I added another commit which improves performance another 2.5x or so by making `lutris.game.Game.log_buffer` lazy initialized only when it's needed. Try the latest version of my PR and see if we're in the clear yet.

**Comment by AaronOpfer** [comment]
I just added one more change to handle logs in large read chunks (up to 256KB) instead of one line at a time which should greatly increase the rate at which logs are consumed. I have a test linux game in Lutris that outputs data as fast as it can and every improvement in Lutris just results in that application outputting data faster and overwhelming Lutris again, so at some point we just need to declare a certain rate of log consumption "good enough" or make Lutris no longer the middleman for these logs.

**Comment by tannisroot** [comment]
This is great! There is absolutely 0 freezing now until you open the log itself, even with +d3d9. But when you do open it, it locks up. And if you open the log as soon as the game starts, it will just print the log line by line without locking anything up until it reaches the end (even after you close the game itself). I think it's a huge improvement.

**Comment by AaronOpfer** [comment]
Hmm, I see that. Maybe it's because the `log_buffer` and the `MonitoredCommand.stdout` both grow unbounded? We should have a limit on both of those.

**Comment by strycore** [comment]
If this partcular issue is solved then it can be closed.
