### ISSUE TITLE
Add screen resolution variable to the installers

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1874]
So that instead of enabling Virtual desktop (which is absolutely needed for a lot of Unity games) like this:
```
winesteam:
  Desktop: true
  WineDesktop: 1920x1080
```
I could just do this:
```
winesteam:
  Desktop: true
  WineDesktop: $RESOLUTION
```
where in place of $RESOLUTION actual resolution of the machine's main display would be parsed.

**Comment by Medath** [comment]
I think an `auto` option would be better than using a variable, which would write the actual resolution into the config, because then lutris would be able to dynamically choose the resolution depending on the monitor that's currently used (So the user wouldn't have to change the config when getting a new monitor or something)

**Comment by strycore** [comment]
@Medath this is not possible. What @tannisroot suggest is correct.

**Comment by strycore** [comment]
@tannisroot I added the variables but I also added a note in the docs about not using them for virtual desktops.
