### ISSUE TITLE
Implement file globbing in src and dst params and strings subject to _substitute

### ISSUE THREAD

**Issue by sparr** [lutris/lutris#1887]
Use case 1: copy many files to a destination (`cp src/* dst/`)

Use case 2: copy to a destination  folder without knowing the suffix (`cp file dst*/` when destination might be dst-1.0/ or dst-1.1/)

Use case 3: set environment variables to files without knowing their precise name or location (`env: SOMEKEY: /usr/lib/somelib*.so`)

per discussion on Discord, this might be implemented directly in the src and/or dst params for `merge` and other functions with parameters that are always files, using `glob.glob()`. For src all matches would be used, for dst only the first match.

For arbitrary strings subject to `_substitute`, @strycore suggests implementing `$SEARCH(some*glob)` which would resolve to the first matching path/file.

This would be an alternative to the rejected #1884

**Comment by sparr** [comment]
`$SEARCH` might be more self explanatory if it had `FILE` or `PATH` in its name

**Comment by strycore** [comment]
first use case isn't valid, that's just what the merge command does, what is valid though is if a pattern needs to be copied, like `src: $CACHE/music/*.mp3`

second use case is a bit weird, I'd need proof that this is needed, otherwise don't implement globbing on dst params.

3rd use case is valid and can be handled with the $SEARCH

globbing support should only be added to merge / move at first so we can test on a few existing installers.
We also need a real installer where that $SEARCH thing is used (an actual game that needs it)

**Comment by strycore** [comment]
globbing can also be added to the file argument of the extract command: https://lutris.net/games/install/1574/view
