### ISSUE TITLE
Lutris crashes on startup when gvfs is missing

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1918]
Reported by a user on Discord:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 221, in do_command_line
    run_all_checks()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 154, in run_all_checks
    check_donate()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 121, in check_donate
    open_uri("https://lutris.net/donate")
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 42, in open_uri
    Gtk.show_uri(None, uri, Gdk.CURRENT_TIME)
GLib.Error: g-io-error-quark: Operation not supported (15)
INFO     2019-03-23 14:02:16,819 [application.do_shutdown:441]:Shutting down Lutris
```
They fixed it by installing `gvfs-backends`. In that case, Lutris should add it as a dependency as well.

**Comment by Kemichal** [comment]
Same here on kubuntu 18.04. Installing `gvfs-backends` worked.

**Comment by TingPing** [comment]
That seems a bit strange, it shouldn't depend on any of that.

**Comment by RobertZenz** [comment]
This should actually be an indirect dependency, as GTK is trying to handle the link but fails to do so because the gvfs-backends is missing.

**Comment by TingPing** [comment]
GVFS isn't actually used at all in this process so there is some bug going on in Gio.

**Comment by RobertZenz** [comment]
@TingPing Not really as far as I can see. GIO is being handed an URL (most likely) which it tries to resolve by using GVFS which is missing. The thrown exception "Operation not supported" seems right in that case. Lutris could handle that, but the question is what breaks with it.

**Comment by foresto** [comment]
For the record, this Gtk.show_uri() "Operation not supported" error can occur even when gvfs-backends is already installed, and can turn up in other parts of Lutris. (I got it when using the Browse Files menu option on a game, and found a similar failure when trying to open the https://lutris.net URL from the About dialog.)

The problem is that gio/gvfs/gtk keeps its own registry of handler applications, and ignores standard linux tools like xdg-open, even if its own registry contains nothing useful for a given type. To fix it, commands like these must be run to register a handler application:

    gio mime x-scheme-handler/https firefox.desktop
    gio mime x-scheme-handler/http firefox.desktop
    gio mime inode/directory Thunar.desktop

The corresponding .desktop files must exist in the appropriate directories, and the programs they represent must also be installed, of course.
