### ISSUE TITLE
Refresh desktop shortcut and app shortcut items

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1948]
When pressing "Create desktop/app shortcut" it won't change to "Delete desktop/app shortcut" until clicking off the game entry.

You can see here it didn't change when I clicked Create app shortcut:

https://streamable.com/0wj1y

**Comment by dino8890** [comment]
Hi,

I took a shot at this and created a decorator for the action callback which toggles the visibility between create and delete shortcut buttons. Do you think this is a proper way to go? I can submit a pull request if you want to review the changes.

Dino

**Comment by strycore** [comment]
@dino8890 I'd like to take a look at it but I'm not sure this is the way I want to go with things.

Since we handle the action in multiple place (contextual menu, sidebar) I think it's better to go with a solution using GObject signals. We've increased the usage of signals in 0.5.x and it has solved a lot of problems we previously had.

**Comment by dino8890** [comment]
I rewrote it to use signals and you're right, it's better this way. I don't know why I didn't do it like this the first time.

Here's the relevant [pull request](https://github.com/lutris/lutris/pull/2056).
