### ISSUE TITLE
New GOG inno packaging breaks compatibility with lutris innoextract and breaks installers

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1949]
>The newest GOG packaging with inno 5.6.2 cannot be extracted using the older(from 2015) innoextract version (which is the default) and neither with the latest stable version(v1.7) which supports up until the inno version 5.6.1 . The result is that many GOG installers requiring innoextract are broken.
As a temporary solution I propose to make available the latest dev version which supports inno 5.6.2.
At the moment you can find the January 2019 snapshot from here 1
Any installer might directly link and download the latest snapshot but maybe the developer will delete or move the dev binary in the future, so a better idea would be for lutris to host it itself in the tools.
I have verified that the latest dev binary works with the newest 5.6.2 packaged GOG files (I have tested with Albion )

https://forums.lutris.net/t/new-gog-inno-packaging-breaks-compatibility-with-lutris-innoextract-and-breaks-installers/5367

**Comment by tannisroot** [comment]
New GOG installers should not use `innoextract` from tools on the website.

**Comment by mastorak** [comment]
Indeed they should not because it doesn’t work anymore. Since there is no stable(latest stable is 1.7) release of innoextract that supports inno packaging 5.6.2 there are two options:
    
- Installers  should link and download directly the dev snapshot of innoextract 1.8. This is less safe as the innoextract developer might move or delete the dev snapshot

- the dev snapshot of innoextract 1.8 should be made available from the lutris tools. This is more safe as binary location is managed by lutris

**Comment by strycore** [comment]
I've made the dev version of innoextract available here: https://lutris.nyc3.digitaloceanspaces.com/tools/innoextract/innoextract-1.8-dev-2019-01-13-linux.tar.xz
Let me know if there is anything else required to support new GOG installers.

**Comment by mastorak** [comment]
Great, thanks!
