### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by yaomtc** [lutris/lutris#1998]
Just now I tried to start a game from Lutris with the keyboard. After experimenting for a moment, I realized hitting Tab does select some items in the interface - however, this is invisible. There's no visual indication of which button is "selected". Can someone make it so hitting Tab shows what's selected? Like, with a thin dotted rectangle or something.

Also, the selection doesn't seem to move past the top bar, so I don't see a way to actually launch any game without using the mouse. Sure, you can filter your games, but hitting Enter doesn't launch the game... It doesn't do anything. Nor do the arrow keys, unless you're moving the text cursor within the search bar.

I think making it possible to use Lutris without a mouse would improve its usability for the disabled/impaired quite a bit. Also, the people that just prefer to use their keyboard.

**Comment by strycore** [comment]
we need to get those kind of issues solved because that would allow having some sort of early full screen UI using sc-controller with lutris.

For the dotted rectangle thing, pretty sure it's a theme issue because I have one on both Yaru and Pop. 
![2019-04-09_18-40](https://user-images.githubusercontent.com/280336/55845513-05120600-5af7-11e9-84b2-f7ea9c1d9fb1.png)

I can reproduce the issue about tabbing through the top bar, although I've noticed that after going past the last element, nothing seems to be selected (pressing space does nothing) so I'm pretty sure that's where the issue resides.

**Comment by veksha** [comment]
#3132

**Comment by veksha** [comment]
Please, consider this pull request #3132

**Comment by veksha** [comment]
Simple keyboard navigation was merged #3185

Tab, Shift-Tab steps through every button/control;
Right/Up keys can be used to move from the left/bottom panel to the game panel;
Down key can be used to move from the search-box (ctrl-f) to the game panel;
If you want to clear search filter just press ctrl-f shortcut again or simply an Escape key.

I think that is all for now.

**Comment by yaomtc** [comment]
Awesome! Thanks a lot. Just installed lutris-git and it's working pretty well.

Only suggestion I'd make would be to have the highlighting continue into all areas so you can always see which of the menu items are in focus. Buttons (like +, Search) get highlighted, but others like sort/zoom, the hamburger menu items, and Manage Runners don't get highlighted.

It's certainly functional now, so I'll close this.
