### ISSUE TITLE
Importing of Steam games that are already in the library (uninstalled) does not make them appear installed

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1999]
How to reproduce:
1. Add a game to your game library on Lutris.Net
2. Relaunch Lutris to let it fetch the new data and add the game to the library
3. Have that game installed locally through Steam
4. Import the game through "Import Games" menu

Expected behavior: the game now appears in the library as installed and is ready to be launched
Observed Behavior: nothing happens, the game remains uninstalled in the library until you manually run the installer it

A lot of users get confused by this because they think the Importing process failed as nothing happens after the importing process.

**Comment by strycore** [comment]
going to mark this as a bug because games imported from the steam service should be set as installed.

**Comment by vahtos** [comment]
I took a stab at this and did not manage to fix it, but can provide some more information in hopes someone more familiar with the project can resolve it.

The issue is in "lutris/services/steam.py", when a game is already added to the Lutris library and then is installed via the steam application (outside of Lutris), the game's installation status is not synced to Lutris. Lutris will not sync the game properly because an entry in the SQlite database already exists and shows it as uninstalled.

More specifically, under the sync() method:
```
if steamid not in self.lutris_steamids:
    added_games.append(game.install())
else:
    pga_game = self.get_pga_game(game)
        if pga_game:
            added_games.append(game.install(pga_game))
```
The steamid is already in self.lutris_steamids, so the game is not added here. I believe you'd need some kind of check under this else statement, or an elif, that compares steam's manifest files (using lutris.util.steam.appmanifest) to the .db file and reconciles conflicting install statuses. I tried doing this, but didn't quite figure out how to do it.

**Comment by codeman101** [comment]
@vahtos I like your attempt to solve the problem. I think it should me re-implemented to only add steamids of games that actually installed and no just because they're in the library.

**Comment by LeXofLeviafan** [comment]
I'm using 0.5.3 and this bug is still present (just tried to import freshly installed Fallout New Vegas and the Thief trilogy from Steam; no reaction whatsoever, not even any lines in log when running `lutris -d` after clicking "Import games")

**Comment by vahtos** [comment]
Confirmed, I am having the same results. I will try to take a look a this soon.
