### ISSUE TITLE
Change DXVK version management and introduce "stable" versions

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2007]
Defaulting to latest DXVK version is a really, really bad idea:
![unknown](https://user-images.githubusercontent.com/10602045/55679784-04704880-591a-11e9-8485-ed44689694ca.png)

**Comment by strycore** [comment]
I was going to modify the current DXVK version management to allow custom builds, like async but given regressions like this one, we might as well make every variant of DXVK a part of the runtime where we can safely upgrade (and even downgrade) at will.

We'll keep some of the existing code to allow specifying DXVK versions. 

Since the DXVK folder structure, we'll have to adjust some of the runtime code to account for that, maybe on the API side as well. I suggest that the default DXVK version gets stored in runtime/dxvk/stable. Then we can also have things like runtime/dxvk/async and all the other versioned folders van stay as well. We have to be extra careful not to break DXVK on older Lutris versions when introducing changes to the runtime. (Adding a `dxvk` runtime to the API will certainly mess with current installations).

**Comment by odysseywestra** [comment]
Another way to combat this on the UI side is to introduce the ability to read changelogs for dxvk and confirm before going to a new version.

**Comment by tannisroot** [comment]
@odysseywestra nobody reads changelogs

**Comment by odysseywestra** [comment]
I guess I'm an edge case since being a gamer you want to keep track of patches that will effect your your game's performance(in the case of Overwatch). Everytime I notice a version change in dxvk, I usually look it up. Still having an option to confirm changes to their options could help.

**Comment by BloodyIron** [comment]
How is Lutris going to handle the advent of d9vk versions in addition to dxvk? Prior, dxvk was a pull-down menu for version selection in Lutris, but going forward, what now?

FYI d9vk hit 0.10 today, and reports are showing Starcraft 2 runs massively better than wined3d.

**Comment by strycore** [comment]
Is this really necessary at this point?

**Comment by tannisroot** [comment]
Yes. And fixing this would be very easy - we merely need to clone DXVK repo, change the repo that dxvk manager fetches releases from to our own and start shipping our own DXVK releases when we feel like the new DXVK version is stable enough. I can do it myself but if you want I can make a build script as well (it would have to be run in an Arch container though, because it's the only distribution with proper mingw packages).

**Comment by tannisroot** [comment]
Forgot to mention why exactly it's still valid issue - for example, D3D9 implementation in DXVK 1.6 currently has a bug that make some objects in Star Wars: Old Republic not render on systems with AMD Graphics. This is fixed in master builds, but for some reason DXVK developers haven't shipped a new release with that fix. If Lutris was able to distribute DXVK versions independently, we could just tag our own version and avoid this bug.

**Comment by strycore** [comment]
why not just set dxvk_version: 1.5 in the SWTOR script?

**Comment by tannisroot** [comment]
I can do that, sure, but what about all the other thousands of games (some of which have several separate installers) that might be suffering from the same issue but we are simply not aware of? Doing it per-game is not a proper solution, plus it's fucking hell because our moderation system is really bad.

**Comment by strycore** [comment]
We ship our own DXVK builds now so that can be closed.
