### ISSUE TITLE
N64 emulation will not work

### ISSUE THREAD

**Issue by TheBlackViper1996** [lutris/lutris#201]
N64 games will not play as I get this error

"UI-Console Error: dlopen('/usr/local/lib/libmupen64plus.so.2') failed: /usr/local/lib/libmupen64plus.so.2: cannot open shared object file: No such file or directory
UI-Console Error: dlopen('./libmupen64plus.so.2') failed: libminizip.so.1: cannot open shared object file: No such file or directory
UI-Console Error: AttachCoreLib() Error: failed to find Mupen64Plus Core library
ERROR    2015-08-31 21:48:12,340 [thread]:Could not kill PID 32380"

However when I use the version of Mupen64Plus from the software centre it works fine,
I managed to resolve the issue with libmupen64plus.so.2 by creating a symbolic link but I have not managed to fix the issue with libminizip.so.1

I managed to do a simple work-around so that Lutris uses the version of Mupen64Plus from the software centre by replacing .local/share/lutris/runners/mupen64plus/mupen64plus with this shell script.

#!/bin/sh
#
mupen64plus "$1" "$2"

**Comment by strycore** [comment]
The error for /usr/local/lib/libmupen64plus.so.2 should not be a problem, it falls back to ./libmupen64plus.so.2 after but there's a problem with libminizip indeed. It can be resolved by running apt-get install libminizip1 but I don't want to add this as a requirement so I'll add this library to the lutris runtime. This is required anyway since this library wasn't available before Ubuntu 15.04.

I tried to update to Mupen64 2.5 (we ship 2.0) and now I run into other problems like flickering in fullscreen or crashes when starting in fullscreen with non-native resolutions.

Mupen needs some more testing and work but I'll make sure to ship  a working emulator when we ship Lutris 0.3.7

**Comment by strycore** [comment]
This particular bug has been fixed with the current runner and runtime used in 0.3.7, there are other issues with this runner but they can be fixed after the release.

**Comment by shimdidly** [comment]
It's 2022 and this same error is still occurring. Here is my log when attempting to use the Mupen64Plus emulator:
`UI-Console Error: dlopen('/usr/local/lib/libmupen64plus.so.2') failed: /usr/local/lib/libmupen64plus.so.2: cannot open shared object file: No such file or directory
UI-Console Error: dlopen('./libmupen64plus.so.2') failed: libSDL-1.2.so.0: cannot open shared object file: No such file or directory
UI-Console Error: AttachCoreLib() Error: failed to find Mupen64Plus Core library
Monitored process exited.
Initial process has exited (return code: 512)
All processes have quit
Exit with return code 512`

**Comment by strycore** [comment]
This is a different error message, you need to install SDL 1.2.
