### ISSUE TITLE
Show donation pop-up only after a certain amount of time

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2011]
New users won't donate to a project that they've just installed.

**Comment by strycore** [comment]
They need to be informed that they can.

**Comment by tannisroot** [comment]
Yes, but only after 1 hour of using it, for example. Or after 10 instance launches.
This is what all mobile app developers do - they never ask the user to rate their app on Play Store/AppStore immediately after launching it, the pop-up appears after a certain time.

**Comment by strycore** [comment]
it doesn't make sense because we don't have a way to determine who's a new users and who's not. Plus we have to add a bunch of code to keep track of how long the client has been used. 
The donation window tells people that the donation page exists. The code associated with it is simple and straightforward. Let's not over-complicate things over what are nothing more than speculations.
