### ISSUE TITLE
 version 0.5.2 no work

### ISSUE THREAD

**Issue by TuxNuX** [lutris/lutris#2018]
![Screenshot_20190410_015604](https://user-images.githubusercontent.com/17123357/55842429-d9f9d780-5b33-11e9-8ea1-b943dff5f1bb.png)

version 0.5.1  good work

**Comment by strycore** [comment]
@TuxNuX is this on Debian?

**Comment by gbschenkel** [comment]
The same error here.
FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig': 'ldconfig'

The `ldconfig` command is not accessible from normal users in some distros(Slackware in my case), because it resides in `/sbin` and isn't in the path. @strycore are you trying to just update the system cache or are you trying to use a specific conf(-f) and/or cache(-C) file?

**Comment by strycore** [comment]
@gbschenkel see the commit that fixed this issue, the initial called assumed ldconfig was in path (we run a call to ldconfig -p to get available libs). I pushed 0.5.2.1 because this was also an issue on Debian.

Please notify the Slackware maintainer of this update so the package can be updated.

**Comment by gbschenkel** [comment]
@strycore The current version of Lutris, on Slackware requires the [desktop-gnome](https://ftp.gnome.org/pub/gnome/sources/gnome-desktop/) package. I manage to build it and the [gnome-desktop](https://gitlab.com/gbschenkel/slackbuilds/tree/current/libraries/gnome-desktop) package and is available in my repo on [GitLab](https://gitlab.com/gbschenkel/slackbuilds) for Slackware current(unstable), as the last version of [Lutris](https://gitlab.com/gbschenkel/slackbuilds/tree/current/games/lutris). Since SlackBuilds.org packages aim to support only stable versions of Slackware, I am trying to create a package for 14.2 on a VM. I manage to built it, but the "most recent version" which I could use on is 3.18.2(2015/11/09) because the version of gdk-pixbuf2 which can't be higher than 2.32.3. Well now I need try it building Lutris to see if will work. If work, I will create the package for the SlackBuild site.

**Comment by TuxNuX** [comment]
> @TuxNuX is this on Debian?

no I 'm Mageia 7 (Cauldron (development version))

new version worked well
but need to add in the spec file
`%post -p /sbin/ldconfig`

**Comment by strycore** [comment]
@TuxNuX nice!

@akien-mga maybe there's something to update regarding the Mageia package?

**Comment by akien-mga** [comment]
@strycore Probably, thanks for the ping. @TuxNuX opened https://bugs.mageia.org/show_bug.cgi?id=24679 so I'll handle it here.
