### ISSUE TITLE
PlayOnLinux Runner

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#213]
A [PlayOnLinux](https://www.playonlinux.com/) runner that would just execute something like:

```
playonlinux://www.playonlinux.com/repository/download.php?id=402
```

... for [Fallout 3 on POL](https://www.playonlinux.com/en/app-402-Fallout_3.html).

**Comment by strycore** [comment]
It's planned but it depends on some features that are not yet ready in PoL, they plan adding a low-level API usable with any GUI which would make integration in Lutris very easy. (cc @qparis)

**Comment by MrTimscampi** [comment]
Wouldn't it be a bit redundant, considering Lutris already has install scripts and support for multiple Wine versions, which is essentially what PoL does ?  
Just wondering, as new user of Lutris.

**Comment by strycore** [comment]
There would certainly be some overlap functionality but it fits in the roadmap of future releases of PlayOnLinux. POL5 will keep its core written in Python but will offer a interface written in Java. The core API separated from the UI allows additional clients, such as Lutris to act as a POL frontend which is what we plan between the POL team and the Lutris team.

**Comment by Konfuz** [comment]
@strycore 

An itermediate solution for people who already have a lot of POL-Stuff installed and try out lutris for the first time could be to just list the scripts under **~/.PlayOnLinux/shortcuts/** and make them executable from inside lutris, so that these people can enjoy the same "out of the box" experience as the steam-users do. 
You can take the Shortcut icons from **~/.PlayOnLinux/icones/32** (or ~/.PlayOnLinux/icones/full_size/) they have the same name as the shortcuts. 

Actually I think that would be enough integration to completely satisfy most of the users.

**Comment by strycore** [comment]
we have detection of PoL wine builds now. I'll probably add detection of wine prefixes when appropriate
