### ISSUE TITLE
Lutris switches right panel to a stopped game regardless of its previous state.

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2144]
How to reproduce:
1. Select a game and launch it
2. Unselect it (by selecting a different game or none at all)
3. Close the game without using Lutris client (for example, by exiting it through in-game menu) so that process manager picks up that the game has closed itself.

Expected behavior: Right panel keeps its current state (selected on a different game or just showing default menu)
Observed behavior: Right panel switches to the game that has just closed.

**Comment by isugimpy** [comment]
This is because of lutris/gui/lutriswindow.py:705.  When the game exits, we update the metadata, which fires on_game_updated, and the line in question triggers to set the game as selected in the view.  Removing that line is completely doable, but I wonder if it has any undesirable side effects.  For example, right now, when you add a new game, that game gets autoselected in the GUI because of this same event.

**Comment by NicolasAirault** [comment]
Hi,
It seems the lines that are updating the view and the selector is not really important. I try to remove, install, select another game when another is already launched without the lines, and there is any problem with it.
I think this if statement at lutris/gui/lutriswindow.py:729 is only here for updating the view when we install a game. Is it something that we really need ?

**Comment by strycore** [comment]
I've removed the game selection from the on_game_updated method. This isn't the responsibility of this method and if we do need to change the view selection in some cases, it should probably be done as a 2 step process.
