### ISSUE TITLE
[Feature Suggestion] Create Game / Launcher Entries as Subset of other Game Entry

### ISSUE THREAD

**Issue by tlneondo** [lutris/lutris#2193]
In the Absense of having built in support for every launcher under the sun, it would help if we could easily define new Game entries as subsets of another.

Say I install the Epic Games Launcher, because I want to play Outer Wilds. I can Either create a new prefix completely separately while using the EGS launcher to update my game, or try to put in per game settings into EGS's prefix.

This also goes with running GOG Galaxy in a prefix, so that you can get access to beta versions of games and sync your saves with the cloud, which I do with Witcher and Blood: Fresh Supply.

**Comment by djibux** [comment]
I second this.  I believe a game could be flagged a compatible with the launcher and installed in the same prefix.  If the game requires a specific configuration (winetrick or other), it should have its own prefix.

**Comment by appetrosyan** [comment]
I believe a good place to start would be 
`lutris/lutris/game.py`. 

The obvious first step is to allow the configuration of the runner to be cloned, and to point at the launcher (e.g. EGL or GOG). Because you're using Lutris to launch the launcher, and not the game directly this could fix bugs withThe API being non-extant (with Epic), but to still make use of a tweaked configuration. 

The only problem would be if the launcher requires a different config than the Game, and the launcher can't run with the Game Wine version.... Which is why I'd keep the stuff in experimental as experimental.

**Comment by strycore** [comment]
Current EGS integration will do this automatically, installing every game from the original launcher. Same with Origin and Ubisoft Connect.

We also have an upcoming PR for cloning a game, which is tracked in #3102
