### ISSUE TITLE
There needs a way to differenciate different versions of a game

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#220]
Even when filtering runners in the sidebar, a game can appear multiple times (with mess or mednafen). I also plan to add a platform filter which would help but what would be nice is overlaying a platform icon on the banner. This requires having the platform aspect implemented and icons for each platforms (consistent and good looking 32x32 icons)

**Comment by Xodetaetl** [comment]
Having the platform information is long overdue. We should have had it from the start, we won't be able to add it backwards automatically to installed games with multiplatform runner.

I'd put the platform icon in the title label. It will be more visible, it won't spoil our beautiful banners and it will surely be easier to code.

Hopefully we can find libre 32x32 icons for most platforms. :)

**Comment by strycore** [comment]
> we won't be able to add it backwards automatically to installed games with multiplatform runner.

Yes we can :) All the multiplatform runners have a 'machine' attribute in the game's config so based on that it's easy to extract the platform from that info.

**Comment by Xodetaetl** [comment]
Oh, that's full of correctness. :P

**Comment by cheater** [comment]
in the lutris launcher, i would like to be able to have a precedence of launchers from most favourite to least favourite, so that only games that are unique to that launcher are shown.

for example, let's say my precedence is like this, from most favourite to least favourite:

Steam, GOG, Amazon, Humble, Epic, Origin, Ubisoft

When I click on GOG on the left, I don't want to see games that I also have on Steam.
When I click on Amazon, I don't want to see games that I also have on either Steam or GOG.
Humble: don't show games I own on Steam, GOG, or Amazon.

etc etc

Have a filter in the hamburger menu that is called "Show only games you prefer to install with this launcher", and make it default on. If it's turned on, you can eg install a game on Amazon if you have it on Steam.

Make the precedence editable of course.

**Comment by strycore** [comment]
@cheater no gonna happen

**Comment by cheater** [comment]
Too bad, how come?

**Comment by strycore** [comment]
Because it's an awful idea.

**Comment by cheater** [comment]
... can you elaborate on this? what makes it so "awful"?

I'd like to be able to browse my games without seeing duplicates over and over.

**Comment by cheater** [comment]
Everything OK over there? Do you normally talk to people like this?

**Comment by strycore** [comment]
On Github, yes.

**Comment by cheater** [comment]
Take it from someone who's been programming for 30 years, Github or not, that's not the right way to talk to people, whether you've written 100% of the code in the repository or are just an onlooker ... just makes you look bad.

**Comment by danieljohnson2** [comment]
I can't speak for @strycore, but I will anyway.

What you describe is complex, and Lutris already has too much complexity here with its hide-this and hide-that and filtering and sidebar. People lose track of the state of the UI and don't know where their games gone. I've done changes to try to clarify this, but they only go so far.

Your scheme is worse. Users are going to struggle with a precedence system, for sure.

And it also seems a bit redundant with the "Favorites" view; that only works for installed games, but I think most of us play games more than we install them.

**Comment by cheater** [comment]
@danieljohnson2 that's a good point, thanks. My main concern here is to see games that otherwise get lost in the deluge of games I otherwise see on Steam anyways.

**Comment by strycore** [comment]
Don't use Lutris for Steam games, it's useless.

**Comment by strycore** [comment]
> ... just makes you look bad.

I don't care about looking bad, I just want Lutris to look good.

**Comment by cheater** [comment]
> I don't care about looking bad, I just want Lutris to look good.

That's a misunderstanding of what I meant. What I did mean was that you were being needlessly rude, and such behavior doubly doesn't have a place if you "want lutris to look good" - people in general easily get upset at projects if they have a bad interaction with maintainers, that word gets around, and you lose community goodwill. Your behavior and/or tantrums reflect on the project as a whole. You're grown up, you know this.

> Don't use Lutris for Steam games, it's useless.

Good point, I don't use it for Steam games, but here's the thing, eg if I go to Amazon games, 95% of the games they gave away are ones I have on steam anyways - my objective is to see the remaining 5%.

**Comment by strycore** [comment]
I do what is needed to keep the project going. I don't want a big and welcoming developer community, I want a small one. 
Lutris has a 15000 users Discord server, I don't interact with it except for the private dev chatroom that only has 10 people.
Several times, when I've felt overwhelmed by the number of requests on this Github, I've tried to distance myself by unsubscribing from new issues and not use it as much for project planning.
It turns out I still need to use the Lutris Github so I'd rather be harsh sometimes to limit the interactions on it.

I want Lutris to be Open Source, it's the only software development model I truly believe in.
It doesn't mean I'm interested in hearing the opinion of everyone regarding the software I'm making.

Anyway, since I'm no longer cooking lunch, I may elaborate a bit more.

* Lutris does not interfere with the 3rd party services views. The game list is pulled directly from respective APIs and we show exactly what is returned by the backend
* In order to have any kind of relationship between games from different services, we need to link their internal IDs in our backend. We only have Steam and GOG so far. Matching by name isn't an option.
* The goal of this ticket is to group duplicate games into a single game, not hide some games from users.

The feature you want will be possible once we have:

* Sync 3rd party libraries to the Lutris website
* Better automation for matching games of different services
* Revamped filtering system that allows exclusion filters

**Comment by cheater** [comment]
You can come up with about one million excuses for rude behavior, but none of them actually excuse it. You could have just said "I'm cooking right now, I'll tell you later" or just not said anything at all and got back to it after cooking/eating/etc. I don't know why it's necessary to explain to grown up people why being rude is not OK no matter how you rationalize it - but it's not. "I need to be rude to limit my time" is not an excuse - you are not any more precious than anyone else; get over yourself. It's not "optimization big brain" behavior, it's just simpleton behavior, and it's exactly why developers as a profession have a bad name and aren't being taken seriously.

If you want a small, productive community, let me tell you right away that by acting like this you will only attract sycophants. People with the skills necessary for this project will see this BS behavior and stay far away, because they don't want to have exactly this kind of conversation. You think you're filtering for dedicated people or whatever, but you're only filtering for people who don't know better. What you're doing here has exactly the opposite effect of what you say your objective is.

Take me for an example, I'm a guy who could easily contribute to Lutris, I've been using Python actively since the very beginning, etc etc. I'm going to stay away from this code like it's toxic waste simply because of your rationalization above there. You scare away a developer like me who's been doing this since before you were born and probably many others and then you get

> overwhelmed by the number of requests on this Github

👆 I hope the cause-effect relationship here connects for you.

I never suggested you have to be holding everyone's hand from zero. You don't have to teach every newbie who just wrote their first javascript to develop in this code base. That's far fetched and it's not what this is about. No one asked you for this extensive amount of support and educational effort. All that was pointed out was that you lacked on basic human decency there, which is an effortless thing. It was pointed out politely, then pointed out politely again, then pointed out politely again. You doubled and tripled down and when it was laid out bare to evade responsibility you said you can't do it because you perform this huge effort of being absolutely welcoming to everyone in a huge dev community - which is completely disconnected from what was being talked about. Maybe that comes from a position of expecting that everyone who interacts with you will just waste your time - which would say a lot.

And then you made an excuse about cooking dinner. 🙄

---

> > Do you normally talk to people like this?
> On Github, yes.

Just to sum this up: "on github" is not some sort of free-for-all to be crappy to random people. Remove this mindset from your head completely. It's some sort of cancer spreading through the open source software community that befalls otherwise perfectly fine projects. Sometimes developers just want to show off how crappy they can be to different users. You're not BOFH. Get over it.

**Comment by cheater** [comment]
Glad it wasn't such an "awful idea" after all

**Comment by strycore** [comment]
> Glad it wasn't such an "awful idea" after all

We didn't implement your idea.
