### ISSUE TITLE
feature request: Allow filtering search results for games that can be played without an internet connection

### ISSUE THREAD

**Issue by najamelan** [lutris/lutris#2222]
Currently there are some filters in the search that allow selecting free games, libre game engines and such.

It would be nice to be able to select only games that don't require internet to play...

Thanks alot for all the great work!

**Comment by tannisroot** [comment]
This is certainly a nice idea but here are some issues with it:
1) determining which games fit this "can be played offline" criteria will require human moderation and our mods are already overflowing with review tickets.
2) even if it would be possible to moderate this, our mods would have no way of knowing whether the report that this games works fine offline is correct or not, as we don't own every game that we have listed on Lutris.net
3) some single player games may gain the ability to be played offline after removal of DRM and the opposite can happen (as happened with Control).
Due to these, I'm closing this issue.

**Comment by strycore** [comment]
@tannisroot the future evolutions of the website will hopefully allow aspects like that to be self managed by the community. 
If we allow community managed tags, some "playable offline" tag would totally allow this kind of feature.
But this is not the right place to discuss that so thanks for closing it.
