### ISSUE TITLE
Discovered PCSX2 Runner Reason For Crashing/Not Working

### ISSUE THREAD

**Issue by ThisNekoGuy** [lutris/lutris#2285]
Hey,

A guy in the Discord server (danielsuarez369#6821) helped me troubleshoot the reason why the PCSX2 Runner doesn't work.

I'm making this report so that this can be repair so workarounds aren't necessary.

There's a missing dependency that can be installed with apt:
_sudo apt install libgtk2.0-0:i386_ 

This makes the Ru.ner actually work; however, the Runner ALSO has an issue where the GS Plugin (the video plugin) was never included with the emulator. Installing PCSX2 separately from Lutris to grab the missing plugin and placing it in the Lutris Runner's plugin folder fixes the last issue.

[PCSX2 PPA](https://launchpad.net/~gregory-hainaut/+archive/ubuntu/pcsx2.offical.ppa)

Also note: The emulator runs like a grandma without Gamemode activated.

Also, it would be appreciated if a Launch button for the emulator itself was implemented so the user can actually change settings as it isn't possible to do without running the emulator outside of Lutris, apparently.

**Comment by strycore** [comment]
I've made the necessary changes to the runtime to be able to run PCSX2. For the GS plugin, libOpenGL0.so needs to be installed and it's not something we can ship in the runtime since it's heavily dependent on the system.
PCSX2 being a 32bit only runner, we'll have to find a way to make this library install with lutris.
