### ISSUE TITLE
The DXVK install videos are unclear and unhelpful

### ISSUE THREAD

**Issue by nickgrier07** [lutris/lutris#2295]
I can't see a thing that is happing on those videos, you need to replace them with **WRITTEN INSTRUCTIONS**. 

That is all.

**Comment by Zeioth** [comment]
I'm not sure what videos you refer to, since you don't link them, but you can enable DXVK like:
![dxvk](https://user-images.githubusercontent.com/3357792/68085368-94d72300-fe40-11e9-9393-1a8170d316b5.png)

To access this menu: "right click in your game > Configure > Runner options"

Also, make sure you installed correctly your drivers and vulkan as described [here](https://github.com/lutris/lutris/wiki/How-to:-DXVK).
