### ISSUE TITLE
Lutris can't open because unsupported locale setting. ARCH

### ISSUE THREAD

**Issue by warriormaster12** [lutris/lutris#2341]
`lutris -d
Traceback (most recent call last):
  File "/usr/bin/lutris", line 27, in <module>
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
`

**Comment by tannisroot** [comment]
@warriormaster12 what's your Lutris version?

**Comment by warriormaster12** [comment]
Lutris version = 0.5.3 
Locale 
LANG=en_US.UTF-8
LC_TIME=en_FI.UTF-8

The problem began when updating to 0.5.3 
Temporary solution is LC_ALL=C lutris %U

**Comment by manuelVo** [comment]
Lutris (ore more accurately the unerlying C library) failed to recognize the locale configured by you which causes an error during startup. I created an PR (#2392) to use a fallback when this happens so lutris can still start (it basically does the same thing that you have done by hand to workaround the issue).

I'd like to note that I believe the root cause of this bug is the locale `en_FI.UTF-8` that you configured. According to my research `en_FI` doesn't exist as a locale (there aren't very many results when searching for `en_FI` and those that appear are very old and most of them claim that `en_FI` is not a thing as well). `locale-gen` and the gtk toolkit don't accept `en_FI` either on my system. If my assumptions are true and `en_FI` doesn't exist other software on your system will probably malfunction (or at least complain about this in the logs) as well and I'd suggest you refer back to the documentation of your distribution to see what to correct locale setting for your region is.

**Comment by ChaosD** [comment]
I stumbled upon this recently after updating manjaro (using german layout/format and english system language). This is the result of mainly [this](https://forum.manjaro.org/t/default-locale-not-set-properly/64163/28) and [this](https://forum.manjaro.org/t/a-question-about-locales/105584/5) thread. Are you using KDE? It seems like Plasma can interfere with common solution approaches.

Not sure how viable my solution is but this solved it for me:
- Make sure you have both languages installed in the "Languages" settings:
![image](https://user-images.githubusercontent.com/331779/66732569-c7eb4f80-ee5c-11e9-9eec-1ad4a154065e.png)

- run `sudo locale-gen`
- check if you got a mixed locale like `en_FI`
- if so, delete/rename `~/.config/plasma-locale-settings.sh` and `~/.config/plasma-localerc` ( **danger zone, not sure if this messes up things later!** )
- verify all language related system settings
- reboot
