### ISSUE TITLE
Lutris in-game overlay

### ISSUE THREAD

**Issue by PopeRigby** [lutris/lutris#2429]
To have an overlay in a non-Steam (or another launcher with an overlay) game, you have to add every single game as a shortcut to get the overlay. This makes it frustrating for people who want an overlay in every game, but don't want to fiddle with another launcher's overlay. So a built-in Lutris overlay with the system time and a web browser would be useful.

**Comment by LeXofLeviafan** [comment]
…Can't you achieve that by simply switching the workspace? It's as simple as pressing Ctrl+F4 for me (the fourth one is where I keep my browser windows).

**Comment by PopeRigby** [comment]
I guess you could do that, but there are benefits from doing it this way. It can act as a frontend for using Steam or Discord chat. It also allows you to still see the game in the background so you can close the overlay if you're about to get killed in-game.

**Comment by LeXofLeviafan** [comment]
That may be so (although I would really either pause the game or wait until it's safe to be AFK rather than chat while trying to watch out for the enemies), but it would be rather hard to implement. The reason being, the "overlay" that Steam provides is technically part of the game itself (injected basically by hacking into the game renderer) and making a similar feature would require a lot of effort in areas that have absolutely nothing to do with the rest of functionality (as most of Lutris is basically a fairly regular desktop app).
I suppose one could try to make a separate project just for that particular purpose (calling it something like "open game overlay wrapper" or whatever), and then Lutris could support it as a feature, like it supports DXVK :-D

**Comment by Zeioth** [comment]
This feature is technically impossible for us. Steam overlay is a part of Steam.

**Comment by PopeRigby** [comment]
@Zeioth what do you mean by "Steam overlay is a part of Steam"?

**Comment by LeXofLeviafan** [comment]
@PopeRigby See my explanation above

**Comment by basxto** [comment]
OpenGamepadUI does to allow to do some configurations with a controller. And controller navigation is what benefits from this most, especially when playing remotely through something like moonlight+sunshine.

Beneficial features that could be provided through such an overlay are: a button to kill the application, see current time, see how long current session is running, change controller settings, turning gamemode/mangohud on/off

OGUI shows wifi network and bluetooth devices in it’s overlay, which is nice because that can be relevant while playing a game, but that’s too out of scope for lutris.

**Comment by strycore** [comment]
Thanks for pointing out OpenGamepadUI, this exactly what I want for a fullscreen interface. It's written in Godot4 and already has Lutris support.
