### ISSUE TITLE
libretro: option to use system cores

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#2444]
The ones located in `~/.config/retroarch/cores`
As workaround i use `ln -sv "$HOME/.config/retroarch/cores" "$HOME/.local/share/lutris/runners/retroarch/cores"`

**Comment by malefice** [comment]
While I do not have any background in GTK programming, I would like to take a shot at this, and hopefully I can learn a lot from this. Anyway, I have taken a look at the [source code](https://github.com/lutris/lutris/blob/master/lutris/runners/libretro.py) for the libretro runner.

Currently, it is [coded](https://github.com/lutris/lutris/blob/ff30fc25b6a8cc515063c7ec027a8259a740afbd/lutris/runners/libretro.py#L110) to search for cores inside `$USER_DATA_DIR/lutris/runners/retroarch/cores` wherever the `$USER_DATA_DIR` is for the specific platform.  I am thinking of implementing this as a `directory_chooser` under the `runner_options`. Will this be adequate?

**Comment by malefice** [comment]
@strycore I already have something for this, and I implemented it as a `directory_chooser`. It works great, but there is one problem. Retroarch (at least on my system-installed one) does not seem to handle tilde expansion well as it fails when called by lutris or manually via CLI.

```bash
# This craps out
/usr/bin/retroarch --config=/home/user/.local/share/lutris/runners/retroarch/retroarch.cfg --libretro=~/.config/retroarch/cores/mednafen_psx_hw_libretro.so psxgame.iso

# This works perfectly
/usr/bin/retroarch --config=/home/user/.local/share/lutris/runners/retroarch/retroarch.cfg --libretro=/home/user/.config/retroarch/cores/mednafen_psx_hw_libretro.so psxgame.iso
```

From our end we can force tilde expansion even if Retroarch will not bother to fix this, but the current behavior of the directory chooser does not perform tilde expansion, while the file chooser does this  expansion even as you type. Is there a particular reason why directory choosers do not perform tilde expansion?

**Comment by lukasfink1** [comment]
> EDIT: Tilde expansion works with `-L` instead of `--libretro` (long form), so it really does look like a parsing issue in Retroarch itself.

Tilde expansion is normally done by the shell. If you prepend something before the tilde, the shell won’t perform the expansion.
I guess you’re probably doing `-L ~/path` which is fine, but `--libretro=~/path`, in which case it won’t work. Try `--libretro ~/path` and it should work. You can also test those examples with `echo` to see, what the shell creates.

I skimmed the [lutris/runners/libretro.py](https://github.com/lutris/lutris/blob/master/lutris/runners/libretro.py) and it seems as though it’s already extracting the correct paths for everything from the retroarch.cfg, which is already configurable and you can of course choose `.config/retroarch/retroarch.cfg` for it. The problem is that this is done in the [`prelaunch`](https://github.com/lutris/lutris/blob/50336d1cf505a234906bf2896e85a38f90bb1d6e/lutris/runners/libretro.py#L160) function, while the list of cores will be already constructed on module load and uses the static `runners/retroarch/cores` path.

It should work, when everything in libretro.py uses extracted paths. This would be the most elegant solution, as you only need to specify the retroarch.cfg and it takes everything else from that. Prevents the redundancy of specifying all paths once in the retroarch.cfg and then again in the Lutris configuration.

**Comment by malefice** [comment]
@lukasfink1 yeah I was aware that the shell handles tilde expansion. My mistake was my false memories that other programs customarily support tilde expansion anyway in situations like this. How wrong I was when I tried it using other programs. Anyway, I was also aware that doing `--libretro ~/path` or `-L ~/path` will work, but it became a uniformity thing for me.

The commands created (at least in PCSX2 and libretro runners) all use the `--long-name=value` style wherever applicable, and while I can just use `os.path.expanduser` to handle the tildes, at the time I made my previous post, I wanted to keep the config parsing part as simple and as uniform as possible. Since then, I looked into the other runners, and some of them already use  `os.path.expanduser`, I will just go ahead with this route.

As for your suggestion of parsing the specified retroarch config file, thank you! It is only recently that I started using retroarch, so I was not aware that the core location is configurable. I will try to come up with something using the approach you suggested.

**Comment by Magicrafter13** [comment]
Came here to report a bug that lutris doesn't let me select a core, only to find out it's not a bug, it's just not designed to handle retroarch already being installed to the system ._.

Thanks for the symlink suggestion though, I hope that works!

**Comment by strycore** [comment]
Lutris now detects and uses cores in ~/.config/retroarch/cores
