### ISSUE TITLE
manjaro xfce 18.2 : browse game folder launches catfish

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2456]
Hello,
on the official Manjaro xfce 18.2 Linux distribution, when you use "browse files" Lutris feature, it opens catfish instead of file explorer (Thunar).
Is it a Lutris or a Manjaro bug?
When you click on "browse files", what is the Lutris called function?

**Comment by tannisroot** [comment]
> when you use "browse" Lutris feature, it opens catfish instead of file explorer (Thunar).
which "Browse" feature are you referring to?

**Comment by legluondunet** [comment]
this one:

![Capture-20191115112113-1920x1080](https://user-images.githubusercontent.com/325405/68936128-2c6e3700-079a-11ea-989c-668c4379780d.png)

**Comment by legluondunet** [comment]
to reproduce this bug:
install Manjaro 18.2 XFCE official release (in QEMU or VirtualBOX...)
install wine, lutris...
install a game in Lutris, right click on the game and choose "browse files".
I can reproduce this bug at each new install (I regurlarly install virtually different Linux distributions to test installers I work on).

**Comment by strycore** [comment]
We just call Gtk.show_uri (see: https://github.com/lutris/lutris/blob/master/lutris/gui/widgets/utils.py#L46 ) so that's an issue with your config and not the Lutris client. Find the place where catfish is used as a default file browser and switch it to Thunar.

**Comment by Rencer** [comment]
> We just call Gtk.show_uri (see: https://github.com/lutris/lutris/blob/master/lutris/gui/widgets/utils.py#L46 ) so that's an issue with your config and not the Lutris client. Find the place where catfish is used as a default file browser and switch it to Thunar.

I had this same problem under Manjaro XFCE, too. I think I figured out what might be the problem, and like you said, it is not a Lutris bug.

For me, not catfish, but a text editor I use opens up, but I never set the text editor to open folders.
It must be a problem in Manjaro and how it is doing it's things with MIME types. I had a lot of problmes that files aren't open wih what I set, and sometimes when I change ONE file type to be opened with a  program, for some unknown reason lot of completely different file-types starts to open up with that application; file-types that I didn't changed. I think it is definetly a bug in Manjaro, or XFCE, or  whatever is responsible for it.
So I looked into with Manjaro's default  "MIME Type Editor" and I saw that "inode/directory" is set to the text editor I use, but I never changed that. So I changed it back to the "default". Turned out that the default is Catfish!  Why that is the default is a mystery. Something really messed up in Manjaro and how it hanles MIME Types. 
I changed it to Thunar and now it works.
So you have to change the "inode/directory" MIME-type from Catfish to Thunar.
