### ISSUE TITLE
Soldat Installer

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#252]
[Soldat](http://soldat.pl/en/) [1.7.0](http://soldat.pl/en/post/soldat-1_7-release) was released. Had an attempt at an installer:

https://lutris.net/games/soldat/

During installation, it crashes Lutris. Know what's wrong with it?

**Comment by Xodetaetl** [comment]
No crash here but it doesn't really install because your installer has many issues:
- Relative paths in tasks are not implemented, use absolute for `task: executable`
- Missing `game: prefix: $GAMEDIR`
- Mistake in the exe path (`driive_c`)
Minor things:
- create_prefix is not necessary here, all Wine tasks include the creation of the prefix if it doesn't exist.
- `dst: $GAMEDIR` is not necessary in the extract command, it's the default.
- chmodx on exe files is not necessary, the executable is `wine`, not the .exe
- Extract temporary install stuff (the setup exe) in $CACHE, so it gets cleaned up after install.

**Comment by Xodetaetl** [comment]
PS: the game's banner isn't cropped, and please submit games from user side so we get notified and can double-check what's posted. I try to double check stycore's submissions too, so don't worry, no special treatment here. ;)

**Comment by RobLoach** [comment]
Done.

**Comment by strycore** [comment]
Nice!
Just a note regarding banners. If you upload banners from the lutris admin, make sure you crop them at a 184x69 ratio otherwise it will be all messed up in the client.

**Comment by RobLoach** [comment]
Messing with the client is half the fun though:
https://twitter.com/LutrisGaming/status/751840832823529472

**Comment by strycore** [comment]
This is giving me ideas for the next April 1st :p
