### ISSUE TITLE
Problem with user directories when sandboxing is disabled

### ISSUE THREAD

**Issue by petr666** [lutris/lutris#2598]
Hi, i have strange problem in recent version. I have disabled wineprefix sandboxing, so my user directories were configured as symlinks. But in recent version programs (or even wine config) do not start with error:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 676, in run_winecfg
    self.prelaunch()
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 778, in prelaunch
    self.sandbox(prefix_manager)
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 926, in sandbox
    wine_prefix.desktop_integration(restore=True)
  File "/usr/lib/python3.7/site-packages/lutris/util/wine/prefix.py", line 132, in desktop_integration
    os.rename(old_path, path)
NotADirectoryError: [Errno 20] není adresářem: '/home/petr/.local/share/lutris/runners/winegames/drive_c/users/petr/Plocha.winecfg' -> '/home/petr/.local/share/lutris/runners/winegames/drive_c/users/petr/Plocha'

which is true, because "Plocha" is symlink to proper Desktop directory. When i delete "Plocha.winecfg", same error moves to next user directory "Mé dokumenty" (Documents). When i delete all "winecfg" files, all symlinks to existing user directories are replaced by empty directories. I.e. i am not able to run programs linked to standard user directories despite sandboxing is disabled.

**Comment by zeparu** [comment]
looks like this has broken something on my end, updated to new lutris today with manjaro, gonna copy paste what i wrote on discord

hey im having a really weird issue with wine and FFXIV right now
it seems like maybe my wine folder links got broken? when i delete them in the prefix, and i start winecfg, it will create an empty documents folder
when i try to start FFXIV, it will put the My Games folder in there, but the launcher instantly closes
when i try to start it again, for some reason it will move the old documents folder to my documents.winecfg, and create a new one, and fill it with My Games again
and then it will halt and not even start wine properly, because it cant move the my documents folder to my documents.winecfg again, because it already exists
if i just start ffxivboot from the prefix with normal system wine, without lutris, it will open properly

at no point during starting the game with or without old folders, no symlinks are created and the game wont start properly without the config files within the documents folder 
copy pasting the config files into that folder also wont do anything
