### ISSUE TITLE
Wine Steam Games on external hard drive permanently appear uninstalled when running Lutris with the drive disconnected

### ISSUE THREAD

**Issue by Dominator86** [lutris/lutris#264]
I think games installed in an unavailable location should only temporarily appear uninstalled until the location is available again.

**Comment by Xodetaetl** [comment]
Indeed

**Comment by strycore** [comment]
The way of dealing with uninstalled games is far too brutal. Because games that aren't available are automatically uninstalled after a nanosecond, it is currently impossible to manually add steam games.
The moment a game becomes unavailable, all its associated config is lost forever.

Fixing this is a very priority for the next release.

**Comment by strycore** [comment]
This should now be fixed in the master branch, can anyone confirm?

**Comment by strycore** [comment]
Well, it's the only bug left in the 0.3.7.6 milestone, I'm removing the milestone so we can release the new version.
