### ISSUE TITLE
Sort by play time incorrect

### ISSUE THREAD

**Issue by Danacus** [lutris/lutris#2659]
The sorting by play time does not behave correctly, it will sort according to each digit separately, instead of sorting the entire number. (probably sorting on text and not on integer values)

For example:
- What happens: 3 hours > 20 hours > 100 hours, because 3 > 2 > 1
- What I expect: 100 hours > 20 hours > 3 hours

I'm currently using lutris version 0.5.4.

**Comment by tannisroot** [comment]
Lol

**Comment by connectety** [comment]
This might only affect hours, because I could not confirm this for minutes.

E.g. Battlenet with 55 mins is before SuperTuxKart with 9 mins
But this just happend to me with hours.
E.g Epic-Games-Store with 30 hrs and 44 mins is before overwatch with 100 hrs and 51 minutes.

I might take a look at it later.

**Comment by connectety** [comment]
This indeed caused by the playtime column beeing a string.
https://github.com/lutris/lutris/blob/97c17179080d30d21f7fd74422e174dda6e38540/lutris/gui/views/store.py#L129

It should be a float, not an integer.
I have not created a PR yet, because the playtime gets handled as a string throughout major parts of the project and i dont have a deep enough understanding to fix this.

But for starters playtime should be a float in the PGA too.
https://github.com/lutris/lutris/blob/97c17179080d30d21f7fd74422e174dda6e38540/lutris/pga.py#L37

**Comment by Danacus** [comment]
As an alternative, it might be easier to keep it as a string, but use [natural sorting](https://en.wikipedia.org/wiki/Natural_sort_order) instead. But I don't really know how lutris works.

**Comment by connectety** [comment]
1. I don't think SQLite supports natural sorting.

2. Another easy approach would be to cast the string to a float the line below. 
https://github.com/lutris/lutris/blob/2f1e10badd49a27cb756ec59f3f7b4fb637624d2/lutris/gui/views/pga_game.py#L118
But we would still store a float in a string, which just isn't best practice. The reasons I found against doing this (**not fact-checked**): might use more disk space and might be more inaccurate.

3. This was easier to fix as I thought. I thought lutris would do converting the DB types itself. This would mean I would have had to fix the serialization and deserialization. Maybe there would have been some more of this stuff when creating a new game or other cases. Instead, lutris gets the type correctly from the DB, but the type in the DB has to be changed.
