### ISSUE TITLE
Steam game overlay broken with lutris shortcut 

### ISSUE THREAD

**Issue by buxel** [lutris/lutris#2719]
I'm sorry if this is considered rude, but i also posted the issue to [ValveSoftware/steam-for-linux ](https://github.com/ValveSoftware/steam-for-linux/issues/7012) because it's hard for me to tell what exactly causes the problem.

#### Your system information

* Steam client version (build number or date): Mar 26 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I added a non-steam game (lutris shortcut) and it starts as expected. I **expected** the overlay to open when pressing shift-tab. The game is "Totally reliable delivery service", running unity engine `2018.4.14f1` trough wine version `lutris-5.5-2`.
What **did happen**, is that some kind of invisible overlay opened, which prevented any further input. The game/music kept running.

First, i was investigating, how lutris could interfere but after trying many suggestions from reddit/github/forums in vain, i took a closer look at steam itself. 

It looks like it fails to load **both**, 32bit and 64bit, versions of `gameoverlayrenderer.so`. Full log [here](https://gist.github.com/buxel/7b0ffab12c9cf9283f563067e6c9771c).
```
ERROR: ld.so: object '/home/buxel/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/buxel/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```
The logs also tell something about losing focus but I'm not sure what to make of that.

I understand that depending on the game one or the other might fail. **But could having both fail result in the issue I'm having?**. I assume, i accidently created a weird environment for steam, which breaks the overlay but I'm running out of clues where to look. `gameoverlayrenderer.so` is probably just the first lead.

I installed `steam-native` in order to get the gamepad working. The overlay didn't work before that either.

#### Steps for reproducing this issue:
1. Add a game (e.g. 0-AD) to Lutris
2. Create a desktop shortcut
3. Add the shortcut to steam
4. Start the game
5. Open the overlay using shift-tab

**Comment by buxel** [comment]
Additional lutris log [here](https://gist.github.com/buxel/7f42f43a224178da951a8f6bfe3e6505).

This caught my interst, but might be unrelated
```
Exception ignored in: <function InputDevice.__del__ at 0x7fcb527e09d0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3.8/site-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3.8/site-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-6'.
```

**Comment by strycore** [comment]
I see 2 errors related to input (the 1st you mentioned and another related to an invalid line in the Windows registry, by what looks like a weird controller name). By any chance, have you tried launching the game with no joypad plugged in?

Can you also tried with more than 1 lutris game so we can determine if this applicable to all games?

**Comment by buxel** [comment]
Some more tests:

- I included a linux native game to make sure it's not some wine runner issue.
- For all tested games i never got the notification to "Access the steam community" by pressing the home button.

**Totally Relaible Delivery Service** ([log](https://gist.github.com/buxel/296715d01fc181cc10c185cdfc421ae7))
- without controller 
- game started  
- overlay didn't work 

**Minit** ([log](https://gist.github.com/buxel/87b6ba9b7c095b58f6b2990786e2d82f))
- with controller
- starts fine with ~40-60 FPS in menu
- when i press the home button to open the overlay, FPS drop to ~10. Overlay still doesn't open.

**0-AD** -linux native- ([log](https://gist.github.com/buxel/c66283ff44334e8d91b7c26e2f611741))
- with controller
- when added directly as steam shortcut, the overlay works. 
- with the shortcut pointing to lutris, the overlay stops working

**Comment by buxel** [comment]
It looks like GameHub is also having this problem. I'm not using LSI, tough
https://github.com/tkashkin/GameHub/issues/286

**Comment by 8BitCerberus** [comment]
Adding my +1 to this. Also on Manjaro. I have another computer on Solus that I will test to see if it's a Manjaro problem or Lutris/Steam problem. I'm having problems with the repo Steam not working as an in-home streaming client, but flatpak Steam works, so there may be some oddity going on with the Manjaro repo Steam. The Solus system has no problem with streaming via it's native client, for reference.

Previously I had been on Ubuntu on this machine and I had no issue with the overlay or streaming from another computer, etc. But it's been several months since then (6+), I've been on Windows for VR but a recent update got me stuck in a boot loop so I nuked the Windows partition and decided to try Manjaro for more up-to-date packages.

**Comment by buxel** [comment]
@crakkhead what distro are you using? 
i just double checked, if gamemode is the culprit on my system and it does not make any difference.

I added "0 A.D." to steam directly -> overlay works
Trough Lutris -> overlay broken

gamemode was disabled for the game and globally. Could it be that the setting is not working and gamemode gets loaded anyways?

**Comment by crakkhead** [comment]
@buxel I'm using Manjaro, same as you. Lutris is at version 0.5.6. For me the Steam overlay works as long as gamemode isn't enabled in the system options in Lutris. So it seems you're experiencing a different issue.

**Comment by 8BitCerberus** [comment]
I've since switched to Solus because my other Solus computer was not having any problem with the overlay. But I am probably going to switch back to Manjaro at some point once this gets figured out. However now on Solus with my primary machine I had the same issue initially. 

After a couple of days digging through forums and trying different things and getting real frustrated that it might be some weird bug with my 5700XT, and/or mesa, because my other machine is a GTX 780 and using the proprietary drivers. Then it occurred to me that I haven't yet tried any native Steam games yet, either Proton and Linux native. Turns out, they too were not getting the overlay.

I don't know what made me think of it, but when you install Steam on Solus it automatically installs their "Linux Steam Integration" tool as well. Reading up on it a bit, there was some information that enabling the native runtime can occasionally lead to graphic glitches or broken games, particularly for Proton (and I assume by extension, Wine), so I had turned it off reflexively. I turned it back on, and tested the games, and the overlay is now working perfectly. Native Linux, Proton, and Lutris/Wine added as non-Steam games.

So I wonder, if on Manjaro if Steam is using it's own runtime (as it would be on Solus with native runtime disabled), as I understand it Steam is using some version of a library that most distros don't support. If you install LSI and make sure native library is enabled (or run `$ LD_PRELOAD=/usr/lib32/libudev.so.1 STEAM_RUNTIME=0 steam`) and see if the overlay is working on Manjaro.

**Comment by Merrit** [comment]
I seem to be having the same issue (also Manjaro). I have tried:

- Both Steam runtime & native
- Launching with no controller plugged in
- Disabling gamemode in Lutris settings (per game and for all lutris), confirmed gamemode not running with game
- `LD_PRELOAD=/usr/lib32/libudev.so.1 STEAM_RUNTIME=0 steam`

Still no overlay available through Lutris links. Steam games (proton) and native linux games as a non-steam link get overlay as expected.

**Comment by strycore** [comment]
this is happening because the shortcut launches lutris which then launches the game. This makes Steam lose track of the process.

If you create a shell script of the game with `lutris -b path_to_script.sh lutris:game` and create a shortcut of that, then Steam is able to keep track of the process.

Maybe lutris should be only dealing with executing shell scripts that wrap the command. This would solve this issue and likely a few others too.

**Comment by Merrit** [comment]
> If you create a shell script of the game

@strycore Can you explain further what you mean here? I created a script to launch the game the way the desktop launcher would, eg `env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/86` and this doesn't seem to make a difference. I feel like you are suggesting something different.

**Comment by strycore** [comment]
@Merrit yes, this is different from what i was explaining.

`lutris:rungameid` will launch Lutris then tell it to launch the game. 
The other option is to use the -b option to generate a bash script that will run the game entirely without Lutris. 
This means that some other game client such as Steam will be able to monitor the game process but on the other hand, the game is no longer managed by Lutris (the play time doesn't get recorded for example)

**Comment by Merrit** [comment]
@strycore I see now! I should have checked what the `-b` flag did. Thank you for explaining further!

Launching this way does let Steam continue to track the game (whereas before it immediately thought it had exited) - unfortunately there is still no overlay, even though overlay works fine on actual Steam games.

**Comment by strycore** [comment]
It *should* be fairly easy to debug with the bash script. 
1st confirm you have the overlay on something not coming from Lutris. Then it's a matter of disabling parts of the lutris runtime until the faulty library is found (by editing the value of LD_LIBRARY_PATH in the bash script and moving libraries out of the runtime folder)

**Comment by Merrit** [comment]
I've managed to isolate the apparent issue thanks to the suggestion from @strycore .

In the generated bash script if I comment out this line:

```
export LD_PRELOAD="/usr/lib/libgamemodeauto.so"
```

The overlay works as expected. I have this environment variable set in Lutris globally, so I presume I must've done so at some point.

In Lutris I've tried:

- Removing this variable
- Changing to the current suggested variable for gamemode: `$LD_PRELOAD:/usr/\$LIB/libgamemodeauto.so.0`
- Disabling the toggle for gamemode

None of these has any effect when running the shortcut through Lutris directly, it still only works from the bash script with this line removed.

**Comment by strycore** [comment]
This confirms that there are issues with lutris + gamemode + steam as I mentioned here: https://github.com/lutris/lutris/issues/2086#issuecomment-1571310973 
I'm surprised that disabling gamemode in Lutris had no effect, this worked on my end.

**Comment by strycore** [comment]
The gamescope issue was on something entirely different. Here, I tested with both Gamemode enabled and disabled and the Steam overlay was showing correctly.

A Steam update must have resolved the issue.
