### ISSUE TITLE
Spam message: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

### ISSUE THREAD

**Issue by Steinhagen** [lutris/lutris#2760]
**Describe the bug**
The following Gtk-CRITICAL message is spammed for each runner when opening the 'Manage runners' window:
`Gtk-CRITICAL **: 16:57:04.200: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
`

**Expected behavior**
When opening the window, you shouldn't receive any debug error messages.

**Current behavior**
The reason why this occurs is because the 'configure_runner' GtkButton (from _lutris/share/lutris/ui/runner-entry.ui: runner_entry->runner_label->configure_runner_ has the Common property (under Widget flags) **'Has default' enabled** and **'Can default' disabled**! 

**Steps to reproduce**
1. Open Lutris from the command line.
2. Open the 'Manage runners' window.

**Comment by xordspar0** [comment]
Here is the documentation for [gtk_widget_grab_default()](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-grab-default), including the meaning of "default" in this context:

> Causes widget to become the default widget. widget must be able to be a default widget; typically you would ensure this yourself by calling gtk_widget_set_can_default() with a TRUE value. The default widget is activated when the user presses Enter in a window. Default widgets must be activatable, that is, gtk_widget_activate() should affect them. Note that GtkEntry widgets require the “activates-default” property set to TRUE before they activate the default widget when Enter is pressed and the GtkEntry is focused.

Because all of the widgets have "can default" set to false, none of them are becoming the default. Therefore, nothing happens when you press enter in the window. I think this is the correct behavior.

> Causes widget to become *the* default widget.

Doesn't that mean there can only be one default widget per window? Anyway, I think we should clean up the error messages by removing the default property from all of these buttons.

**Comment by xordspar0** [comment]
Actually, after testing I see that setting has_default to False in runner-entry.ui stops the assertion failures, but it also prevents you from being able to press enter to press a button after selecting it by pressing tab.

**Comment by strycore** [comment]
How you found the cause of this issue remains some kind of dark wizardry to me.

**Comment by xordspar0** [comment]
Me too. :smile: [I found out](https://developer.gnome.org/glib/unstable/glib-Warnings-and-Assertions.html#g-return-if-fail) that you can pause the debugger on assertion failures like this:

```
G_DEBUG=fatal-warnings gdb --args python3 bin/lutris
```

That gives a long and complicated stack trace that spans Lutris, GTK, and Glib code. It points to the assertion failing inside the GtkBuilder `add_from_file()` function, but it doesn't help me know where in the UI file the problem was. What's your secret, @Steinhagen?
