### ISSUE TITLE
Feature Request: Request for Integration of Chiaki as Runner for PS4 Remote Play

### ISSUE THREAD

**Issue by iwoojoo** [lutris/lutris#2771]
This is a request for integration of Chiaki(a Open Source Implementation of PS4 Remote Play)
From my personal Expirience it the project is working well in allowing one to use their PS4 over the local Network to play games on it. It does require some steps in setting it up but once your connected to your PS4 it "just works"

Github Page:
https://github.com/thestr4ng3r/chiaki

**Comment by strycore** [comment]
I don't think this would work as a runner because there doesn't seem to be a way to control the PS4 from this tool, it's more of a remoting solution (maybe I missed something though).

Without the ability to manage the games themselves, it can't qualify  as a runner. The best course of action is to install Chiaki via the Lutris installer: https://lutris.net/games/chiaki/
