### ISSUE TITLE
Setting default Wine version to Proton error

### ISSUE THREAD

**Issue by RickAndTired** [lutris/lutris#2792]
**Describe the bug**

Setting the default Wine version to Proton gives an error when you select an empty directory for a prefix.

If you select a lutris-wine build in a per game setting it is still broken.

If the Prefix directory has any file in it - then it works as normal

**Expected behavior**

Game starts

**Current behavior**

Error pop up
"Invalid Wine prefix path /path/to/custom/prefix, make sure to create the prefix before saving to a registry"

**Steps to reproduce**

- Wine Configure
- Set Wine Version to Proton
- Save
- Add a new game
- Wine prefix - select an empty directory
- Select Wine version: lutris-5.6-2
- Try to run game

**Lutris debugging output**

[lutris-proton-error.txt](https://github.com/lutris/lutris/files/4526468/lutris-proton-error.txt)

**System information**

File is a .json - I added the .txt because GitHub doesn't support .json
[lutris-issue-report.json.txt](https://github.com/lutris/lutris/files/4526465/lutris-issue-report.json.txt)

**Comment by xordspar0** [comment]
I can confirm this. When 1) Lutris's default Wine version is Proton, and 2) the Wine prefix of a game is an empty directory, the prefix directory will be *deleted* prior to the game starting, regardless of the version of Wine the game runs with.

**Comment by xordspar0** [comment]
The problem is in create_prefix().

https://github.com/lutris/lutris/blob/097a013c3339121afde72fb8953d869c18e1531e/lutris/runners/commands/wine.py#L105-L123

On line 108, Lutris intentionally deletes the empty directory, expecting to create it again when Wine is called.

On line 117, Lutris fails to find a wineboot binary and bails out with this error:

```
No wineboot executable found in /home/rick/.steam/steam/steamapps/common/Proton 5.0/dist/bin/wine, your wine installation is most likely broken
```

The problem is that the Proton directory structure is pretty different than normal Wine. Pre-5.0 versions of wine had a dist/ directory with binaries like `wine` and `wineserver`. But there is no `wineboot` script anywere in these versions of Proton. In Proton 5.0, the directory structure has changed even more. Now all of the files are in a single flat directory. The dist/ tree is now a single tar file.

Proton 5.0 directory structure:

```
Proton 5.0/
├── filelock.py
├── LICENSE
├── LICENSE.OFL
├── proton
├── proton_3.7_tracked_files
├── proton_dist.tar
├── toolmanifest.vdf
├── user_settings.sample.py
└── version
```

I was hoping to at least write a failing test for a simple corner case that wasn't handled, but this is a little more complicated than that. I don't know what the best way to solve this is.

**Comment by xordspar0** [comment]
Also, because of the restructuring in Proton 5.0, I don't think Lutris is capable of detecting it as a Wine runtime that you can use. @RickAndTired, you must have added Proton 5.0 by choosing a custom executable, right? In your logs, the Wine path is the `wine` binary, and Lutris tries to find wineboot by looking in `wine/wineboot`, but `wine` isn't even a directory. :smile: 

That's another problem that we'll need to fix.

**Comment by RickAndTired** [comment]
@xordspar0 I did not choose Proton 5.0 as a custom executable. Proton 5.0 is in the drop down, I didn't do anything extra to get it there.

**Comment by xordspar0** [comment]
Ok, good to know. My Lutris doesn't detect Proton 5.0. I'm not sure what's different.

**Comment by Meister1593** [comment]
Seems like this was issue for me too, look at bottom of the #3123

**Comment by strycore** [comment]
Proton is now removed from the available wine versions
