### ISSUE TITLE
EGS: Just Cause 4 terminates with "Make sure EGS is running"

### ISSUE THREAD

**Issue by Galcian79** [lutris/lutris#2799]
I'm trying to run Just Cause 4 (EGS) from the .exe folder but it seems the DRM prevents that, even if i keep the store client as a background process. It seems the only workaround would be running it inside the client, but obviously i cannot do that because changing the prefix setup would screw up my EGS installation. Don't know if there is a better way to run DRM games.

**Comment by buxel** [comment]
You could try adding `-EpicPortal` as launch arguments for your game. This helped in the past but I'm not sure if it will for JC4. Not sure, if their "DRM" is still that weak, tough :wink: 
Another approach could be enable logging in EGS check which launch arguments are used when you start the game trough EGS.

**Comment by Galcian79** [comment]
> You could try adding `-EpicPortal` as launch arguments for your game. This helped in the past but I'm not sure if it will for JC4. Not sure, if their "DRM" is still that weak, tough wink
> Another approach could be enable logging in EGS check which launch arguments are used when you start the game trough EGS.

Hi @buxel and thank you for your answer. 
Unfortunately it seems passing `-EpicPortal` argument doesn't work for any game in my library. Can you confirm it still works?

**Comment by buxel** [comment]
I only had to use it once for subnautica. Games that I recently tried starting directly: Minit, Into the Breach and Hob.They might have improved their DRM for the "bigger" titles 😕
-------- Ursprüngliche Nachricht --------Von: Galcian79 <notifications@github.com> Datum: 26.04.20  22:13  (GMT+01:00) An: lutris/lutris <lutris@noreply.github.com> Cc: Chris Na <christoph.nachreiner@gmail.com>, Mention <mention@noreply.github.com> Betreff: Re: [lutris/lutris] EGS: Just Cause 4 terminates with "Make sure EGS is running" (#2799) 

You could try adding -EpicPortal as launch arguments for your game. This helped in the past but I'm not sure if it will for JC4. Not sure, if their "DRM" is still that weak, tough wink
Another approach could be enable logging in EGS check which launch arguments are used when you start the game trough EGS.

Hi @buxel and thank you for your answer.
Unfortunately it seems passing -EpicPortal argument doesn't work for any game in my library. Can you confirm it still works?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lutris/lutris/issues/2799#issuecomment-619618275",
"url": "https://github.com/lutris/lutris/issues/2799#issuecomment-619618275",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by derrod** [comment]
[Thought I'd chime in since I've encountered this while working on [my EGS replacement project](https://github.com/derrod/legendary)]

Some EGS games (mostly using Denuvo DRM) require something called an "Ownership Token". This is used to verify you own the game (as the name implies). On my Windows machine this was only required once and afterwards the game launched without it, not sure if that is also the case when using WINE. Also note that Just Cause 4 will require online authentication anyway at first before you can play the game in offline mode.

**Comment by byte1024** [comment]
Got this when I tried to play a game installed from Windows even when egs launcher is installed through Lutris in an attempt to avoid re-downloading.

Epic launcher offline support isn't yet added: https://trello.com/c/aUVaDIUd/200-offline-sign-in I tried anyway and its not there in the launcher.

This shouldn't be a Lutris issue but should be from epic launcher and game. **Lutris cannot control  or circumvent this.**

**Comment by strycore** [comment]
This cannot be done. This is the equivalent of asking for Steam games to run outside of Steam. It will work with a handful of games (and we do support that option for them) but for the most part, games will depend on whatever launcher is used to be running with the game.

> obviously i cannot do that because changing the prefix setup would screw up my EGS installation
The only obvious thing here is that running games without EGS is impossible. Adapting a Wineprefix to be compatible with multiple games or creating multiple prefixes for a single EGS install is far more realistic.
Please open an issue about what's affecting your regular prefix when setting up JC4 then that can be worked on.
