### ISSUE TITLE
[Feature request] Closing "Import games" pop-up with another method

### ISSUE THREAD

**Issue by TheBrainScrambler** [lutris/lutris#2828]
Hello, this isn't really a bug, it's more a feature request.
When the Lutris client is opened and you click "+" > "Import Games", a pop-up spawns. The "problem" is that to close it, the only way of doing that is to click the cross on the titlebar. And well ... I disabled titlebars for personal purposes (if I do enable them, I got a double titlebar on the Lutris client, one being the one from the GTK theme and another from my WM). I actually tried to do CTRL+Q, but that closes all Lutris windows, not really convenient. And CTRL+W does nothing. So I have suggestions :
- CTRL+Q should only close the current window were you are
- Implement CTRL+W which should behave as described above
- Add a titlebar like you do for the main client or the "Manage runners" window
- Add a "Cancel" button as you did for the "Add game" pop-up
- Just ignore my request, but I would appreciate if you don't ;)

**Comment by xordspar0** [comment]
Does your window manager have a way of closing windows? Gnome, KDE, XFCE, etc. have alt-f4, for example.

**Comment by TheBrainScrambler** [comment]
I actually use Awesome, so yes it has a shortcut for that, however this will close all opened windows.

**Comment by xordspar0** [comment]
mod4-shift-c closes all windows? Not in my experience. Or are you thinking of a different shortcut?

**Comment by TheBrainScrambler** [comment]
Oh, well right ... it works. But still, it would be good to have something else, like doing CTRL+W or having a "Cancel" button like the other windows

**Comment by TheBrainScrambler** [comment]
Since I didn't got any response for some time, I would like to know if you could implement something as stated above

**Comment by xordspar0** [comment]
I was just looking at some Gnome apps to see what their behavior is. It seems like ctrl-q is for closing the whole application, ctrl-w is for closing tabs and *the main window* of the app if it supports more than one main window (like the file manager, document viewer, etc.). Notably, ctrl-w doesn't work for smaller pop-up windows like the file properties dialog, the preferences dialog, and the about dialog for Files. Gnome apps tend to use escape for that.

As for Lutris, I think my expectation as a Gnome user is that the import game window can be closed with escape because it's a little window where nothing will be lost if it is closed. The add game window, on the other hand, has user input typed into it, and I would expect it not to close when I press escape. It has a "cancel" and "ok" button anyway.

I know Lutris isn't necessarily a Gnome app, but it makes sense to me for it to follow the same guidelines since it uses Gtk. What do you think?

**Comment by strycore** [comment]
Ctrl+Q is for closing applications, that is set at the Window Manager level.
On Pop!_OS, it replaces Alt+F4.
This is not a behavior that can be changed by Lutris so if you expect Lutris to do something other than expected with Ctrl+Q, you can just close the issue.

**Comment by TheBrainScrambler** [comment]
@xordspar0 That sounds logical. I now also noticed that the "Connect to GOG account" window, the one where you enter your GOG crendentials exits when you press Escape. So I also think it should close on pressing Escape.

@strycore I'm not interesting in particulary changing the behavior of CTRL+Q, I'm just asking for a way to close only the "Import games" window with a button or a keyboard shortcut, so that you don't need to close it using the close button on the titlebar, which is usually on the right and with a cross.

**Comment by strycore** [comment]
Using a standard GTk header bar for that dialog is easy enough. 

Also, I wonder if there's a standard for that kind of situation in the Gtk guidelines. Gtk dialogs close with an Escape press but that won't work for application windows.

**Comment by strycore** [comment]
The Import Games window is gone so this isn't really relevant anymore.
