### ISSUE TITLE
Error when starting native game (runescape)

### ISSUE THREAD

**Issue by oleerik** [lutris/lutris#288]
Hello!

I'm experiencing this error:

`./runescape: /home/oleerik/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libxml2.so.2: version LIBXML2_2.9.0 not found (required by /home/oleerik/.local/share/lutris/runtime/lib64/libxslt.so.1)
./runescape: /home/oleerik/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libgpg-error.so.0: no version information available (required by /usr/lib/libgcrypt.so.20)`

The files requested are there and I cannot find anything wrong with them. I also don't understand why it's trying to use steam libraries to start this game as it's not a steam game.

Any ideas?

**Comment by strycore** [comment]
Hi,

Lutris uses its own runtime which is partly based on the Steam runtime, I removed libxml2 from our version of the Steam runtime and Runescape now launches with no problem!

To get the update, you need to restart Lutris, the runtime will update itself automatically (it can take a while since I updated the Steam part and it's the largest)
