### ISSUE TITLE
[Feature request] Epic Game Store over legendary

### ISSUE THREAD

**Issue by MordragT** [lutris/lutris#2891]
Recently i stumbled accross [https://github.com/derrod/legendary](legendary),  and i believe it could be a perfect fit to integrate the epic games store.
I dont really know my way around on the technical side of lutris or legendary, but wanted to bring this to youre attention, in case you had missed it.

Best Regards

**Comment by buxel** [comment]
I agree. From a technical side, it's rather straight forward. I have some WIP here already: https://github.com/buxel/lutris/tree/legendary-runner
You can already run it and it should allow you to install and launch games (testers welcome!), the problem is that there are currently no install scripts on lutris.net for it. You'd have to manually create one and pass it to lutris via `lutris -i my-script.yml`

I'm already in contact with the developer to work out some smaller kinks. A PR will follow so it can be discussed with the lutris team.

**Comment by MordragT** [comment]
Great to here that, I will definitly try that out.

**Comment by buxel** [comment]
PR here: #2894

**Comment by BeatLink** [comment]
The PR has been closed

**Comment by pktiuk** [comment]
What will happen with it now?

**Comment by Kyuunex** [comment]
literally the first thing on my mind when i found out about legendary

**Comment by benjamimgois** [comment]
Any news about epic / legendary integration ?

**Comment by pktiuk** [comment]
I think there won't be any significant updates, at least not until milestone https://github.com/lutris/lutris/milestone/46 will be finished.  
This is scheduled as a part of 0.5.10 milestone

**Comment by pktiuk** [comment]
I don't know what is the status of this, but in current beta release initial Epic support appeared.

https://github.com/lutris/lutris/releases/tag/v0.5.9-beta1

```
Add initial support for Epic Games Store
```

I don't know whether is it done using legendary, or in other way.  
I can't find any PR or other issue mentioning it directly.

**Comment by pktiuk** [comment]
@strycore

Is this issue still relevant?

**Comment by Atemu** [comment]
I'd say yes.

EGS support via the actual EGS launcher is very much appreciated but the option to use a Free alternative instead would still be worthwhile pursuing IMO. It could make for a much cleaner and less error-prone integration.

**Comment by SuperSamus** [comment]
Why is this closed?

**Comment by TSRBerry** [comment]
I'd really like to see legendary support as well and would prefer it over EGS.
I don't understand why this issue was closed. Especially since Atemu already mentioned very good reasons why this is desired.

**Comment by strycore** [comment]
This needs more context. In 2019, the Lutris project received a grant from Epic Games (aka The Epic Megagrant). I agreed with Epic Games to integrate with Epic Games Launcher. Back then, the idea of a Legendary based runner would go against this agreement. Fast forward to 2023 and now the EGS integration is now well established. But a new player has entered the game: Heroic Games Launcher, which is based on Legendary. So the ticket was closed because there already was a Linux client providing an open source alternative to EGS.

>  Atemu already mentioned very good reasons

I wouldn't call those very good reasons. More like borderline slander. 

>  cleaner and less error-prone integration

Our integration is clean and not error prone. It is also the most feature complete, since it gives all features of EGS, including downloading assets for Unreal Engine 5.

So putting any effort in developing this feature would put us in a weird situation were we have 2 competing integrations for the same store and would only target a small demographic of people who do not want to use either EGS or Heroic Games Launcher for some reason.

**Comment by TSRBerry** [comment]
> In 2019, the Lutris project received a grant from Epic Games (aka The Epic Megagrant). I agreed with Epic Games to integrate with Epic Games Launcher. Back then, the idea of a Legendary based integration would go against this agreement.

Interesting, then I just had a wrong view of how open of a platform Lutris is.

> I wouldn't call those very good reasons. More like borderline slander.

Excuse me, but I don't understand. What? How?

> Our integration is clean and not error prone. It is also the most feature complete, since it gives all features of EGS, including downloading assets for Unreal Engine 5.

Why wouldn't legendary be able to do the same? Your integration is just running EGS with Wine. It just feels weird that I need to launch a huge chromium application just to install games from this platform when there are better alternatives available.

---

My apologies, I clearly misunderstood and thought Lutris was trying to be an open platform, but with agreements like that and the way you are handling this I don't feel like that's the case.

**Comment by pktiuk** [comment]
I think that people willing to use epic games with legendary already use Heroic. Lutris is better for other users.

**Comment by strycore** [comment]
> My apologies, I clearly misunderstood and thought Lutris was trying to be an open platform, but with agreements like that and the way you are handling this I don't feel like that's the case.

Now it's no longer borderline slander, it's complete FUD. 

Integrating with the EGS application does not make Lutris less open. We are doing the exact same with Battle.net, EA App (prev. Origin), Ubisoft Connect (prev. UPlay) and before Proton was a thing, Steam.

Receiving a grant from Epic does not make Lutris less open, Lutris is proud to share this achievement with some of the best open source software there is: Godot, Blender, Krita....

Not integrating with every possible piece of free software there is out there does not make Lutris less open, we're focusing our development in advancing the project given the resources we have.

What makes Lutris open is the fact that anyone is able to offload the weight of writing and maintaining such a feature from the core development team. If someone were to submit a PR offering integration with Legendary, it would receive more consideration than asking the core team to stray off their roadmap to implement something that we already have.
