### ISSUE TITLE
Use discrete graphics toggle is grayed out

### ISSUE THREAD

**Issue by zQvypF8EaxNuN6** [lutris/lutris#2897]
In the systems options for the game I am trying to run (Guild Wars 2 / WINE), the "Use discrete graphics" toggle is grayed out. This makes me wonder if the Vega 8 APU is being utilized. 

I followed the driver instructions on Lutris at https://github.com/lutris/docs/blob/master/InstallingDrivers.md for Manjaro and AMD. Currently have MESA 20.0.6 installed with amdgpu driver.

Using LTS kernel on Manjaro XFCE. Laptop is a Huawei Mate D 14" with Ryzen 2500u and Vega 8 discete APU. I have used Wine-Staging 5.8, Lutrix 5.6-2, DXVK 1.6.1L & DXVK 1.7L and none of this caused the option to be able to toggle on and off. I added DRI_Prime = 1, RADV_PERFTEST = aco, and WINEFYSNC = 1 to environmental variables.

![Use Discrete Grayed Out](https://user-images.githubusercontent.com/65871945/82765077-e04b2180-9dd0-11ea-8dd6-fe7b330c2d8b.png)

Thank you for your help in advance.

**Comment by byte1024** [comment]
Lutris uses lscpi to check for gpu's with this setting.

If you do $ lscpi, you should get various info (if lscpi isn't found then that would definitely be why its disabled).

It looks for multiple gpu's in that text. The devs here might want to know the result of lscpi if it contains multiple gpu's as it looks like Lutris isn't finding multiple there.

**Comment by zQvypF8EaxNuN6** [comment]
I am assuming you mean the command lspci and not lscpi (never heard of this command and google results were people typoing lspci). If that is what you meant here is the results of lspci:

lspci
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:01.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 PCIe GPP Bridge [6:0]
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Internal PCIe GPP Bridge 0 to Bus A
00:08.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Internal PCIe GPP Bridge 0 to Bus B
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 61)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 7
01:00.0 Network controller: Intel Corporation Wireless 8265 / 8275 (rev 78)
02:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c4)
02:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Raven/Raven2/Fenghuang HDMI/DP Audio Controller
02:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
02:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Raven USB 3.1
02:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Raven USB 3.1
02:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor
02:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) HD Audio Controller
03:00.0 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 61)

Very respectfully,

Mark Horton
(707)800-5130
markhorton27@protonmail.com

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by byte1024** [comment]
Yes, lspci, I have trouble typing that correctly lol haha.

If I'm not mistaken there's only one gpu showing up

`02:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c4)`

which is the APU. I don't see any discreet gpu. That would be why its disabled. If you have a discreet gpu then its not showing up there.

If you are thinking that the APU's gpu isn't being used because that's disabled then that is nothing to think about.

**Comment by byte1024** [comment]
Yes, lspci, I have trouble typing that correctly lol haha.

If I'm not mistaken there's only one gpu showing up

02:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c4)

which is the APU. I don't see any discrete gpu. That would be why its disabled. If you have a discrete gpu then its not showing up there.

If you are thinking that the APU's gpu isn't being used because that's disabled then that is nothing to think about.

**Comment by byte1024** [comment]
Yes, lspci, I have trouble typing that correctly lol haha.

If I'm not mistaken there's only one gpu showing up
`
02:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c4)`

which is the APU. I don't see any discrete gpu. That would be why its disabled. If you have a discrete gpu then its not showing up there.

If you are thinking that the APU's gpu isn't being used because that's disabled then that is nothing to think about and this can be closed.

**Comment by byte1024** [comment]
Have a feeling this should just be closed.

The Intel version of the MateBook D has a discrete gpu possibility but the AMD one here does not.

https://www.notebookcheck.net/Huawei-launches-upgraded-MateBook-D-14-and-MateBook-D-15-range-with-AMD-APUs-10th-Gen-Intel-processors-and-NVIDIA-GPUs.445010.0.html

**Comment by zQvypF8EaxNuN6** [comment]
Byte1024,

I see.So I confused Ryzen's Vega 8 APU with being a discrete GPU when in reality an integrated APU and discrete GPU are different? I will close the problem if this is confirmed. I always thought the Vega 8 was similar to Intel's MX line as they are regularly compared.

Very respectfully,

Mark Horton
(707)800-5130
markhorton27@protonmail.com

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by byte1024** [comment]
Yes, there has to be 2 GPUs for the discrete setting to work. Example, I have a discrete 2060 RTX but the setting is disabled because there's no APU integrated GPU.

As far as I understand the Vega is integrated to the Ryzen APU so it is not a discrete GPU https://www.amd.com/en/products/apu/amd-ryzen-5-2500u

Even if it was not internal to the CPU, you have to have 2 GPU's (an internal CPU one and other one) for this setting to work. Only one GPU exists in the hardware you have. Therefore, that one GPU will be used.

**Comment by zQvypF8EaxNuN6** [comment]
Got it. Thank you for your help. This can be closed. Wishful thinking for another tweak for hidden performance gains lol

Sent from ProtonMail mobile

-------- Original Message --------
