### ISSUE TITLE
gamemode option greyed out on kubuntu 20.04

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#2917]
**Describe the bug**

Option greyed out.

**Expected behavior**

Not, greyed, out.

**Current behavior**

Greyed, out.

**Steps to reproduce**

- Install ubuntu 20.04
- Install lutris
- Launch lutris

**Lutris debugging output**

[gamemode.tar.gz](https://github.com/lutris/lutris/files/4716458/gamemode.tar.gz)

**System information**

[lutris-issue-report.tar.gz](https://github.com/lutris/lutris/files/4716460/lutris-issue-report.tar.gz)

**Screenshots**

![image](https://user-images.githubusercontent.com/5204968/83504878-b5965280-a4cd-11ea-8aa1-016ac86d8407.png)

**Comment by byte1024** [comment]
I believe that it should only be greyed when it can't find what it needs to find on the system (50% a Lutris problem) or Feral game mode isn't installed correctly for Lutris to use (100% user problem).

In any case, an issue present on the official git suggests Debian based distros don't fully support Feral game mode out-of-the box? https://github.com/FeralInteractive/gamemode/issues/216

In the end, if you search and find libgamemodeauto.so in /usr/lib & /usr/lib64 then I would assume it should not be greyed out as that's what it looks like the setting is using to determine eligibility.

**Comment by byte1024** [comment]
Yes, on Ubuntu 18.04 libgamemodeauto.so.0 shows up as 64bit only and in /usr/lib/x86_64-linux-gnu.

Maybe Lutris can try to support it as-is but I don't know why it doesn't already.

**Comment by JanGalek** [comment]
Ubuntu 20.04 is 64bit only, fast fix is Configure -> System options -> Command prefix set to gamemoderun ;) Of course you can setup it for every new installation in **Manage Runners**

**Comment by stephanlachnit** [comment]
> Ubuntu 20.04 is 64bit only

That's not true, Ubuntu doesn't offer a full 32bit image, but they still build tons of packages in 32bit so that they can be used on the 64bit image. It just isn't the case for gamemode (for now).

> In any case, an issue present on the official git suggests Debian based distros don't fully support Feral game mode out-of-the box? [FeralInteractive/gamemode#216](https://github.com/FeralInteractive/gamemode/issues/216)

Just for reference, this isn't true and never was, a long time only 64bit builds have been made.
Debian supports 32bit for over a month now, for Ubuntu it's a different story, see my explanation here: https://github.com/FeralInteractive/gamemode/issues/252#issuecomment-638286326

**Comment by strycore** [comment]
it doesn't matter anymore, gamemode now uses an executable so you can have the 64bit only parts installed and it will still work.

**Comment by mYnDstrEAm** [comment]
Why is it greyed out in Debian10 after installing gamemode? libgamemodeauto is in /usr/lib/x86_64-linux-gnu/ but not /usr/lib/

Is it because of an outdated version of gamemode in the Debian repos?

**Comment by stephanlachnit** [comment]
> libgamemodeauto is in /usr/lib/x86_64-linux-gnu/ but not /usr/lib/

As it should be.
 
> Is it because of an outdated version of gamemode in the Debian repos?

You're using Debian stable, so that is to be expected. But I created a backport with Multi-Arch support, it just landed (https://tracker.debian.org/pkg/gamemode), so it should be available in the next couple of days. You need to install it by hand though: https://backports.debian.org/Instructions/
