### ISSUE TITLE
Lutris can't create slug with Japanese titles when it contain no Alphanumerical symbols

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2932]
**Describe the bug**

Trying to add a game with an japanese title, but Lutris won't allow it, creates a error on the terminal

Adding [メイド☆ぱらだいす ～目指せ！メイドナンバーワン！～ ](https://www.jp.playstation.com/software/title/jp0604npjh00099_00maidpara00000000.html) and Lutris creates the following on the terminal: 

```
Saving メイド☆ぱらだいす ～目指せ！メイドナンバーワン！～ (ppsspp)
DEBUG    2020-06-10 11:02:58,692 [config.save:211]:Saving LutrisConfig(level=game, game_config_id=-1591779765, runner=ppsspp) config to ~/.config/lutris/games/-1591779765.yml
Traceback (most recent call last):
  File "~/src/lutris/lutris/gui/config/common.py", line 535, in on_save
    self.game.save()
  File "~/src/lutris/lutris/game.py", line 252, in save
    playtime=self.playtime,
  File "~/src/lutris/lutris/pga.py", line 382, in add_or_update
    game_id = get_matching_game(params)
  File "~/src/lutris/lutris/pga.py", line 400, in get_matching_game
    raise ValueError("Can't add or update without an identifier")
ValueError: Can't add or update without an identifier
```

I'm guessing it has to do with the ☆in the title

**Comment by xordspar0** [comment]
The docstring for slugify says that it "[removes non-alpha characters](https://github.com/lutris/lutris/blob/master/lutris/util/strings.py#L12-L27)". I guess that's a problem for a name that contains no alpha characters.

I opened a PR that has a failing test that covers this case. I don't know the best way to solve it though, so anyone who wants to tackle this can take that code.

https://github.com/lutris/lutris/pull/2935

**Comment by strycore** [comment]
The website works around this issue by falling back to romkan, pinyin and translit to handle non latin alphabet. See: https://github.com/lutris/website/blob/master/common/util.py#L13

The problem is that I don't want to ship 3 extra packages on the desktop client just to handle slug generation... So I'm not sure how to handle this.

**Comment by YihaoPeng** [comment]
The end user does not really care about the file name of the configuration file, so it is OK to generate a uuid as the file name.

**Comment by xordspar0** [comment]
Isn't the slug also used for the default name of the game folder?

**Comment by strycore** [comment]
that's correct, and the client will keep making request to a random hash to find non existent icons.
that's not a huge problem but it's something to consider if we're going to roll with a hash.

**Comment by malefice** [comment]
Since Django 1.9, `slugify` can accept an `allow_unicode` kwarg [(link to 2.2 docs)](https://docs.djangoproject.com/en/2.2/ref/utils/#django.utils.text.slugify). Maybe we can vendorize Django's implementation of slugify into the lutris client to allow names with purely non-ascii characters. If the server-side only stores ASCII-only slugs, then server-side can apply the necessary ASCII-fication to whatever non-ASCII slug the client may throw at it. Does this sound viable?

**Comment by YihaoPeng** [comment]
Just a reminder, including non-ASCII characters in file/directory names or URLs has a lot of technical details to pay attention to.

For example, the character encoding of the user's file system may not be UTF-8, and thus cannot store specific characters.

When passing the URL, urlencode needs to be correctly performed.

Finally, it is well known that a large number of Windows applications cannot properly handle non-ASCII file/directory paths. Passing such paths to them can cause strange runtime problems. Although `Wine` will convert the `wineprefix` path to `C:\`, this may reduce the problem.

**Comment by malefice** [comment]
@YihaoPeng I made the suggestion because it is "better" (huge air quotes) in some aspects for a lack of better term. For example, if you manually add a game named `メイド☆ぱらだいす ～目指せ！メイドナンバーワン！～Starcraft Remastered`, under the current implementation and even using your suggestion, it will end up as `Starcraft Remastered`. Granted this is a corner case where normal users will not do anything like this, and I am not even sure if there are even games nwith names that will ever trigger this, but the possibility is there.

Under my suggestion or if lutris ships with the 3 additional packages, the same string will be considered as an entry different from both `メイド☆ぱらだいす ～目指せ！メイドナンバーワン！～` and `Starcraft Remastered`, and it will also solve the current issue. My suggestion, however, does fall apart in the situations you mentioned.

If shipping the three extra packages is totally out of the question, and if we do not want to deal with all the technical issues we might encounter with non-ASCII names, maybe we can implement identifiers for all games instead like the way steam assigns appid's to games in their store? Then on the web side of things, support lookups using either identifiers or names? What do you think?
