### ISSUE TITLE
can't use lutris due to issues with the ssl

### ISSUE THREAD

**Issue by Ds886** [lutris/lutris#2970]
**Describe the bug**

failing to authorize the ssl certificate when trying to connect or get launchers

**Expected behavior**

that It will be able to grab content from the site

**Current behavior**

What is the current behavior?
It is not able to connect to the site

**Lutris debugging output**

```
NFO     2020-06-28 14:15:09,096 [application.do_command_line:245]:Running Lutris 0.5.5
INFO     2020-06-28 14:15:09,096 [startup.check_driver:62]:Using Intel Open Source Technology Center
INFO     2020-06-28 14:15:09,096 [startup.check_driver:67]:Running Mesa driver 19.2.8 on Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)  (0x3e9b)
INFO     2020-06-28 14:15:09,096 [startup.check_driver:79]:GPU: 8086:3E9B 1028:0827 using i915 drivers
INFO     2020-06-28 14:15:09,149 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-06-28 14:15:09,150 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
DEBUG    2020-06-28 14:15:09,281 [http.get:65]:GET https://lutris.net/api/runtime
ERROR    2020-06-28 14:15:09,314 [dxvk.get_dxvk_versions:31]:<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
ERROR    2020-06-28 14:15:09,318 [runtime._iter_remote_runtimes:156]:Failed to get runtimes: Unable to connect to server https://lutris.net/api/runtime: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
INFO     2020-06-28 14:15:14,648 [application.do_shutdown:491]:Shutting down Lutris
```
**System information**

Ubuntu MATE 20.04, Vostro 7580

**Screenshots**

**Comment by strycore** [comment]
Your ISP (or someone else) is tampering with your internet.
Do one else has issues with the SSL certificate, it's standard Cloudflare stuff

Do you live in a country where human rights are not respected?

**Comment by Ds886** [comment]
Sorry if the above message was a bit stiff and unwelcoming, had a bit of rough day and it might have reflected in the original request.

I live in Israel and in another Debian install under the same network it works fine, but in the prior Ubuntu MATE install(18.04) on another laptop Lutris never worked.

around the first time I've tried to run it I've tried installing libssl form source as people mentioned it as solution around that time(incompatible libraries), today I have upgraded the install to 20.04 and decided to try to run lutris again.

I can reach the site and the services in the browser but not through wget or lutris. I've tried to import the certificate, while it didn't help with lutris, It helped reaching the site with wget.

I would format a clean install of manjaro/arch by now but it is a laptop with dual boot and it is a bit more of a pain to do given I've already customized the install and I prefer to maintain the state of the system otherwise.

between attempts I also tried clean install or cleaning things I've changed and kept tracked of what I am doing constantly in order to reverse it.

right now I am not next to the particular computer but my next step would be to check the python libraries or create a dummy scritp in python first to make sure it is the source are there any other things that could cause the issue?

**Comment by strycore** [comment]
Can you provide me with your AS?  `whois $(curl ifconfig.me) | grep AS`

**Comment by byte1024** [comment]
Tracked

`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>`

down to the ca-bundle on the users OS installation. On Fedora its at /etc/ssl/certs/ and I'm not sure if its exactly the same for Debian based distros at the moment.

The easy way to figure this out is that editing the ca-bundle and changing the DigiCert's (which the ssl cert of https://lutris.net/api/runtime uses) so that its no longer valid (or current if you will), produces this error.

That goes with others who have run into this error as well (examples)...
https://forums.lutris.net/t/fixed-unable-to-connect/9662
https://github.com/lutris/lutris/issues/1140#issuecomment-506056942
https://github.com/ritiek/spotify-downloader/issues/480

Its possible perhaps that there's still some other combination such as 
sudo pip info certifi or ca-certificates distro package
as an example.

I don't think its actually a Lutris issue but certificates on the user's OS that are out-of-date or somehow incorrect. I'm not finding any certificate problem on my end. So just updating the ca-bundle or refreshing it should fix the issue.

The error also specifies "unable to get **local** issuer certificate" as in its local to something. If it can't connect then it should be local to the user. Lutris I don't think supplies certs (didn't check that) but it is definitely using ca-bundle which I don't think Lutris has anything to do with (again didn't check.

**Comment by byte1024** [comment]
Further info on this and some other things to look into: https://serverfault.com/questions/891734/debian-wheezy-outdated-root-certificates

I'm still not 100% sure why it happens. Looks like they coded in --fresh because they know there will be bugs lol. I can find some bug fixes related to fixing things so --fresh didn't have to be used in those cases - that wouldn't be the case for everything.

**Comment by Ds886** [comment]
I am not sure what i've did
I did as byte suggested and it didn't help at first, I then did a fresh reinstall and what byte suggested and it worked.

**Comment by legluondunet** [comment]
@strycore this issue seems resolved, could you close this issue?
