### ISSUE TITLE
[Feature Request] Add "expected filename" to installers; locate the file automatically

### ISSUE THREAD

**Issue by jimj316** [lutris/lutris#2987]
I have a suggestion for a quality of life feature: adding a field to install scripts to specify the expected filename for a file (eg. the game archive) that needs to be chosen. 

This would allow the installer to perform a very quick check to see if a file by that name exists in a few key locations, such as ~/Downloads; if it does, it could preselect that file for the user, making the install process a lot quicker. The user would still need to press OK to confirm that it is the right file.

There is a small risk of false positives, especially if a file has a very generic name (eg. game.zip), which is a drawback.

It might also be helpful for future features, like finding games already installed (#2858; although only if the archive's still around), and unattended installation (#2907)

**Comment by byte1024** [comment]
`This would allow the installer to perform a very quick check to see if a file by that name exists in a few key locations, such as ~/Downloads; if it does, it could preselect that file for the user, making the install process a lot quicker. The user would still need to press OK to confirm that it is the right file.`

Could alternatively just show a list to select from (including a "not one of these") as what happens when there are multiple ones in various locations? Could happen.

A bunch of complex issues possible, such as should the key locations be a simple editable field so the user can change them as I'm sure some people use very different folders than standard or whatever.

Probably more hidden problems that should be taken into account.

**Comment by strycore** [comment]
That kinda clashes with the work done on the file-picker branch and anyway we would NEVER do some wild guesses like that.

I understand the motivation behind the ticket but this is not a solution. Stay tuned for lutris 0.5.8, there will be some major changes in this aspect of lutris.

**Comment by strycore** [comment]
btw, you can already cache downloaded files if you enable the PGA cache in the preferences.
