### ISSUE TITLE
Newst Lutris from git problem with Python 3

### ISSUE THREAD

**Issue by ksaadDE** [lutris/lutris#3000]
When installing lutris by cloning it from the Repo, there're some Python3 (and Modules) related bugs. 
Also some libs / pip modules needing manual installation, maybe some notice or auto setup tool is needed, to make the process easier.

If I get the bug again I will report a more detailed log. Currently I can't replicate it. 
( And yes I tried the setup.py before, but that doesn't fix the problem)

It was something with lutris GUI and a .py lib (maybe you know it already) I used some snippet posted in some Forum to fix it.

**Comment by strycore** [comment]
![](https://media.giphy.com/media/l3V0o7QyRb08irLag/giphy.gif)

**Comment by strycore** [comment]
The Travis build is not failing (https://travis-ci.org/github/lutris/lutris/builds/706384320) and no one else has raised any issue. Any piece of information you can provide will be helpful to resolve the issue you are running into.

**Comment by ksaadDE** [comment]
@strycore  Sorry for the less than good documentation of the issue! Like the reaction in the GIF - that was exactly my face when I looked at it!

The build itself seems ok, but after starting lutris the Python dependencies running against each other. 

Ah I remember a bit... ! I had to force Python to Python3.7 then running bin/lutris (inside the Lutris folder)
also I had to change a line in some python file. 
Found it:
https://paste.ubuntu.com/p/q8Fz9jVhvn/

Line 134 in __init__ 
```
self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
     AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
```

And a Forum somewhere in the net told me I had to remove the sort before it. Due to Python Versions
`self.modelsort = Gtk.TreeModelSort.new_with_model(self.modelfilter)`
Is then the correct function usage in Gtk.TreeModelSort!

**Comment by strycore** [comment]
That's from an old version of lutris. You should not run into this while using the current stable release (or even the one before that). It doesn't have anything to do with Python, it was a weird API breakage in Gtk.

**Comment by ksaadDE** [comment]
@strycore  No it wasn't a old version it was a fresh git clone from the lutris Repo :100: Are you really sure that can't happen with new Lutris + old Python? Maybe that's the problem. 

Which Python version runs your auto Build? I had the issue with Python Version less than 3.7. I think there is the bug.

I didn't read the Exception deeply, I just saw something with Python + GTK. It's still a Python thing, since the Exception is thrown by Python. I did just a quick GoogleFu to see what I have to change, then I got the result and fix above. 
Next time I will go deeper in the rabbit hole to understand what the heck goes on here :> 

If I have more time I try a VM with my configurations and lets see if I can replicate it.

**Comment by ksaadDE** [comment]
Update: I saw your Python auto build runs with Python3.6... ._. I think there's the weird Bug!
From your link above: https://travis-ci.org/github/lutris/lutris/builds/706384320 

In the newst build: Python 3.6.9

Are you really sure there is nothing changed on the GTK side or yours? Between 3.6 and 3.7? O.o  I had after fixing the GTK issue also another Bugs, then I cloned it again and run it with Py3.7 and it run well (a few GUI issues were also there .. but yeah it were very stable to a point then)

**Comment by strycore** [comment]
Let me clarify this again.

A line like `self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)` is valid python on every python release that has ever existed. This has nothing to do with the python version you are using, I repeat: this has nothing to do with the python version you are using.

The fix for this bug has been submitted 6 months ago: 

```
        try:
            self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
        except AttributeError:
            # Apparently some API breaking changes on GTK minor versions.
            self.modelsort = Gtk.TreeModelSort.new_with_model(self.modelfilter)  # pylint: disable=no-member  # NOQA

```

Anyway, I just noticed that your logs says you're running lutris 0.5.4 while you said twice that you were running the git version.

You may need some sleep or step away from the computer for a while, you know, just to take care of yourself and not get yourself all confused and stuff.

**Comment by ksaadDE** [comment]
@strycore Very polite man. I reported a Bug and get instant insulted, happy birthday rofl 

**Okay back to your shittalk:** 
you should read more carefully, because I just told you that **the Logs aren't my Logs**. I just copied them from your Lutris Forum, where the Bug occured too. I never wrote my Logs or something like that, because I deleted Lutirs instantly after having 24 hours troubleshooting of your stuff, but hey I knoww it's hard work and you have a lot todo. I am happy to use it like it is, even with Bugs and so on. 

Also you should know that Python pulls dependencies based on Version. So pip2 and pip3 can contain fully different Dependencies / Modules. 

Btw: I never assumed or wrote down that your code line is no valid Python, but OK. Maybe you should rest more.. and read more carefully (again).

Ask yourself a bit why someone should contribute to your Project, if you run instantly your Hellstorm against someone who contributes. Maybe you just had a bad day, shit happens. 

Looking forward to work together, in a friendly manner, maybe you want it too.

**Comment by strycore** [comment]
Sorry that you felt offended by that. Lutris is starting to be a pretty big project and it is not even half way done from my point of view. I cannot let old issues I fixed in January come back and haunt me. I cannot have someone question our Python compatibility when I have tested Lutris on Python 3.5 up to 3.8 in the past few days.
I have over 200 open issues on the client alone. This is not something I'm comfortable with. So when an issue comes up and it's about some stuff I know for sure is working, then I'm not always delicate.

I'm just hoping that after further investigation, you will find out why you are running code from last year or realize you're running into a different issue than the one you pasted the logs for. There is likely some missing piece of information in our documentation that made you run into this issue.

**Comment by ksaadDE** [comment]
Nvm. Lutris a really important Project for the Community and I think it's not only big, it's very interesting. Thank you for doing it (and the Rest who's helping)! 

I'll report back, if I find it and then I'll have a better Documentation.
Sorry for my bad Documentation, I swear next time I'll do it better :>
