### ISSUE TITLE
Do not block games from launching while runtime is updating

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#301]
Hi

Not sure about this, got it this afternoon, when trying to launch a quick game while on lunch. 

Lutris came up with a Runtime updating window, http://i.imgur.com/vmGkj3R.png. Wouldn't it be better to ask if you want to update, and tell what is being updated? the empty popup could be used to inform the user about what is being updated

**Comment by RobLoach** [comment]
For me, the Runtime Update took a while, and I got impatient, and ended up disabling it in the Advanced Settings.

**Comment by strycore** [comment]
I pushed an updated version of the Steam runtime yesterday, which is quite large. Disabling the runtime won't stop the client from updating it, there is currently no way to prevent runtime updates (and we have no plans to make runtime updates optional).
Steam runtime updates are very rare, I usually only update the lib32 and lib64 runtimes. Just be patient a let the update finish :D

**Comment by RobLoach** [comment]
I'll update Lutris, along with the Runtime, and report back if it still takes forever.

**Comment by strycore** [comment]
Yes, this needs improvement. There was once a progress bar when the runtime was one single file, now that it's divided in 3 parts, the code has to be reworked to display multiple progress bars.

Note that runtime updates have nothing to do with the client version. I push runtime updates when I want to add or change libraries and they get downloaded automatically by everyone.

**Comment by telanus** [comment]
Why I ask about the ability to postpone the update is not everyone has that 10+ minutes to wait while the update is running, like yesterday I had maybe 10 minutes before I needed to leave for work while on lunch, instead of playing, I made this tread, and in the end cancelled the update as I had to go to work.

**Comment by strycore** [comment]
Ok, here is another proposal which I think is better.
We could make the runtime updates non blocking and show the progress in the status bar.
If people are running games while the runtime is updating, they'll know that games have a chance of not running because the runtime is not fully ready. 
And for simple updates as opposed to the initial download, chances are that 99% of the games will run with the old runtime. (For example, yesterday's update did not fix any game, it removed a warning in Wine due to an outdated library)
