### ISSUE TITLE
Can't start lutris

### ISSUE THREAD

**Issue by sebas10007** [lutris/lutris#3015]
I install lutris, there it's the logo, but don't do nothing so i try to run it in the terminal and it's appear [https://paste.ubuntu.com/p/Ty4Y2jFVTN/](url) 

**Screenshots**

![Captura de pantalla de 2020-07-12 11-10-48](https://user-images.githubusercontent.com/45272782/87251321-72b28d80-c430-11ea-9b37-5d2d472cdf37.png)

**Comment by strycore** [comment]
have you used the setup.py script to install Lutris?

**Comment by sebas10007** [comment]
I only execute in the terminal , I am using Ubuntu 20.04 LTS

sudo add-apt-repository ppa:lutris-team/lutris
sudo apt-get update
sudo apt-get install lutris

**Comment by strycore** [comment]
Do not make me check if we messed up our package tell me what you actually did.
We do not place Lutris in /usr/local.

**Comment by sebas10007** [comment]
ok ok.... 
I used setup.py to try to install lutris but I stopped and before that I try whit the lutris file on ./lutris/bin. them lutris don't work so i try "sudo add-apt-repository ppa:lutris-team/lutris
sudo apt-get update
sudo apt-get install lutris"

and that's all

**Comment by strycore** [comment]
Yes, and using the setup.py script override whatever the repo does.
Your system is broken until you have removed every trace of the setup.py script.
There is not automated way of uninstalling stuff that has been installed with setup.py, just look for lutris stuff in /usr/local and delete them.
We explicitly tell users not to use that script for installation and for good reasons... I mean, look at you opening github issues and all.

In the future, when you see a python program with a setup.py script, do not touch it. This script is for package maintainers only.

Closing this ticket since after you're done deleting the files in /usr/local then the client should work just fine.
