### ISSUE TITLE
Error message: FSYNC_NOT_SUPPORTED even fsync is disabled

### ISSUE THREAD

**Issue by Dakai** [lutris/lutris#3039]
Hi, the Lutris has been working very well with my Battlenet client and world of warcraft game, however, after a kernel upgrades to Linux 5.7.4-1-Clear, the game can not be started anymore, there is an error says my kernel is not patched with fsync, and the Fsync is not supported, but I don't need Fsync and it is disabled in the game option of Lutris, please help, thank you very much.

**Comment by byte1024** [comment]
I ran into this yesterday. Not sure what's going on with the kernel or fsync but just because the setting is disabled doesn't mean that the Lutris install script didn't enable it some other way ;-)

You need to check in the lutris configuration of the game/application for additional fsync usage such as on the system options tab or maybe even game options if it can be passed as an argument there. I found one I think in system options for example.

This could be seen as a bug I suppose since the fsync setting doesn't disable other fsync enablement through arguments.

Outside of that, not sure what they could do really, and might not be a bug otherwise.

It also depends on what happened to fsync and if Lutris needs to change or if it's just broken on that kernel or whatever.

I haven't looked into it.

**Comment by byte1024** [comment]
I would think it has to do with this https://github.com/lutris/lutris/commit/f71ad93c91bae4f5c1458769a8c2be055e0048e4

They added a check with Lutris 0.5.7 which should now block on non-supported kernels and before it did. So its probably not really a bug here. I probably didn't run since 0.5.7 and my guess is either you got 0.5.7 at the same time or didn't run also since getting 0.5.7 and its a coincidence.

**Comment by Dakai** [comment]
Thanks for the information, it turned out it was me being stupid, I set WINEFSYNC=1 in the game configuration, the game worked very well in previous kernels, so I didn't check the environment variables.
