### ISSUE TITLE
AlterEgo games use Windows line ending in their launch script

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#305]
examples:

https://lutris.net/games/alterego/
https://lutris.net/games/alterego-dreamwalker/

**Comment by strycore** [comment]
Nah, the games work fine, the problem is that the developers of these games have shipped their launch script with Windows line endings so calling the scripts, even from outside Lutris will fail.

The following options for fixing this are available:

- Hosting a working copy of the script somewhere else
- Bypassing the script completely and calling /usr/bin/mono as the game executable
- Calling /usr/bin/dos2unix in the installer
