### ISSUE TITLE
Lutris database error

### ISSUE THREAD

**Issue by Loubaris** [lutris/lutris#3084]
**Describe the bug**

When I type lutris -d, I get this error ( I am on debian )

Traceback (most recent call last):
  File "/usr/bin/lutris", line 33, in <module>
    app = Application()
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 60, in __init__
    init_lutris()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 46, in init_lutris
    init_db()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 40, in init_db
    pga.syncdb()
  File "/usr/lib/python3/dist-packages/lutris/pga.py", line 130, in syncdb
    migrate(table, DATABASE[table])
  File "/usr/lib/python3/dist-packages/lutris/pga.py", line 112, in migrate
    existing_schema = get_schema(table)
  File "/usr/lib/python3/dist-packages/lutris/pga.py", line 69, in get_schema
    for row in cursor.execute(query).fetchall():
sqlite3.DatabaseError: file is not a database

I think the problem is from a library and I don't know what to do,
thanks for any help

**Comment by byte1024** [comment]
I had a problem kind of like this but not with lutris and a reboot fixed it. You could try it just to rule it out even.

It looks like a sqlite3 or lutris migration issue, so if a reboot doesn't work, I would expect these two or a python issue.

Otherwise, I don't get why it would be complaining about a file not in the db otherwise unless lutris had a special issue that this error here doesn't fully explain that you tripped or unless you had messed around with the lutris installation and it caused this (doing that can cause migration issues).

**Comment by byte1024** [comment]
I feel the need to comment yet this one is a bit of a pain.

Looks like it is "sqlite3.DatabaseError: file is not a database" but that is the end result and the real problem is something else. I'm not sure if its coming from get_schema, some system problem, or a package. I basically need to debug and run through how Lutris executes this to see what it could be.

On top of that, if it creates a db file and works with it for one system, as long as the user system is set up in a compatible way it should be correct in Lutris.

There are various things that cause this. One is supposedly changing sqlite to sqlite3 for example. https://stackoverflow.com/questions/48974135/sqlite-error-file-is-not-a-database

But, in the worst case, I would think deleting it might work but will lose everything saved for Lutris. It is ~/.local/share/lutris/pga.db

You can also open that file in text editor and see if it starts with "SQLite format 3".

Suppose it could have been corrupted as well which will cause this error in which case you have no choice as there's no backup file that I know of at this time unless they sync it (also not something I know of at this time).

**Comment by Loubaris** [comment]
I don't find the ~/.local/share/lutris/pga.db

**Comment by byte1024** [comment]
Suppose strycore will know if its there on all systems or can change?

If its not there then either it changes and you can also search for it or well, I would expect a different error if it didn't exist.
