### ISSUE TITLE
runner: PCSX2 Lutris runner does not work

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3115]
Hello,
PCSX2 runner never worked on my computer. I downloaded the last version today and same result: nothing started.
I didn't install bios files, could this avoid Lutris PCSX2 runner to start?

I joined you the log.

[lutris pcsx2 runner.txt](https://github.com/lutris/lutris/files/5126514/lutris.pcsx2.runner.txt)

**Comment by strycore** [comment]
You need the BIOS files to play games but the emulator should start without and let you configure your BIOS files.
I recently pushed a patch for library detection with PCSX2. Since PCSX2 is 32 bit only, the most common issue for it not starting is a missing dependency.
Also be sure to redownload the lutris runner if you haven't lately. I pushed 1.7.0-dev a few days ago.

**Comment by TheWranger** [comment]
Not sure if it's related but there is definitely a missing dependency in the new build that stops the GS plugin from working (if you install the latest dev build of PCSX2 with all dependencies then the Lutris build will work find). Will try to figure out what it is

**Comment by TheWranger** [comment]
It's missing libegl1:i386 and (presumably) libegl-mesa0:i386

**Comment by strycore** [comment]
PCSX2 should display warnings if a missing lib is detected.
