### ISSUE TITLE
Lutris can't create prefix without proton wineboot on any lutris wine

### ISSUE THREAD

**Issue by Meister1593** [lutris/lutris#3123]
**Describe the bug**

Every time i want to create prefix, it tries to find wineboot in proton 5.0 directory for some unknown reason.
Fails to do so, results in no prefix, lutris saying that prefix not found and throws error stack trace in terminal.
In Lutris app, dialog box or any indication isn't thrown.

Tried using `Proton 5.0`, `lutris-5.7-8`, `lutris5.6-5` wine - doesn't matter.
Prefixes created before (or outside lutris) are working fine. It's only the prefix creation
Kernel doesnt matter, happens on usual kernel too (i use tkg kernel)

**Steps to reproduce**

Trying to press button *wine configuration* in empty non-created prefix.

**[Lutris debugging output](https://gist.github.com/Meister1593/ab1531a8a115bab2535d9afd2979b376)**

**[System information](https://gist.github.com/Meister1593/4748c9edbbc58ceb240d5fd107d68c3d)**

**Comment by strycore** [comment]
wow.

**Comment by strycore** [comment]
I really cannot use this information. It is useless to me. 
And it is a common problem.
You will now ship your computer to me because people can't explain their problems correctly.
If I had your computer, I could fix this problem in like 5 minutes.
So you're going to ship your computer to me and I'm going to fix the issue and then I will ship your computer back.
Please contact me so I can send you a Fedex shipping label for your computer.

**Comment by GloriousEggroll** [comment]
@Meister1593 Proton does not ship with wineboot, and wineboot is necessary for prefix creation. The reason proton when used within steam creates a prefix is because when proton is built and packaged it uses wineboot to create a default prefix which is then copied per game.  The default prefix is packaged with proton, wineboot is not. You need to create the prefix using a normal wine version and/or lutris installer. If you wish to run a game with proton, you need to change the runner after the game prefix has already been created/installed in lutris.

**Comment by Meister1593** [comment]
@GloriousEggroll This means, that i can't create new prefix using even lutris wine (which is shipped with lutris itself)?
I have to use plain wine for doing this thing?
As i said, not even lutris wine could create prefix, even plain wine can't create prefix using lutris.
It always tries to open wineboot from proton, but i don't even choose it to run.

**Comment by Meister1593** [comment]
Found the issue, thanks to Tarulia (discord), it was issue with global configuration for Wine.
For some reason, it tried using Proton wineboot to create prefix when Proton was defined in global configuration, no matter what was in specific game runner. 
Changing Proton in global configuraiton to other lutris-wine fixed issue.

**Comment by mihawk90** [comment]
@strycore below some information that might be more helpful for you.

After some testing with that user on discord it seems to be clearer now what the exact issue is here, since it is indeed *not* a Proton issue, it is a general issue with how Lutris handles wineboot.

First some steps to reproduce:

0. Start Lutris in debug mode (duh)
1. Set the (global) Wine Runner configuration to some arbitrary value you can easily recognise (for me it was still on TKG-4.6, which is how I noticed it in the logs)
2. `+` -> Add game... -> Runner: Wine, Wine version: some different version then in 1., any arbitrary prefix path
3. Save
4. Sanity check the generated yml file, for me it looks like this:
```
[tarulia@localhost]~% cat /home/tarulia/.config/lutris/games/winetest-plyshka-1598956728.yml
game:
  prefix: ~/Games/winetest-plyshka
system: {}
wine:
  version: lutris-5.7-8-x86_64
```
As you can see the wine version is correctly saved (which you can also confirm via right-click on the "game" and selecting configure).

5. Right-Click game -> Wine configuration
6. Check the Terminal output. You will notice that Lutris is using a different WINE version for wineboot then it is for executing the actual exe. Excerpt (lines 196-199 in the [full log](https://github.com/lutris/lutris/files/5155720/winetest-plyshka.log)):
```
DEBUG    2020-09-01 12:28:05,789 [system.execute:39]:Executing /home/tarulia/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wineboot
DEBUG    2020-09-01 12:28:05,790 [system.execute:45]:WINEARCH=win64 WINEPREFIX=/home/tarulia/Games/winetest-plyshka WINEDLLOVERRIDES=
INFO     2020-09-01 12:28:22,717 [wine.create_prefix:144]:win64 Prefix created in /home/tarulia/Games/winetest-plyshka
DEBUG    2020-09-01 12:28:22,851 [wine.winecfg:374]:winecfg: /home/tarulia/.local/share/lutris/runners/wine/lutris-5.7-8-x86_64/bin/winecfg
```

As you can clearly see it is using wineboot from tkg-4.6 (which was in my runner configuration), but using the winecfg from the (correct) 5.7.8 version.

@Meister1593 has the added issue that his (global) runner configuration was set to a Proton version, which as GE pointed out does not ship with wineboot.

Since I assume this is not by design, I found it worth mentioning :)

**Comment by Meister1593** [comment]
@GloriousEggroll Is this issue is still on? I think this needs separate bug report, seems like a serious bug.
