### ISSUE TITLE
Feature Request: Add support for game categories

### ISSUE THREAD

**Issue by BeatLink** [lutris/lutris#3153]
It would be really cool if games in lutris could be grouped into user created categories like on steam

**Comment by bcedu** [comment]
Hi! I was going to sumbit a new issue but I've seen there is alredy these issue asking for categories. 

Is there any plan to add categories to lutris?

I've also seen that there is a branch (https://github.com/lutris/lutris/pull/1452) that has implemented the categories but it is not integrated with master? Is there any reason?



Thanks!!

**Comment by feltcat** [comment]
It seems that PR #3001, which added support for a "favourites" category and was merged into master, also added backend code to handle arbitrary categories. It seems that the only thing still needed would be UI for managing categories and choosing which category to filter by. Since this issue was added to the 0.5.10 milestone, I'd guess that it's planned to do that, but I can't see if any work has been done on it since then.

**Comment by strycore** [comment]
Implemented in https://github.com/lutris/lutris/pull/4482
