### ISSUE TITLE
Dosbox Config handling in Lutris

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#320]
I've setup Tomb Raider with the following Autoexec section http://pastebin.com/KcfNWncb

ran it from the terminal using ./dosbox and it runs, added it to lutris as the conf file and it doesn't work. Lutris will start the game from :TWO and then when you exit it'll then run :ONE. 

So somewhere Lutris is either not reading the config correctly, or using batch programming like this is a bit beyond what lutris is capable of atm.

**Comment by strycore** [comment]
I guess it was because the script was missing an END label. My version is working fine:

`
[autoexec]
@CLS
@ECHO [42;1mÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
@ECHO º ------------------------------------------ º
@ECHO º Tomb Raider 1                              º
@ECHO º ------------------------------------------ º
@ECHO º  1) Tomb Raider                            º
@ECHO º  2) Tomb Raider: Unfinished Business       º
@ECHO º                                            º
@ECHO º ------------------------------------------ º
@ECHO º  3) exit program                           º
@ECHO º ------------------------------------------ º
@ECHO ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍŒ[0m
@choice /c12345 /s Which game do you want to run? [1-3]: /n
@if errorlevel 3 goto END
@if errorlevel 2 goto TWO
@if errorlevel 1 goto ONE
 
@GOTO END

:ONE
mount c "/home/strider/Games/tomb-raider-i"
mount d "/media/strider/TR1"
c:
cd TOMBRAID
cls
tomb.exe
GOTO END

:TWO
mount c "/home/strider/Games/tomb-raider-i"
mount d "/media/strider/TRGOLD"
c:
cd TOMBRAID
cls
TOMBUB.EXE
GOTO END

:END
@ECHO Exit
`
