### ISSUE TITLE
add default icon for games without icon when creating desktop shortcut

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#3205]
**Describe the bug**

Creating desktop shortcut for game without icon results in shortcut without icon.
Sample game https://lutris.net/games/sonic-classic-heroes/

**Steps to reproduce**

- Install lutris from ppa on KDE.
- Install game https://lutris.net/games/sonic-classic-heroes/
- Create desktop shortcut.

**Lutris debugging output (Optional)**

[lutris.zip](https://github.com/lutris/lutris/files/5385503/lutris.zip)

**System information (Optional)**

[lutris-issue-report.zip](https://github.com/lutris/lutris/files/5385496/lutris-issue-report.zip)

**Screenshots (Optional)**

![image](https://user-images.githubusercontent.com/5204968/96142946-4b75cb80-0f0b-11eb-86c1-5c3a7d848349.png)

**Comment by Capital2** [comment]
The title of the issue and its content are 2 different issues.
Your problem seems to be with the DE's icon theme and not related to lutris:
Replicated the problem on KDE, and the default "Icon not found" icon showed up.
![Screenshot_20220906_201508](https://user-images.githubusercontent.com/46960941/188720061-28fb1d23-35cf-4948-b6e8-a942404c30a3.png)
The title suggests that the aforementioned default DE icon is not wanted and as an example putting the lutris icon as a replacement on icon-less launchers, if that is the case please consider updating the issue.

**Comment by soredake** [comment]
I can't reproduce this with recent KDE, as for setting lutris icon to entries without own icon i will open another FR.
