### ISSUE TITLE
lutris beta: Steam runners show only games installed in steam default home directory

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3248]
Hello Lutris dev Team,
I configured Steam to install my games in two different locations:

a) default Steam location:
/home/romain/.steam/steam/steamapps/common

b) another hard disc:
/mnt/dd2/Steam/steamapps/common

Lutris can find and show only the games I install on default Steam location.

**Comment by Wopfi** [comment]
Maybe my issue is related. But I don't see any Steam games at all. My Steam installation also has two library locations. The default one where I normally don't install anything and the second one, located on my game HD, where I keep all my games.

```
/home/thomas/.local/share/Steam/steamapps
/disks/other_data/steam_library/steamapps
```

And since the update to 0.5.8, Lutris just shows "No games found" when in Sources/Steam. Neither games installed in the first nor in the second location are shown.

**Comment by tetoNidan** [comment]
lutris  --version lutris-0.5.8.3

Maybe related? Manjaro installed from community not AUR. Maybe I should make new ticket?

lutris --list-steam-folders

2021-06-29 20:33:45,596: Your version of python-magic is too old.
2021-06-29 20:33:45,690: Initializing lutris
2021-06-29 20:33:46,592: Downloading DXVK releases to /home/$USER/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-06-29 20:33:46,594: Runtime updated. Initialization complete.
2021-06-29 20:33:46,596: Lutris 0.5.8.3
2021-06-29 20:33:46,597: Using NVIDIA drivers 465.31 for x86_64
2021-06-29 20:33:46,598: GPU: NVIDIA GeForce GTX 1070
2021-06-29 20:33:46,598: GPU: 10DE:1BE1 1043:1660 (nvidia drivers)
/home/$USER/.local/share/Steam/steamapps
2021-06-29 20:33:46,798: Shutting down Lutris

should be as I have added a mount point added in steam for external steam library in /media:
/home/$USER/.local/share/Steam/steamapps
/media/Games/SteamGames

**Comment by JoshStrobl** [comment]
I am also getting this with Lutris 0.5.8.4 under Solus. Native package, not a flatpak or any other distribution method. it does not detect my secondary Steam library, but rather solely:

```
/home/joshua/.local/share/Steam/steamapps
/home/joshua/.local/share/Steam/compatibilitytools.d
```

In reality my Steam libraries are:

```
/home/joshua/.local/share/Steam/steamapps
/run/media/joshua/pool/SteamLibrary/steamapps/
```

![image](https://user-images.githubusercontent.com/156574/124509592-f5b7bb00-ddda-11eb-8ef3-127bcc079e50.png)

Hitting the Reload button when hovering over the Steam source does nothing to help. Debug messages when clicking are as follows:

```
DEBUG    2021-07-05 21:44:43,177 [http.get:73]:GET https://lutris.net/api/games/service/steam
DEBUG    2021-07-05 21:44:44,895 [steam.load:114]:159 Steam games loaded
```

**Screenshot of Lutris**

![image](https://user-images.githubusercontent.com/156574/124509275-55619680-ddda-11eb-91f7-47c727a7a2fb.png)

**Screenshot of Steam install list**

![image](https://user-images.githubusercontent.com/156574/124509336-6f9b7480-ddda-11eb-8970-eee08cc61818.png)

I would like to note that Civilization V and VI only are in the screenshot because I clicked to add / install them via Lutris, but cancelled since it wasn't letting me actually choose the existing install location for it (was trying to see if it was picking it up). It is not the result of anything automatic on the side of Lutris.

Elite Dangerous is the only application on that list which is installed from Steam and residing in the local Steam library. Battle.Net, Elder Scrolls Online, and World of Warcraft are all using the WINE runner.

**Comment by tetoNidan** [comment]
I have no clue if this will help at all but i made a quick finder. Only tested on my machine. 

```python
#!/usr/bin/env python3
""" A file to find all steam proton game folders."""
from os import walk, listdir
from os.path import expanduser, join as oJoin, split as oSplit
from pathlib import Path

def find_steam_paths():
    """Finds and returns any possible steam paths. Searches from root down. """

    steam_games = [] ## list of found steam games folders.

    steam_list = ('steamapps', 'compatdata') ## mandatory steam file sequence

    finger_print = {'pfx': ['dosdevices', 'drive_c'], ## our basic steam folder
                    'dosdevices': ['z:', 'c:']} ## identification dict

    for path_, _, _ in walk(expanduser('/')): ## loop through root
        path_list = Path(path_).parts ## split our cwd into a set

        ## so we are looking to be in a pfx dir, we need to do a bit of slice
        ## magic to make sure we're indeed inside a likely steam game prefix.
        if len(path_list) > 2 and path_list[-4:-2] == steam_list:
            finger = {} ## dict we will use to test against finger_print later

            i = 0  ## walk iteration control variable.
            for pth, dir_, _ in walk(path_): ## walk through only our path

                if oSplit(pth)[1] != 'drive_c': ## ignore drive_c for now
                    finger[oSplit(pth)[1]] = dir_  ## add the directory's dict

                if i > 1: ## we don't want to go to far
                    break  ## we've gone to far, exit our path walk

                i += 1 ## look further into our path walk

            if finger == finger_print: ## our known steam fingerprints match
                ## list our users directory in drive_c
                search_dir = listdir(oJoin(path_, 'drive_c', 'users'))

                if 'steamuser' in search_dir: ## we have a steamuser in users
                    ## get our steam folder location
                    steam_folder = oJoin(*path_list[:-4])

                    if steam_folder not in steam_games:
                        ## our known game folders does not have this entry
                        steam_games.append(steam_folder) ## add entry

    ## return a list of games if found. Empty list on failure.
    return steam_games

if __name__ == '__main__':
    print('\n'.join(find_steam_paths()))


```

**Comment by hellmind** [comment]
How can we set steam library path manually? 
Cant be done editing some config files?

**Comment by SanAndreaP** [comment]
After looking around in source and in steam files I think I figured it out (for Flatpak Steam):

Lutris looks inside the `~/.var/app/com.valvesoftware.Steam/data/steam` directory ([lutris/config.py](https://github.com/lutris/lutris/blob/master/lutris/util/steam/config.py#L19)), but on my installation Steam creates the directory as follows: `~/.var/app/com.valvesoftware.Steam/.local/share/Steam/`

I'm not sure why it is there in the first place, maybe there's something misconfigured on my part, as there seems to be another symlink within the com.valvesoftware.Steam folder named 'data', pointing to the `.local/share` folder mentioned above.

Regardless, I just created a symlink from the .var path to the local user path with:
```bash
sudo ln -s ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/ ~/.local/share/Steam
```
and it works.

**Comment by strycore** [comment]
I added ~/.var/app/com.valvesoftware.Steam/data/Steam to the supported paths.
