### ISSUE TITLE
force $HOME to gamedir

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#329]
the most online games require to download additional data that will be stored in ~/.local/... so the best option would be to force  $HOME and $XDG_USER_HOME to the  $GAMEDIR

its also better for all games since it makes the whole gamefolder portable

**Comment by RobLoach** [comment]
Good idea.

**Comment by strycore** [comment]
I don't thing that would work consistently. Sure it would for those games that use the environment variables, but I'm pretty sure most of them don't.

We can start experimenting on that subject and see how that works but I doubt it will become a default setting.

Do you have a few examples of games that download their content to ~/.local/share?

Also keep in mind that Lutris will soon have savegame syncing so we will keep track of where save files / config files are located. This is of course a different matter since you're talking about games that download their files to ~/.local/share.

**Comment by RobLoach** [comment]
> Do you have a few examples of games that download their content to ~/.local/share?

- CaveStory+
- FEZ
- SteamWorld Heist

**Comment by sixsixfive** [comment]
* almost any game puts their config and save files in ~/.<gamename> or ~./config/<gamename> 
* many wine games use C:/users/<user>/My Games or Documents
* every emulator uses its on config ~./pcsxr
* it also prevents the broken winemenubuilder from breaking your mimetypes / apps

also I used this in the past very often since i want may games portable(for the use with emulatorstation: http://www.emulationstation.org/), exporting the HOME var works almost any time, XDG vars doesnt work much often since freedesktop is a GNOME driven organization

**Comment by strycore** [comment]
Ok, I was thinking about games that download actual game data (maps, models) in ~/.local/share, if it's config files and saves that's a bit different.

However, I find the idea interesting and I'd like to play around with it a bit. I'll add a system option for that so it can be enabled for all games if wanted. However, it's very unlikely that this will become the default setting, since it will break pretty much every game installed in the past.

One good thing about this is that it would solve the problem with games putting their files at the root of the home folder (assuming they use standard environment variables).

Unrelated note, could you give more details about the winemenubuilder issue, maybe in a separate ticket?
I keep seeing that you disable it in your installers and I don't think that's the right place to do it. If there is a problem that affects Wine games globally then Lutris should, by default, do the right thing.

**Comment by Xodetaetl** [comment]
> However, it's very unlikely that this will become the default setting, since it will break pretty much every game installed in the past.

We can set every existing game to false with a migration when we add the option.

**Comment by strycore** [comment]
This is quite a big change, I'm all for adding the option but we will need to test it for a few months before making any decision regarding setting this as the default behavior.

**Comment by buckshee** [comment]
How about an 2nd Linux runner that automatically sets HOME to game directory?

**Comment by strycore** [comment]
> How about an vHOME Linux runner that automatically sets HOME to game directory?

lol, no.

This will be a system option.
