### ISSUE TITLE
Bring back the ability to remove games without deleting their files

### ISSUE THREAD

**Issue by hazelnot** [lutris/lutris#3313]
While it kinda makes sense why this change was made, this creates some issues such as being unable to update [certain installers](https://github.com/rockerbacon/lutris-skyrimse-installers).

**Comment by DoktorSeven** [comment]
It also removes ALL files in that directory, so if you are pointing a game to a certain file with other files in it (such as an emulator pointing to a ROM/disk file), removing that game will delete EVERY ROM/disk file in that directory.  It's a terrible change and I was forced to downgrade to 0.5.7.1 until they fix this problem because I did not want to accidentally delete a directory full of things I want to keep.

**Comment by byte1024** [comment]
Maybe its just not re-implemented yet.

> It also removes ALL files in that directory, so if you are manually pointing a game to a certain file with other files in it (such as an emulator pointing to a ROM/disk file), removing that game will delete EVERY ROM/disk file in that directory. It's a terrible change and I was forced to downgrade to 0.5.7.1 until they fix this problem because I did not want to accidentally delete a directory full of things I want to keep.

Do yourself a favor and back those things up tomorrow lol. You won't be sweating so much.
