### ISSUE TITLE
Use case-folding for alphabetical sorting

### ISSUE THREAD

**Issue by solbero** [lutris/lutris#3378]
**Describe the bug**

Games starting with lower case letters will be sorted after games with capital letters when sorting alphabetically in the Lutris interface.

For the large majority of games this is not a problem, since they start with a capital letter. However, there are some games such as [ibb & obb](https://ibbandobb.com/) which are stylised in lower case.

**Steps to reproduce**

1. Add a game entry that starts with a lower case letter
2. Sort the game list alphabetically
3. Games that start with lower case letters will be sorted after all games that start with capital letters

**Screenshots (Optional)**

<img src="https://user-images.githubusercontent.com/7732292/105612081-ca578b80-5db9-11eb-8700-95848c94c9d2.png" width="400">

**Comment by strycore** [comment]
I hope there's a way to apply a `lower()` to the name column for sorting, without having to create another column just for that purpose like we do for playtime.

**Comment by solbero** [comment]
I tried to look at the code and figure out where the sorting is done for the views. Is the sorting done when the entries are are fetched from the database, or further downstream? If it is done later it could be possible to use the Python built-in function `sorted()`with the `key=str.casefold`, e.g. `sorted(unsorted_list, key=str.casefold)`.

Any pointer to where to look in the code would be appreciated, and I’ll see if I can submit possible solution.

**Comment by strycore** [comment]
I think this problem is caused by the fact that I moved a bunch of sorting and filtering from the Gtk view to database queries. 
There is a sort_func in store.py that is only applied on the list view. I haven't spent a lot of time on the listview and mostly refactored the grid view so there might have been some oversight here.
There might be a simple way to fix this at the database level without having to deal with the whole mess in the sort function in the Gtk views.
I kinda want to re-introduce Gtk based sorting but doing so in a much more careful manner than what we once did. There is at least some cleanup to do to either replace the sort_func in store.py with something else or apply it as well on the GridView.

**Comment by strycore** [comment]
Thanks for the fix!
