### ISSUE TITLE
Add runner icon overlay on duplicated banners

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#341]
the current duplication makes it very hard to determine which version I launch.

![screen](https://cloud.githubusercontent.com/assets/3780774/18211611/cd12647e-713e-11e6-9893-7212b2b99f7e.png)

Why not ask the user? 

eg: if more than one version is installed display only one banner/icon and launch a dialog that asks the user which version should be launched.

**Comment by RobLoach** [comment]
Perhaps append the version to the end of each title?

**Comment by strycore** [comment]
We're going to add runner icon overlays on duplicated games.

**Comment by strycore** [comment]
In the case of multiple instances of the same game using the same runner, the installer version will be appended to the name

**Comment by sixsixfive** [comment]
so if i have a game installed with 20 dlc's i will have 21 game banners?

**Comment by Xodetaetl** [comment]
@sixsixfive : No, DLCs / mods / patches are added to an existing installation of a game.

**Comment by sixsixfive** [comment]
hm i have currently two men of war banners, one for the game and one for the special edition upgrade(which just launchers the base game). 

this currently happens with all content patches(eg i could install freespace2 and create an installer for every fan made mission pack/campaign(currently 106 http://www.freespacemods.net/e107_plugins/download/download.php?action=list&id=6 ) all of them would have the same game banner and all of them would launch the same binary(without args)

**Comment by strycore** [comment]
We do have something missing regarding mods and DLCs. Sometimes a game entry should not be added to the client, because the executable is still the same and the mod is used from within the game.

Currently we install mods with the `requires: {installer}` directive but I think we should also add the `extends: {installer}` directive for such cases.

If an extension or mod is radically different from the base game, it should probably deserve its own entry and banner (see Quake 1 and 2 extensions).

**Comment by AccountOneOff** [comment]
This can be closed merged with #220 can't it?
