### ISSUE TITLE
Lutris initializes very slow and often glitches on POP_OS!

### ISSUE THREAD

**Issue by Nekspire** [lutris/lutris#3411]
**Describe the bug**

Hi there, i've found a problem with Lutris behavior on my new installed POP_OS!. It initializes always very slow, approximately
2 minutes every time when is launched. Additionally when i try to do something, for example search Lutris.net for games it's lagging and forcing to the quit application.

Please tell me, what might be the problem? 

This repository isn't for reporting game bugs or game related issues. Feel free to contact us on [Discord](https://discordapp.com/invite/Pnt5CuY), the [Forums](https://forums.lutris.net), or the IRC channel #lutris on freenode.org for that. We'll try and help as best we can.

**Steps to reproduce**

- 
-
-

**Lutris debugging output (Optional)**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information (Optional)**

![image](https://user-images.githubusercontent.com/71459567/107028834-62884400-67ae-11eb-8203-5b3627cd4d67.png)

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/71459567/107029091-c4e14480-67ae-11eb-8c49-b05f03a4cede.png)
![image](https://user-images.githubusercontent.com/71459567/107029156-de828c00-67ae-11eb-8a54-82e17aae04c4.png)

If your issue is hard to explain with words, feel free to attach screenshots.

**Comment by strycore** [comment]
You know that I can't do anything at all with this information, right?

**Comment by strycore** [comment]
I think your computer is broken.

**Comment by strycore** [comment]
Too incomplete to be a work item. The slowdowns should get sorted out eventually, at least I hope. Closing.

**Comment by romahicks** [comment]
Trying forcing traffic through IPv4. This could possibly just be Lutris/OS attempting to use a IPv6 connection if it is not setup correctly, once the connection times-out it attempts IPv4.

I weirdly had this issue last night on Fedora and viewed this issue. I had very similar symptoms. Turned out it was my ISP; my ISP has some support for IPv6, I have a IPv6 connection but it is just to a IPv4 DNS (or something like that, not sure the exact details). But it broke the network connections to my FreeBSD server and Linux computers over the last month, and I had just reinstalled Lutris recently, so I hadn't noticed until now.

**Comment by strycore** [comment]
We're not forcing anything on Lutris' side. All downloads are either using `requests` or Python's own `urllib.
Maybe a way to troubleshoot would be to download some arbitrary files using Lutris' code on your ISP, this is not something I can do.
However, using a python shell or a small script, it's quite easy to test.
