### ISSUE TITLE
Installed games not auto being picked up on Lutris & feature request to be re added

### ISSUE THREAD

**Issue by coreybruce** [lutris/lutris#3413]
**Describe the bug**
Installed games do not show up in my games category and also why is there no import button anymore? I don't wish to go through my already installed games and "installing" one at a time just so they show up

For example here is Lutris, it shows I have no games and no games installed

![alt text](https://i.imgur.com/LOhsIBI.png) 

![alt text](https://i.imgur.com/aADrwcn.png) 

But if you look on Steam for example I have right now a couple games installed and can/will install more but they won't show up and I have no way to easily import them anymore since you removed the import button

![alt text](https://i.imgur.com/AZiUaUZ.png) 

Also native Linux games installed from your package manager do not show up at all and again I have no way to import them.. 

As a example I installed SuperTux and it does not show up

![image](https://user-images.githubusercontent.com/8393780/107170166-65cc3b80-6a0b-11eb-8107-1ad05e14da53.png)

![image](https://user-images.githubusercontent.com/8393780/107170199-78df0b80-6a0b-11eb-95bf-e38bf6633aed.png)

Here is a log of it starting up but as you can see while ignoring Mangohud messages it's fine
```
Unable to load locale dir, translations won't work.
2021-02-08 12:37:25,148: Your version of python-magic is too old.
2021-02-08 12:37:25,281: Initializing lutris
2021-02-08 12:37:26,812: Runtime up-to-date. Initialization complete.
INFO     2021-02-08 12:37:26,820 [application.do_command_line:314]:Lutris 0.5.8.1
INFO     2021-02-08 12:37:26,820 [startup.check_driver:49]:Using NVIDIA drivers 460.32.03 for x86_64
INFO     2021-02-08 12:37:26,820 [startup.check_driver:53]:GPU: GeForce GTX 1060 6GB
INFO     2021-02-08 12:37:26,820 [startup.check_driver:69]:GPU: 10DE:1C03 10DE:11D7 (nvidia drivers)
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/corey/.config/MangoHud/python3.9.conf [ not found ]
parsing config: /home/corey/.config/MangoHud/MangoHud.conf [ ok ]
```

**Comment by strycore** [comment]
You need to make a $5000 donation to Lutris to make me acknowledge this ticket.

**Comment by coreybruce** [comment]
lmfao this is a joke right? why would I need to donate  a large ridiculous sum of money to have a bug "acknowledged"? it's a bug that I am nice enough to report with the addition of user input because I want to help improve this project. I'm sorry but this is sounding very arrogant and rude.

**Comment by coreybruce** [comment]
All jokes aside tho I really wish to help fix this bug :P

**Comment by RossComputerGuy** [comment]
I'd like to see this issue fixed. I want that import button again.

**Comment by coreybruce** [comment]
Just a tip tho, no one is going to want to donate to a free and a open source project that doesn't fix bugs and than turns around asking for thousands of dollars  to fix a single bug..

**Comment by RossComputerGuy** [comment]
Exactly, this is worse because @strycore is a member of Lutris. They're basically asking to be  paid for a free and open project, completely the opposite of what FOSS is supposed to be. This kind of behavior should not be acceptable. Even if it's a joke, there's no way to tell.

**Comment by Shished** [comment]
This is not a bug. Import function was removed few versions ago. Check out change logs.

**Comment by coreybruce** [comment]
@Shished it's a bad decision to remove because now I can't auto manage my games like I use to and  have it easily imported into Lutris, isn't that the point of Lutris after all?

**Comment by RossComputerGuy** [comment]
But this issue is asking for it back, I'm sure many users besides the ones here want it back.

**Comment by coreybruce** [comment]
Exactly especially when it removes the ability to easily have your games show up if they do at all which non steam games don't at all..

**Comment by Shished** [comment]
I can't tell why did they made this. Maybe they weren't satisfied with how it was implemented, maybe it was hard to maintain, maybe something got broken in it.

**Comment by coreybruce** [comment]
Not sure but it working perfectly fine but now it's basically broke Lutris and I have to manually add my games which is annoying

**Comment by RossComputerGuy** [comment]
Idk as well, last time I tried it, it was just fine.

**Comment by Shished** [comment]
I nobody wants to pay devs to maintain some specific feature then you can fork the last version with it and maintain it yourself, for free.

**Comment by RossComputerGuy** [comment]
Yeah, I don't have time but if someone else wants to do that then good. I highly suggest doing it.

**Comment by coreybruce** [comment]
ok but without the feature whats the point of Lutris than? yes it can easily add and install non native games with a click of a button and what helped it take off but the other main use that people also really loved about Lutris was how it managed your games from different places like GOG, and Humble Bundle as well as non steam games installed on your Linux OS and easily being able to import all those games in a click of a button making it far less convenient when it was working just fine with the feature

**Comment by ctaetcsh** [comment]
I am in agreement with @coreybruce and @RossComputerGuy. It seems weird that this was removed, since it would make sense for Lutris to be a jumping point for your game library. Perhaps this could be solved with a different game manager?
On the topic of the first reply, even if it is a joke that's pretty distasteful on an Open Source project. At least add an `/s` if you're kidding.

**Comment by coreybruce** [comment]
lmao  
>imagine thinking that down voting or hearting comments against the developers behaviour is going to change reality that this isn't okay 

The fact is anyone is free to donate and help support this and that's great but no one should have to pay $5000 or even a high amount jokingly to have a look at a simple ticket.. If you are struggling than don't take it out on your community and act greedy, ask for help or reach out to other open source projects or community's for assistance.

**Comment by gardotd426** [comment]
> Exactly, this is worse because @strycore is a member of Lutris. They're basically asking to be paid for a free and open project, completely the opposite of what FOSS is supposed to be. This kind of behavior should not be acceptable. Even if it's a joke, there's no way to tell.

Um... No. 

FOSS doesn't remotely mean "free as in beer." At all. If anyone doesn't know what FOSS is "supposed" to be, it's you. 

>it's a bug that I am nice enough to report

Lmao you sound like a "nice guy" who expects any girl you're nice to to become your girlfriend. 

Fellas, people have to survive. Lutris is a rather large project, and has completely changed the Linux gaming ecosystem. Not to mention the fact that the 5000 dollar comment was clearly a joke, and you're acting like idiots. 

This also isn't a discussion forum. This thread has been closed. Take this nonsense to reddit.

**Comment by coreybruce** [comment]
No your right it doesn't but no one needs to pay a sum of money to have a bug you report looked at or simply asking for a feature re added, this is continuing because of this bad behaviour @gardotd426

Like I said anyone can freely donate or support the project but this isn't the way to go about it..

**Comment by coreybruce** [comment]
Also what was even the reason the feature was removed?

**Comment by rndmh3ro** [comment]
@coreybruce you better stop posting here now.

**Comment by strycore** [comment]
Ok so there is a lot of confusion on this ticket so I think some things need to be cleared up.

Here's how the old "import" was working: we would connect to GOG or any other service then make a request to the lutris website to get all games that we have on lutris.net. This resulted in many games being not available as they didn't have an installer or an entry in our database.

Here's how lutris works now: we have all supported services accessible directly from the sidebar. You connect to GOG or Humble and all the games are listed. They are all installable because the client will create a default installer script if one isn't present on the website. All games installed from services like GOG, Humble or Steam are added to the lutris library.

Now there are 2 big changes that are the subject of the bug report here. We disabled the "local games" service (or XDG) because it wasn't deemed stable enough. It's still here, it's just disabled. It will be re-enabled in the next release.
The other change is that instead of scanning installed Steam games which takes a long time, we now use what we used for the steam sync on the website and fetch the Steam library directly from the Steam API, meaning that we get the full game library instead of what's available.
Lutris 0.5.9 is supposed to be mainly about Steam and the improvement of services. There will be a service selection widget in the Preferences that will allow to enable/disable services. There are many more services planned like Battle.net, EGS, MAME, ...so we don't want to show everything. There will also be options for the services like the default install path. (It's now hardcoded, GOG games are installed in Games/gog/)

Lastly, I do not need $5k. It was a joke about how open source developers are not paid really well. But I'm only part-time an open source dev so I'm doing ok. I appreciate donations to the project but having some project managers or UX designers give their take on the project would be much more valuable at that point.

**Comment by coreybruce** [comment]
Thank you for the update

**Comment by strycore** [comment]
Also, every open source developer should get paid as much if not more than developers working on closed source projects. Google wants to have better scrutiny on open source projects? Then pay up! It is not up to the common users to pay. It is up to the corporations who use the software. Lutris is a special product because it's not needed by any company in the industry so it relies solely on donations. But many others projects are vital for the functioning of our whole digital ecosystems. And they get used by other companies. You just have to see what happened between ElasticSearch and AWS recently. 
The open source model has been abused. Everything has been done to maximize profitability. So you have tons of iOS and Electron app developers but very little who care about a Python/GTK combo... 
I get that I'm a little spiky sometimes, but I do what I feel is right to keep the project in the right direction. I'm still not convinced this was a bad take from me, despite having written it while still in bed, just sorting through some emails. I could have taken a few more minutes to write a "nicer" response that would have resulted in an "ok. then...". Or I can write a silly one-liner that can lead to more interesting discussion. If anything, I'll come up with something less lazy than "gimme $5k!" next time. Given it is a video game project outside of any rules, then *any* rule could apply.

**Comment by RossComputerGuy** [comment]
I understand. I'm sorry that I caused this to blow up. I didn't realize it was a joke. Sometimes my understanding of communication isn't the best. I just wanted to know why the feature was removed. I didn't have any intentions of causing any backlash. I agree that FOSS devs should get payment but I don't think they're entitled to it. They deserve it if they make something good like Firefox, Lutris, or Vim. I realize that what you were doing isn't demanding for money and I'm sorry. I hope that people will let this issue die into obscurity.
