### ISSUE TITLE
Remove games from library option missing

### ISSUE THREAD

**Issue by shanks3042** [lutris/lutris#3416]
Since the new UI update it is not possible anymore to remove games from the library. It is only possible to hide certain entries but this is not very useful.
Please re-add the option to completely remove games as in the old UI. It feels like a big downgrade to the old one.
Also in the old UI we had the option to remove the folder with the game. Now that has to be done manually.
If there is a way to switch to the old UI that would be also fine for me.

**Comment by CoreyVincent** [comment]
+1 I agree 100% with this. Very annoying that I can't remove items from my library list. I created an item accidentally and now I just have this random item in my dashboard...

**Comment by CoreyVincent** [comment]
Figured out how to remove them manually.

Navigate to:
`/home/<your_username>/.local/share/lutris`

You will find a database file in this director called `pga.db`.
Open the database file with any database manager(dbeaver, DB Browser for SQLite...).
Open the database, expand the `tables`, then select the "games" table.
Inside you will see something like this:
![Database Entries](https://user-images.githubusercontent.com/11997743/107859642-b9be9200-6e08-11eb-8f2d-d602c8bcc7dd.png)
You should see all the games you've imported.
Find the one/s you would like to remove and delete their rows from the table. And save the changes to the table.
![Screenshot from 2021-02-13 14-27-22](https://user-images.githubusercontent.com/11997743/107859680-14f08480-6e09-11eb-89ae-3cc98e3f8d3d.png)
After you should see that your lutris game list is now clean of that unwanted clutter.
![Screenshot from 2021-02-13 14-28-27](https://user-images.githubusercontent.com/11997743/107859708-4d905e00-6e09-11eb-917b-d51dc7b85616.png)

Hopefully, others find this helpful until this can just be done in the application.

**Comment by strycore** [comment]
We don't remove games from the local database anymore because I want to find a way to keep playtimes between game installs.
For that we need to have some kind of upstream sync with the lutris.net website so we can safely delete. 

Removing games by directly interacting with the best solution at the moment. In the next release, there will be a cleanup command line flag to clear all uninstalled games from the database. And once upstream sync is implemented we can just delete the games from the database without worrying about keeping any data.

**Comment by eridal** [comment]
@strycore thanks for the context. I was a bit surprised that this option was removed and that using sqlite was required.

Anyways I think it should be possible to remove games, specially for those games that we haven't even got to install.. and I mean literally. I ended here because I used lutris to install an empty prefix and long story short, I was unable to install .. so the prefix was empty :)

I hope that refactor you mention allows to decouple the game from its usage stats, so that way you can keep playtimes while also allowing to remove them. Bonus: simpler re-installation flow? :wink:

**Comment by strycore** [comment]
I've made it possible to remove games completely again while still keeping uninstalled games for their playtime. 
To achieve that, I've removed the "Hide game" option on uninstalled games and replaced it with the "Remove" action.
Removing an uninstalled game completely removes it from the database.
Might still add a command line flag to clear out all uninstalled games.
