### ISSUE TITLE
[Feature request] Adding flatpak runner support

### ISSUE THREAD

**Issue by LanaKirisame** [lutris/lutris#3509]
It's probably already been asked for somewhere else but i didn't see it here so :

Flatpak has become the closest thing to a standard to distribute emulators on Linux, so far I've seen Desmume, Retroarch and Citra recommending and redirecting their users to a flathub page or straight up downloading a .flatpaktref. ( https://desmume.org/download/ , https://www.retroarch.com/?page=platforms and https://citra-emu.org/download/ ).

Having runners installed via Flatpak would solve problem relative to updates, system integration and missing library.
A good example would be Citra : when downloaded trough Lutris it cannot be launched until you install QT5 library which aren't here by default on GTK based desktop.

There are downsides to this approach :
While Gamemode has received an update to work within a Flatpak, running : 
`gamemoderun /usr/bin/flatpak run org.citra_emu.citra` will result into : `ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
There is also the need to have a working Flatpak installation on the system. A way to address this would be to add Flatpak as a dependency and to enable Flathub when downloading a Flatpak runner.

For now I'm using a small bash script like this one :
```
#!/bin/bash
flatpak run org.citra_emu.citra "$@"
```

**Comment by tazihad** [comment]
it's in beta https://github.com/flathub/net.lutris.Lutris

**Comment by LanaKirisame** [comment]
> it's in beta https://github.com/flathub/net.lutris.Lutris

I think you misread something, what this feature request ask is not lutris to be packaged in flatpak form but to allow lutris to use flatpak runner. For exemple even when using lutris flatpak if you download Citra trough the runner section it will fetch an ( outdated ) package and there is no easy option to use the up to date flatpak one.

**Comment by A6GibKm** [comment]
Note that you can't  just run `flatpak run org.citra_emu.citra "$@"` from inside a sandbox (which affects the Lutris Flatpak). To be more precise you can, but requires adding a sandbox hole that renders sandboxing useless.

**Comment by strycore** [comment]
We now have support for Flatpak runners but some adjustments will be needed in individual runners.

The process is really simple:

1. Specify a flatpak_id on the runner (like org.citra_emu.citra)
2. Make sure `get_executable` isn't used in the runner code. Use `get_command` instead. `get_executable` will return a string like `/usr/bin/citra` while `get_command` will return a list like `["/usr/bin/citra"]` or `["flatpak", "run", "org.citra_emu.citra"]`

That's it, the runner now supports Flatpak!

> requires adding a sandbox hole that renders sandboxing useless

I guess that now that Lutris is able to talk with the Flatpak API and use `flatpak-spawn --host` the sandboxing is useless. I don't believe that sandboxing Lutris, a program that orchestrates other programs, was ever desirable or even needed.

**Comment by strycore** [comment]
>There are downsides to this approach :
While Gamemode has received an update to work within a Flatpak, running :
gamemoderun /usr/bin/flatpak run org.citra_emu.citra will result into : ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

Right, I ran into this issue when adding Flatpak support for Steam, which resulted in me disabling gamemode by default for the Steam runner.

We might have to add something to disable gamemode whenever a Flatpak runner is used.

**Comment by QmwJlHuSg9pa** [comment]
On first-run, runners that support `flatpak_id` do not give the user a choice of installing a preferred runner (Flatpak vs. internal download). The user must somehow _know_ to install the _correct_ Flatpak runner ahead of time, in order for it to be utilised.

E.g. the DOSBox runner script specifies `flatpak_id: io.github.dosbox-staging`, but there are other DOSBox variants available via Flathub. The Lutris GUI at no point indicates that the DOSBox runner supports _a_ Flatpak app, not does it specify _which_ Flatpak app it supports.

Likewise, perhaps the "version manager" dialogue boxes for each applicable runner should support selecting the specified Flatpak app (rather than offering only internal downloads)?

E.g. Currently, the pressing the "version manager" button for DOSBox always downloads the latest internal version of DOSBOX-Staging, which results in the Flatpak app always being ignored, even if its already installed.
