### ISSUE TITLE
Add DPI manager to the Wine Runner

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3617]
By default, Wine uses DPI of 96, which makes all GUI programs look incredibly small on a 4K screen, even when scaling is enabled in the DE.
While the user may choose to change the DPI themselves in Wine Configuration to remedy that, automating this in Lutris should be relatively easy.
Lutris simply needs to get DPI data from somewhere (at least on X11, this can be done with `xrdb -query | grep dpi`), convert it to hex (192 DPI, 2x scaling on a 4K screen, is `000000c0`, while default, 96 DPI, is `00000060`), and specify it in Wine's registry by setting `"LogPixels"` DWORD variables located in `[Software\\Wine\\Fonts]` and `[Control Panel\\Desktop]` to the according value in the format of `"LogPixels"=dword:000000c0`.
For example:
```
[Control Panel\\Desktop]
"LogPixels"=dword:000000c0
```
```
[Software\\Wine\\Fonts]
"LogPixels"=dword:000000c0
```
Specifying these will set DPI to 192.

**Comment by Somnius** [comment]
Does this oneline script work
`wine reg add "HKEY_CURRENT_USER\Control Panel\Desktop" /v LogPixels /t REG_DWORD /d 0x60 /f`
or maybe suggestion on changing the value for 192 dpi screens?

**Comment by danieljohnson2** [comment]
I've made an attempt at this, but I'm not sure its good enough.

* This overwrites WINE's setting unconditionally, so you can't configure this the old way anymore
* Fractional scaling is pretty dicey in the games I've tried.

The thing is, there's no way to tell WINE to autodetect the DPI. I have to do it. WINE can't tell the difference between "user set to 96 dpi", "scaling is off, 96 dpi is the default dpi" and "autodetected 96 dpi". It's just 96.

**Comment by tannisroot** [comment]
> This overwrites WINE's setting unconditionally, so you can't configure this the old way anymore
This is ok, just provide an option to disable the functionality.
> The thing is, there's no way to tell WINE to autodetect the DPI. I have to do it. 
Well yes, Wine can't autodetect DPI, Lutris needs to calculate it on its own and set it in the registry.
> Fractional scaling is pretty dicey in the games I've tried.
I don't think this should affect games at all, which ones did you test?

**Comment by danieljohnson2** [comment]
Well, the reason it sets the DPI even when turned off is because the WINE registry retains the last setting. So, if the user does not like the result of setting DPI, he can turn it off and this code resets it to a "safe" setting (96 dpi). If turning it off did not do this, the previous setting would still be in effect. I figured that was bad.

Fractional scaling  (in GNOME) works by using a 2x scale for rendering the UI, then scaling the resulting windows down as bitmaps. It's the Apple style of HiDPI, not the Microsoft style.

I tested fractional scaling with "Deus Ex: Mankind Divided", "Hard Reset Redux" and "Nuclear Throne".

Mostly, they render fine but the mouse does not work- it seems like the mouse position is not getting through properly. But "Nuclear Throne" also wound up rendering partially off-screen.

OTOH, the Deus EX launcher window scaled just swell this way and worked correctly.

I don't think this is caused by the DPI setting I frobbed- even without it, fractional scaling breaks stuff in WINE much the same.

It's possible this would all work better on KDE, which I believe does fractional scaling in the Microsoft way- expecting the applications to scale by 125% or whatnot. Windows programs are supposed to be able to do that.
