### ISSUE TITLE
About Mednafen

### ISSUE THREAD

**Issue by Ammako** [lutris/lutris#3624]
1: Mednafen runner is quite outdated, it downloads 1.24.0-UNSTABLE which is at least a year and a half old by now. 1.27.1 stable is out since last June. Might there be a way to fetch newer versions when available?

2: Can't select system version for Mednafen runner, it just uses the one that Lutris downloads. You can of course create a symlink and use that, but according to #347 this is probably supposed to be available as a GUI option.

3: I think Lutris has a lot of potential to be a great frontend for Mednafen, as an alternative/replacement to Mednaffe. Is there any chance additional configuration options could be implemented? Most particularly, controller (and hotkey?) configuration would be very beneficial to have. The current toggle to "Use default Mednafen controller configuration" doesn't do much for me.

**Comment by strycore** [comment]
I uploaded a build of the latest version of mednafen, lutris will now download 1.27.1
Also added back the runner configure button to always be displayed.

The mednafen runner hasn't received much attention lately because it's also available from retroarch with an easier way to configure controls. In Lutris 0.6.0, I'd like to have a controller customization tool, it would be nice to have it available for all our runners including mednafen
