### ISSUE TITLE
Lutris always using konsole even after choosing another

### ISSUE THREAD

**Issue by Latrolage** [lutris/lutris#3689]
How can I get lutris to not use konsole by default? I want it to use another terminal emulator, I changed the terminal emulator in the overall system options but /usr/bin/konsole still has (default) next to it and whenever I click "open Bash terminal" it opens in konsole.

**Comment by danieljohnson2** [comment]
I've look at this, and I do not think this is a bug.

Lutris prefers to use the setting in the "Text based games emulator" setting, found in the global options. If this is missing falls back to linux.get_default_terminal(). You say using this later function fixes the problem.

But that function provides the default anyway, so I wonder if you've perhaps set "Text based games emulator" to something odd?

Absent that, I would think your proposed change would break "Text based games emulator" but otherwise not change anything.
