### ISSUE TITLE
[WINE] lutris overrides winecfg configs

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#373]
https://drive.google.com/file/d/0B_2_dsXrefR-M0hiNkdtTWZUMEk/view?usp=sharing

**Comment by strycore** [comment]
Well that's the whole point, if you want to set the game in windowed mode, you have to do it from the Lutris options.
This allows to use different settings per game while using the same prefix.

**Comment by sixsixfive** [comment]
sorry but this is confusing 

lutris should either read/modify wines registry or use winetricks to change that(synchronize its settings with wine)

**Comment by strycore** [comment]
I'm thinking about writing a read/write parser for the Wine registry. This would be much faster than having to launch Wine for each registry modification. With that in place we could in theory sync the lutris config with the registry but if I did that, it would mean that we would have to create a separate Wine prefix per wine game (keep in mind that Wine prefixes are often much larger than the game itself).

winecfg is made available because every option isn't available from lutris itself, if we want to keep this feature of using the same prefix for different games, we should implement every winecfg option into lutris and make winecfg unavailable from the contextual menu.

Do you see any other option?

**Comment by sixsixfive** [comment]
thats a good idea, however you don't need to do this the most settings can be changed with winetricks(winetricks settings list)

**Comment by sixsixfive** [comment]
> it would mean that we would have to create a separate Wine prefix per wine game

this is not the problem:

you could create one prefix for every wine release as reference, and symlink the most the wine files from every gameprefix to this prefix

**Comment by strycore** [comment]
With the new WinePrefixManager it's become clear that Lutris can modify Wine prefixes but a Wine prefix can't modify the Lutris config.
The goal is course to be able to configure everything from Lutris without having to resort to winecfg.
