### ISSUE TITLE
From GOG it turns out to download only versions of games in English

### ISSUE THREAD

**Issue by smotim** [lutris/lutris#3783]
Hi! On gog.com the files for installing games depend on the region that is selected on the site. If I choose Russia and try to download Witcher 3 or Dishonored, the download of game files + files of Russian localization will begin. Apparently Lutris downloads English versions by default, without localization files for my region. If you can add a choice, please do it

**Comment by qdevpl** [comment]
With Witcher it's not as big of a problem, because for this game there are langpacks that can be installed manualy later, but it's bit annoying not be able to pick version for older games, where it already installs with language. Example - Robin Hood: Legend of Sherwood. I don't see any good option to fork script to install other language than English.
