### ISSUE TITLE
Lutris should not download files and write to $HOME just to print its version

### ISSUE THREAD

**Issue by gatl** [lutris/lutris#3793]
If I want to check the version of Lutris, as per the man page, it is quite straightforward:
```
     -v, --version
              Print the version of Lutris and exit
```

But when I tried that (in my multi-user environment), what I got was the downloading of DXVK, DXVK-NVAPI, VKD3D and D3D. I also ended up with files under `$HOME/.local`, `$HOME/.config` and `$HOME/.cache` that I had to delete manually.

It seems to me that Lutris is taking too many liberties when all it needed to do was to print a string and exit, as per the documentation.

**Comment by danieljohnson2** [comment]
Almost all Lutris operations require the creation of these directories  because they access the PGA. But "--version" is the exception, and it's the first option checked, so we can just move the initialization a bit later to address this.

I think it is also undesirable to update the runtimes when doing command-line operations that otherwise would show no GUI; it does not seem necessary and it's bad feng shui to pop windows like that.
