### ISSUE TITLE
Banners and icons aren't displayed in configuration

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3829]
### Bug description

Even though the icon for game exists and is used for desktop shortcuts, and the banner does show up in the library, Lutris does not display them in game configuration menu, in the Game Info tab, instead showing default blanks.

### How to Reproduce

1. Open configuration for a game that has a linked icon the website and a banner
2. Open the Game Info tab
3. See the issue (screenshot attached below)

### Expected behavior

Lutris should display the banner and the icon in the configuration.

### Log output

```shell
Nothing useful there
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.15.2-217-tkg-pds
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 3800X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 495.44
OpenGL Core:     4.6.0 NVIDIA 495.44
OpenGL ES:       OpenGL ES 3.2 NVIDIA 495.44
Vulkan:          Supported
```

### Media (optional)

![Screenshot from 2021-11-18 05-00-42](https://user-images.githubusercontent.com/10602045/142338648-b562cc9b-d525-4acd-a0ac-142e5ee959ec.png)

### Checklist:

- [X] I'm not asking for support with a game, an installer script or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I am seeing this too. It looks like an old 'get_pixbuf_for_game' function- this wants a file path but always gets a slug (or 'game_id' if you like).

The problem is that there's no way to know how to resolve the slug to a path here. It needs to know what kind of media it is- and what service (Lutris, GOG, etc) it is too.

I think this can work if the method is moved to the ServiceMedia class; the configure dialog must provide one, but I think it should always use Lutris banners and icons.

I'm working on a PR.
