### ISSUE TITLE
[Feature Request] add an option to disable game thumbnails

### ISSUE THREAD

**Issue by 07416** [lutris/lutris#3875]
I have a large library and prefer not to download, store on disk and display game thumbnails in Lutris.

**Comment by danieljohnson2** [comment]
What would you see in the UI with this option? Gray rectangles where the thumbnails should be?

**Comment by 07416** [comment]
> What would you see in the UI with this option? Gray rectangles where the thumbnails should be?

That's a decent placeholder, but the space formerly reserved for the images could perhaps be optimized (reduce the dimensions to some degree).

I don't know if Lutris offers a "compact" library UI akin to Steam, from the usability standpoint I find the interface quite good on a high-resolution screen:

![image](https://user-images.githubusercontent.com/14923168/144454545-36d3285c-a1a5-40eb-9a80-a46e256a9b53.png)

**Comment by danieljohnson2** [comment]
Lutris offers a zoom slider (its in one of the drop downs); it's a little bugged right now but if you frob it enough you should get to a view with icons. Put it also in list mode and it's not entirely unlike that.

However, I believe Lutris will still download the banners all the same, as it's not related to what you view.

I think what would be better is if Lutris only downloaded the icons you view, and then being in the icon mode would mean that banners don't download.

**Comment by strycore** [comment]
Buy a bigger hard drive.

**Comment by 07416** [comment]
> Buy a bigger hard drive.

@strycore I'm a wheelchair-bound US citizen without a health insurance, my income is mainly spent on medicine and the mental health care I can afford. Chronic pain can't be cured.

Does the reply represent the entire Lutris project?

**Comment by danieljohnson2** [comment]
@strycore is in charge, but I think maybe he was kidding.

But, I wonder what the issue you are having actually is. Is it disk space usage? Just how big is your ~/.local/share/lutris/banners directory, for instance?

Mine is 9.3MB and contains 1,138 banners. That's not even as much space as one small game, these days.

If yours is actually very large, then something very strange is going on, I think. We should find out what's happening before implementing a solution.

You've proposed a solution- a switch to turn of banners- but that might not even help. It would not, if the issue is disk space- Lutris downloads the same stuff no matter what you display on the screen.

If the problem is not disk space usage, then what it is? Network bandwidth? Screen real estate usage? Ugly banners with no taste?

**Comment by 07416** [comment]
> And I wonder what the issue you are having actually is. Is it disk space usage? Just how big is your ~/.local/share/lutris/banners directory, for instance?
> 
> Mine is 9.3MB and contains 1,138 banners. That's not even as much space as one small game, these days.

No, disk-usage isn't the main reason — I only prefer a more compact UI, similar to the one Steam can be configured to use. Sadly I `rm -r`'d the path recently and have to recreate the cache, see if the issue returns. I was at around 350MB (0,35GB) if I recall correctly.

**Comment by danieljohnson2** [comment]
That's quite a bit larger than mine, but quite a bit smaller than a large game.

Lutris does offer more compact view options via the view menu up in the header bar. This UI is a bit bugged 5.9.1 but can be made to work it you frob it with determination. Try to get the 'zoom' slider to the smallest setting; that's icons. You might prefer the list mode to the grid mode too. This UI should work better in the next release.

I'm not sure 'list mode' + 'icon zoom level' is as tight as what you are looking for- but it's similar at least. Try it!

**Comment by strycore** [comment]
I'm going to reopen this because it might be useful for working on performance issues related to the banners. There won't be a toggle in the UI but it's something that we'll be able to set via a setting in lutris.conf or an env var.

I need to be able to measure the performance impact of different banner formats, so being able to disable can give me the base timing.

**Comment by strycore** [comment]
Might be just on the list view, because showing an IconView without images might have some unexpected results. We'll see.

**Comment by strycore** [comment]
This results in something very compact indeed.
![Screenshot from 2022-01-23 14-42-26](https://user-images.githubusercontent.com/280336/150700941-4a44df2e-df61-4141-9860-80e1bdd65f23.png)

**Comment by strycore** [comment]
done, add the following line to the [lutris] section of the lutris.conf file: 

`hide_media = True`

**Comment by strycore** [comment]
Also works with LUTRIS_HIDE_MEDIA:

`LUTRIS_HIDE_MEDIA=1 ./bin/lutris`
