### ISSUE TITLE
[Feature Request] Add gamepad support to UI

### ISSUE THREAD

**Issue by Buri** [lutris/lutris#4009]
Currently, Lutris has no support for gamepad input. This makes it very difficult to use on handheld devices like Aya Neo or Steam Deck.

This would probably mean adding support for controller intself, adding appropriate controller inputs (in case of support for different controller models), create system for navigation in UI and support for on-screen keyboard.

**Comment by DavidoTek** [comment]
Could probably be done with the [inputs](https://pypi.org/project/inputs) library.
Did something similar with [ProtonUp-Qt](https://github.com/DavidoTek/ProtonUp-Qt) where I emulated keyboard input, though Lutris is using GTK instead of Qt. Only problem with inputs is that it is quite outdated and has a few bugs...

+1 Would be quite useful for the Steam Deck too.

**Comment by strycore** [comment]
The plan is to have an UI made with Godot that can be used with a gamepad. 
Having gamepad support on the main UI would be useful too, since we're not going to recreate the whole lutris UI in Godot (at least not for the foreseeable future)

At some point, I'd also like to pick up on the development of SC Controller and try to integrate it with Lutris. That would allow to have controller support for all games, not only Steam ones.
