### ISSUE TITLE
Add gamescope AMD FSR option and sharpness.

### ISSUE THREAD

**Issue by Casul51** [lutris/lutris#4041]
[Feature request]
Gamescope recently got AMD FSR feature. It would be cool if it can be enabled at start of the game automatically (`-U` for enabling it) and add sharpness configuration (`--fsr-sharpness $var`)

**Comment by strycore** [comment]
It's too early to implement this option since it's only available to people who install gamescope-git from AUR. 
Once this feature is pushed in a stable release, we can add the option. 
Not sure we should add it as an option, we can just make FSR the default, it can be toggled on and off with a keyboard shortcut.
Same with sharpness, the default one should be good enough and it can be adjusted with keyboard shortcuts

**Comment by leucome** [comment]
Yes if there is no toggle in the UI I would prefer it to be on by default.  Though a toggle switch could be a good idea  just to tel people that the feature exist. 

Also there is probably something to do  about  the presentation of the two option  Wine FSR and Gamescope FSR.  Maybe hide them both of put them side by side or fuse them together.

**Comment by Rabcor** [comment]
This is still very much needed, it looks like gamescope defaults to FSR ultra performance preset (think that's sharpness 5?), which looks like ass but lets you run any game on a potato.

**Comment by strycore** [comment]
We now have the FSR option in Gamescope
