### ISSUE TITLE
[AGS] the runner doesn't work and has several issues

### ISSUE THREAD

**Issue by qptain-Nemo** [lutris/lutris#416]
First of all the runner doesn't work due to a couple of issues

- The downloaded ags.sh doesn't have the executable attribute set
- AGS can't find the libraries without LD_LIBRARY_PATH added to ags.sh. An example version of ags.sh that works: http://hastebin.com/ubabarenov.bash

Additionally:

- the directory lib32 wasn't present in my installation at all. I don't know if it's intentional because I'm on a 64 bit system or another mistake
- instead of "game binary" or "game data" the runner offers you to select a "blopblup" in the configuration settings
- the fullscreen option doesn't do anything. I don't know what the runner does but to disable fullscreen you have to pass --windowed to AGS. Or change the contents of acsetup.cfg accordingly. The former is easier though, especially since ags.sh already relays the options given to it to ags, you'd just have to pass "--windowed" to ags.sh if the fullscreen box is unchecked.

**Comment by strycore** [comment]
That's what happens when I upload a new runner version and forget to change the default version…

Other than that:

- The lib32 is present if you install the 32bit version
- What do you mean? blopblup is not an appropriate name? ok… I've changed it to "game executable or directory"
- The fullscreen flag was -f which explains why it wouldn't work since it has to be --fullscreen, also the runner passes --windowed when the game is not fullscreen (to override any other config file)
- As a bonus I've also added graphics filters.
