### ISSUE TITLE
Update PSPPP Runner

### ISSUE THREAD

**Issue by Keyhaku** [lutris/lutris#427]
Hello,

It seems you are using an old version of PSPPP - 1.1.1.
The latest version is 1.3.

Could you please update the runner, so when lutris downloads it, it downloads the latest version ?

Thank you

**Comment by RobLoach** [comment]
libretro also has an updated version of ppsspp. You could just use that one. I believe one of the plans is to replace a lot of the emulators with their respective libretro cores.

**Comment by strycore** [comment]
After reading this ticket, I was going to update the PPSSPP build and bumped the version number in the build script. 
But then that happened:
```

CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
  CMake 3.6 or higher is required.  You are running version 2.8.12.2

```

Alright, no problem, that's why I have a Trusty and a Xenial buildbot… but again:

```
CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
  CMake 3.6 or higher is required.  You are running version 3.5.1

```

Well, damn… can  I at least try it on my yakkety desktop? Nope:

```
cmake --version
cmake version 3.5.2

```

The only way I can build this in Ubuntu is by creating a zesty container:

```
rmadison cmake
 cmake | 3.6.2-2ubuntu1    | zesty           | source, amd64, arm64, armhf, i386, powerpc, ppc64el, s390x

```

I don't really feel like doing that so now I'm cloning a Debian 8 VM to upgrade it to Debian 9…

**Comment by strycore** [comment]
A new build of PPSSPP is available, built on Debian 9 and tested on Ubuntu 16.10, runs perfectly.
