### ISSUE TITLE
Provide a way to specify BIOS file for libretro/retroarch cores

### ISSUE THREAD

**Issue by Keyhaku** [lutris/lutris#431]
Hello,

I'm trying to find where to place BIOS file for PCXS Rearmed and Mednafen PSX cores, I can't find the information neither on lutris wiki, nor retroarch wiki.

So please provide a way, via lutris GUI, to select BIOS file for libretro cores.

P.S : Meanwhile, If you could also tell me where to place the file that would help me :)

**Comment by strycore** [comment]
Yup, that's something we didn't ship with the initial RetroArch support but we got all the elements to make it more user friendly.

In the retroarch config (located by default in ~/.local/share/lutris/runners/retroarch/retroarch.cfg) there is a system_directory key pointing to where you should copy the BIOS files. If the value is 'default' (which it's likely to be) then the directory is ~/.config/retroarch/system/

Then you have to make sure to get the correct BIOS files with the correct name, for Mednafen PSX you'll have to check /.local/share/lutris/runners/retroarch/info/mednafen_psx_libretro.info

Which will tell you the filenames and MD5 checksum of the accepted BIOS files. Make sure that your BIOS are the correct ones, trying to play a Japanese game with the US BIOS won't work!

Also, pasting the MD5 in Google can be quite useful if you're having trouble finding what you're looking for ;)

**Comment by RobLoach** [comment]
Updated this a bit in https://github.com/lutris/lutris/pull/956 to use the Runner's folder system folder.... `runners/retroarch/system`.

Sidenote: RetroArch will check the firmwares for you in the "Core Information" menu.

**Comment by musjj** [comment]
@RobLoach 
> Updated this a bit in https://github.com/lutris/lutris/pull/956 to use the Runner's folder system folder.... runners/retroarch/system.

I had a problem with text not displaying in PPSSPP, so I tried to put the assets file into `~/.local/share/lutris/runners/retroarch/system` but it doesn't work. I had to put it into `~/.config/retroarch/system` instead.

**Comment by strycore** [comment]
This is why you should maybe take information that's 5 years old with a grain of salt.

**Comment by RobLoach** [comment]
RetroArch's default bios folder is there, so that makes sense. Is there anything else that we should do here? Or is this good to close?

**Comment by strycore** [comment]
I think it would be good if Lutris helped users copy BIOS files to the correct folder.

**Comment by wrightgabriel0220** [comment]
Correct me if my understanding is incorrect at all here, but as of now is there any way inside the GUI to configure something per-core like a BIOS file? I looked around a bit because I was trying to get the Beetle PSX core working myself, and I feel it'd make intuitive sense to maybe:

- add a section under the LibRetro config listing the cores
- let the user click a given core to configure it
- idk all what one might want to configure with a core but this could literally just be an option for BIOS for now with a file picker?

I have some free time and would be happy to take a shot at this if this idea doesn't feel way off the mark?

**Comment by strycore** [comment]
Thanks for offering to take a look!

The goal here is to avoid as much user intervention as possible and make everything automated. This ticket is about Libretro cores but we should implement a system that can adapt to other runners using BIOS files such as FS-UAE.

But for now, let focus on Retroarch. 
If you open the ~/.config/retroarch/cores folder you have a bunch of .info files that describe available cores. Those info files contain data about needed BIOS files. If  we take duckstation as an example, it gives: 


```
# BIOS / Firmware
firmware_count = 3
firmware0_desc = "scph5500.bin (PS1 JP BIOS)"
firmware0_path = "scph5500.bin"
firmware0_opt = "false"
firmware1_desc = "scph5501.bin (PS1 US BIOS)"
firmware1_path = "scph5501.bin"
firmware1_opt = "false"
firmware2_desc = "scph5502.bin (PS1 EU BIOS)"
firmware2_path = "scph5502.bin"
firmware2_opt = "false"
notes = "(!) scph5500.bin (md5): 8dd7d5296a650fac7319bce665a6a53c|(!) scph5501.bin (md5): 490f666e1afb15b7362b406ed1cea246|(!) scph5502.bin (md5): 32736f17079d0b2b7024407c39bd3050| This core also supports No-Intro BIOS images."
```
This gives us 3 BIOS files with their respective names and MD5 hashes.

Our goal is to copy and rename those 3 files from a known location to ~/.config/retroarch/system/ which is where Retroarch expects the BIOS files to be. 

We want the feature to be core agnostic and we want the user to provide a location where they store all their BIOS files, for any system. The best option for providing such a path would be a setting exposed in the "Storage" tab in the preferences. 

The whole process is something like:

1. The user selects a location in the Storage tab for "BIOS files location". 
2. Lutris scans the folder recursively and stores a JSON file in ~/.cache/lutris/ bios-files.json containing: filename, file size, date created, date modified, md5 hash
3. The user launches a Retroarch game, Lutris reads the .info file associated with the core running the game and gets the list of BIOS files
4. If some of the required files are not present in the destination folder ~/.config/retroarch/system, then check if any of the available files in the BIOS repository match by MD5 hash and copy them to the Retroarch system folder. 
5. Run the game without any user intervention

**Comment by strycore** [comment]
Thanks, any source that provides checksums for BIOS files is helpful. We have a dat parser on the website so that's easily ported to the client.

**Comment by strycore** [comment]
Maybe we should keep that on the backend and have the Lutris API provide checksums for BIOS files. That way we can update them without updating the client.

**Comment by wrightgabriel0220** [comment]
![image](https://github.com/user-attachments/assets/cfad8bb4-2d0c-4616-98b3-289cc021447a)
Hi again! I've started working on this and gotten the config for the path set up so far (finding it quite easy to navigate as somebody relatively newish to Python and this repo btw!) -- pictured above. I want to make sure I understand this idea of putting part of the process on the backend. 

1. My understanding is the backend in this case is the lutris api which I think is in the website?
2. If the md5 of the required BIOS is stored on the core running the game, why would we need a list of checksums on the API?

**Comment by strycore** [comment]
Thanks @wrightgabriel0220 !
In this case, there is no need to access the Lutris API, everything needed should be contained in the Retroarch files.
We have checksums for ROMs on the Lutris API but only for games, not for BIOS files.

**Comment by wrightgabriel0220** [comment]
Working on scanning through and creating the cache of BIOS files and I'm at a bit of an impasse. How do we handle the user either initially clicking the wrong folder or including non-bios, non-directory files. Hashing everything in there every time indiscriminately on select feels prone to "oops I selected /home on accident and now Lutris is trying to hash my computer for 30 minutes". Should we programmatically check filenames against RetroArch's System.dat or some other resource before hashing? Or is this just kind of a "well, don't select /home then" type of deal? If so, maybe worth adding a warning in the help text?

**Comment by strycore** [comment]
We could add some checks before calculating checksums.
Counting the number of files and folders, and calculating the overall size is much faster than computing checksums. 
We could stop the process if any of the following are met:
- too many files in the folder (idk, something like 5000)
- folder too big (1GB ? idk how big a folder would be if you collected all the BIOSes out there, I've had BIOS packages that were around 500MB)
- too many subfolders (a BIOS folder should have at most 2 or 3 levels of subfolders, anything deeper than that would be suspicious)

**Comment by wrightgabriel0220** [comment]
That totally makes sense. Will do! I'm inclined to think we should provide the user a notice that their input was invalid and wasn't scanned in. Maybe at least just outlining that input as red? Pointing it out because I don't see a way built into GTK to get that styling and the CSS is pretty lean so I'm not sure if that's really worth adding an extra class to achieve.

1GB for the folder cap seems maybe a smidge low if you've had a 500mb BIOS before, but I don't mind just testing how big a sizable collection would get just to be sure. :) I'll try that out sometime today or tomorrow.

**Comment by strycore** [comment]
We have warning labels that can be applied under widgets, so re-using them while also changing the styling would make sense. It's a pretty narrow edge case so really, it's not a big deal if the text isn't red.

The folder size cap should be whatever feels reasonable regarding checksum scanning. Even 5GB of data shouldn't take that much time, on a fairly decent CPU.

**Comment by wrightgabriel0220** [comment]
Done with everything for the user configuration side of things. The warning shows up (didn't end up figuring out red text). The folder gets scanned and cached in the json file appropriately. I'm now working on `libretro.py` to get checking and moving the BIOS files into the RetroArch system folder working. I'm noticing there may be some emulators for which our approach of pulling the checksum from the `notes` property in the respective `.info` might not work? Ex:
In `pcsx2_libretro.info`, the notes point out that it only demands a folder because "the core doesn't require any specific filename for the BIOS files" 
```
# Firmware / BIOS
firmware_count = 1
firmware0_desc = "'pcsx2/bios' folder"
firmware0_path = "pcsx2/bios"
firmware0_opt = "false"
notes = "[1] This only checks if the PCSX2 'bios' folder exists and is in the correct location.|[2] Because the core doesn't require any specific filename for the BIOS files,|[^] this info file cannot tell you if the content of your 'bios' folder is correct or not.|[3] Please check https://docs.libretro.com/library/pcsx2/#bios for more details."
```
I have no clue whether this is a very specific to PCSX2/PS2 concern or if there's other weird cases like this.

**Comment by strycore** [comment]
Thanks, that is pretty great! Don't worry about the text in red, that can be changed later.

If a core like PCSX2 doesn't provide any checksum info, just skip it for now. We'll need to get the checksum info elsewhere or implement a special case for PS2 emulation if there are no fixed checksum and it's all based on filenames.

**Comment by wrightgabriel0220** [comment]
I'm running into a tricky bit here. In `libretro.py`, we have a `system_path` variable which is based on the info file for the current RetroArch core. Since that info file seems to not typically include a `system_path`, we typically end up with the default which is `settings.RUNNER_DIR` (`settings` being `lutris.util.settings`). I don't know if I've done something weird with my config or there's something otherwise up here, but RetroArch seems to want to pull the files from `~/.config/retroarch/system`. I know this because that's where my BIOS files were before I moved them out to test this. I put them there using the RetroArch UI like a month ago before I was working on this. I've gotten Lutris now to successfully dump the BIOS I know was just working when I had it in `~/.config/retroarch/system` into the path represented by `system_path`, but when I boot the game, RetroArch tells me I'm missing the BIOS. I took a look at what `system_path` resolves to for me, and right now it's coming out to `~/.local/share/lutris/runners/retroarch/system`. So I have the BIOS at `~/.local/share/lutris/runners/retroarch/system/insertbiosname.xyz`, but I had to create `system` under `~/.local/share/lutris/runners/retroarch` to even do that. My first instinct is that either the default for `system_path` is maybe out of date or I've messed something up from my personal use? But I find it far more likely that I'm just not understanding some detail here.

**Comment by wrightgabriel0220** [comment]
Figured out the issue I was having! Turns out the system path just wasn't being set by Lutris on Retroarch itself, and so Lutris and Retroarch were out of sync on that setting. Fixed that and now it works like a charm. Video demo in the PR above.

**Comment by strycore** [comment]
We probably need to change some of the code in the Retroarch runner because it was defaulting the system folder inside the Lutris runner folder. This should not be the case, Lutris runners should be able to be deleted without any fear of losing data.

**Comment by wrightgabriel0220** [comment]
Would the ideal be to put the BIOS into `~/.config/retroarch/system` as opposed to `/.local/share/lutris/runners/retroarch/system` then?

**Comment by strycore** [comment]
Yes, nothing should be stored in .local/share/lutris/runners/ except the Lutris provider runners

**Comment by wrightgabriel0220** [comment]
Alright, pushed some new changes up on [the corresponding PR](https://github.com/lutris/lutris/pull/5807) that fix that. I also moved the functionality I'd set up into a util module so it'll be easier for me to apply this to the other runners that need it after I'm done here.

**Comment by strycore** [comment]
Thanks a lot! There's certainly going to be some refactoring of this code in the near future because I'd like to scan folders in other situations.
