### ISSUE TITLE
DLLs get unregistered after wine version change

### ISSUE THREAD

**Issue by atahanacar** [lutris/lutris#4327]
DLLs registered using the "regsvr32" command, either manually or by winetricks, gets unregistered if your prefix gets updated by Wine, for example when chaning Wine versions. This is not a Lutris problem, but one way to solve this would be to add a new runner option, like DLL overrides, which would automatically register the listed DLLs.

**Comment by strycore** [comment]
We do have a DLL overrides option, we've had it for a while.

It's better to use this feature rather than regsvr32 since that can cause issues, apparently. 

AFAIK, changing Wine builds does not affect how DLLs, even installed with Winetricks, are handled. I change Wine builds on all sorts of games very frequently and I don't believe this has ever been  an issue.

**Comment by atahanacar** [comment]
So, is using `regsvr32 quartz` the same as `WINEDLLOVERRIDES="quartz=n"`? I don't have the game that I had the problem with anymore so I can't test. However, if it is actually the case, then this is indeed a nonissue.

What happened when I created this issue was the game would work fine after quartz was installed with winetricks, but would crash after changing Wine version unless I manually ran regsvr32 inside the prefix.

**Comment by strycore** [comment]
That sounds like a Wine issue but I haven't heard of anything similar.

Do you have the name of the game that had this issue?

I don't know exactly how regsrv32 does, I don't remember having to use it. DLL Overrides should do the trick most of the time.
