### ISSUE TITLE
Black screen for Wine Desktop - lutris-fshack

### ISSUE THREAD

**Issue by Mobmaker55** [lutris/lutris#4339]
Using the standard Wine (7.11) installed, I am able to have Wine Desktop open. However, with lutris-fshack, Wine Desktop is a black screen.

Tested games: Genshin Impact, Minecraft Dungeons

My system:
Arch Linux, GNOME 42.2, NVidia GeForce GTX 1660 (tried both `nvidia-open` and `nvidia` drivers), AMD Ryzen 5 5600X.

**Comment by danieljohnson2** [comment]
I have recent had a similar problem with a couple of games, and it turned out that a firmware update had somehow caused a problem with the GLCache for those games.

Maybe you should remove the "GLCache" directory from the impacted games and see if that helps. It should regenerate itself when you run the games again.

**Comment by strycore** [comment]
I believe this shouldn't be an issue in the current default, lutris-GE-Proton8
