### ISSUE TITLE
Mass-Import Scan Games From Folder 

### ISSUE THREAD

**Issue by dux074** [lutris/lutris#4341]
![de](https://user-images.githubusercontent.com/99002223/175228973-41ef213f-dd74-40d0-aa85-e94f57464d76.png)

Done A Mass Import By Scanning my Retroarch Directory nothing popped up on libretro on lutris

**Comment by battlegroundspng** [comment]
I had to clean reinstall Windows 7 on my laptop, but luckily all my Origin game installs are on my external HDD.

I installed Origin and changed the download/game path to my external HDD.

I now have to click Download, and it immediately verifies/prepares the game since all files have already been downloaded.

 

Problem is, the first check it does is whether you have enough space to download the game. This is flawed since the game has already been downloaded and all Origin needs to do is verify the files.

 

Other apps like Steam, GOG, UPlay, battle.net allows us to "import" or "scan" for the games.
[Battlegrounds Png](https://www.battlegroundspng.com)

**Comment by telanus** [comment]
> Done A Mass Import By Scanning my Retroarch Directory nothing popped up on libretro on lutris

Currently only Dolphin (afaik) is supported when you try and mass import emulated games. RetroArch and other emulators is still on the to-do list.

**Comment by strycore** [comment]
I reworded the Scan folder feature to make it clear it's for importing games installed with Lutris. 

Importing games in Retroarch works differently. You can either use the "Import a ROM" feature or drag and drop the ROMs into the Lutris window. 

Note that this won't always use Retroarch, in a lot of cases it will but we also use MAME as a default emulator in some cases.
