### ISSUE TITLE
Launching and installing games doesn't work anymore

### ISSUE THREAD

**Issue by KiritoStorm** [lutris/lutris#4351]
I usually had no problems with Lutris, some weeks ago it wasn't possible to launch Battle.net / Overwatch and other games anymore.
I think this was caused by some wine updates that came for Zorin, but I don't know how to fix it and if that is the issue.

I also tried to change the wine versions, reinstalling the zorin / ppa version and also tried out Flatpak, that wasn't working because I didn't find any games when I was searching.

Do I need a Lutris account to lunch games? I tried to create one, but also can't login. (Login failed)

Any ideas what I can try next?

**Comment by LinJuz** [comment]
I am also experience a similar issue in regards to launching certain games.

I don't know if this specific issue pertains to just my machine alone, but after a quick look at htop, it would seem lutris sometimes launches processes related to installed games in the background. 

The fix for me was to open lutris, then open a htop instance and search for "Overwatch" in this case, and kill all of those instances. After that, launching Battle net and Overwatch worked fine.

**Comment by strycore** [comment]
Please try with latest lutris-GE-Proton8
