### ISSUE TITLE
Default behaviour of Lutris about VK icd choice makes enabling DRI_PRIME and Prime render Offload toggles useless

### ISSUE THREAD

**Issue by Leopard1907** [lutris/lutris#4357]
https://github.com/lutris/lutris/blob/master/lutris/sysoptions.py#L118

According to this; when gpu0 is is an igpu Lutris automatically defaults to using that icd even when Prime Render Offload is enabled in Lutris settings. So this leads to those toggles ( DRI_PRIME and Prime Render Offload) only being effective for OpenGL gpu choice which makes it confusing.

http://us.download.nvidia.com/XFree86/Linux-x86_64/515.57/README/primerenderoffload.html

```__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only``` should have been the option for using dgpu but even then when icd is specified on Lutris settings ( which by default it selects icd for gpu0) those variables and toggles on Lutris are not effective for Vulkan workloads.

**Comment by icebarf** [comment]
+1 

`DRI_PRIME` is not recommended even by Nvidia.

`_NV_PRIME_RENDER_OFFLOAD=1` along with Vulkan/OpenGL specific environment variables should be preferred when detecting dedicated GPUs. 

This could also be the root cause for [#4211](https://github.com/lutris/lutris/issues/4211). I'm facing similar issues right now where only the integrated GPU is being used.
