### ISSUE TITLE
Encountering a YAML float/int where a string should be breaks the installer

### ISSUE THREAD

**Issue by jimj316** [lutris/lutris#4365]
The following installer file causes the installer to lock up when it is selected in the "select version to install" dialog:
```
name: Cool Game
game_slug: cool-game
version: 012
slug: "cool-game-012"
runner: linux
script:
  game:
    exe: "$GAMEDIR/Cool Game.sh"
    working_dir: "$GAMEDIR"
  files:
    - file: "N/A:if you've made it this far the bug's fixed, congratulations"
  installer:
    - extract:
        src: file
        dst: "$GAMEDIR"
    - chmodx: "$GAMEDIR/Cool Game.sh"
```
The output from Lutris is:
```
jimj316@deskneko:~$ lutris -i cool-game.yaml 
2022-07-06 00:38:15,528: Starting Lutris 0.5.10.1
2022-07-06 00:38:15,683: Running AMD Mesa driver 22.0.5 on AMD Radeon RX 460 Graphics (polaris11, LLVM 14.0.4, DRM 3.46, 5.18.0-2-amd64) (0x67ef)
2022-07-06 00:38:15,684: GPU: 1002:67EF 1682:9460 (amdgpu drivers)
2022-07-06 00:38:15,802: Startup complete

(lutris:24446): Gtk-WARNING **: 00:38:15.936: Theme directory 64/devices of theme Gruvbox has no size field

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 157, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(script, self)
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 50, in __init__
    self.installer = LutrisInstaller(installer, self, service=self.service, appid=_appid)
  File "/usr/lib/python3/dist-packages/lutris/installer/installer.py", line 26, in __init__
    self.version = installer["version"]
TypeError: 'NoneType' object is not subscriptable
```
This seems to be caused by the unquoted "version" field being parsed as an number. The effect visible to the user is that the version appears as "10" (octal 012!), and selecting it in the install dialog causes the dialog to lock up. This happens with any unquoted number -like sequence of characters (eg. 4.2, 15, 12.3015e+02, 0x4D2)

I'll admit this is pretty obscure; I found it while working on a helper tool for creating Lutris installer scripts. The YAML library I'm using (eo-yaml) will never quote a string if it could parse without them! This is pretty bad behaviour imo, _but as far as I can tell_ is legal behaviour for a YAML writer.

Suggested fixes would be to coerce values to strings where appropriate, or detect this case and consider the installer invalid.

**Comment by danieljohnson2** [comment]
This seems like a good issue for my newly granted code-dev magic powers! I'll just fix this myself!

The YAML parser sees the 012 and decides that's an octal int, but later code fails in several places because of this.

Your specific bug is because the GTK signal machinery is converting it to a string, and then the signal handler tries to compare the integer 10 with this string- and it does not match. But a local fix does not work, it just fails later. It needs to be a string everywhere.

I've added a normalization pass for all installer YAML that just makes certain values (including the 'version') be strings, if they are present.

The version number shows up as 10 still, since it is still being read as an octal integer in the first place. The fix for that is to fix your script; it's not reasonable for Lutris to guess what you meant about that.
