### ISSUE TITLE
If PRIME Offload is enabled do not default to iGPU Vulkan ICD files

### ISSUE THREAD

**Issue by buyBread** [lutris/lutris#4400]
Genius idea I know. And hey maybe it won't scare away all the Laptop users coming from Windblows who have no clue why their games are running like garbage.

**Comment by strycore** [comment]
Let me explain the situation real quick.

![Screenshot from 2022-08-04 13-43-39](https://user-images.githubusercontent.com/280336/182949044-f3e4edd5-32a5-43c3-963e-2ae376d27e86.png)

**Comment by danieljohnson2** [comment]
Well, actually, I do.

But last I tested it, the hybrid mode thing worked perfectly with Lutris.

**Comment by danieljohnson2** [comment]
OK, so I sat down with my lappie and tried to reproduce. And I managed to! "Dishonored: Death of the Outsider" runs badly because of this issue when in Hybrid mode, but is fine in NVIDIA mode. I find that it is not exactly defaulting to Intel- it gives the 'I don't know what ICD to use' message, but the effect is the same.

Here's a PR that tries to detect this case and fails over to NVIDIA if, and only if, we could not detect the correct ICD the usual way. This should be harmless, and it fixes "Dishonored: Death of the Outsider" for me, when in Hybrid mode.
