### ISSUE TITLE
please remove line 173 in /lutris/util/steam/config.py

### ISSUE THREAD

**Issue by jordan663994** [lutris/lutris#4424]
it stops the launcher from working

**Comment by danieljohnson2** [comment]
That line looks pretty harmless.

Are you running the latest Lutris?

Back in 0.5.9 or so there was a bug in that line, which has since been fixed. I would think the latest Lutris release would be okay on this.

**Comment by strycore** [comment]
Just because you had a crash at that particular line, doesn't mean we should remove it. First make sure you are running the current 0.5.11 beta (available as a deb in the releases) and try to reproduce your issue.

As @danieljohnson2 said, I'm fairly sure this is related to a bug we have since fixed so this can be closed.
