### ISSUE TITLE
Runtime Update Checks

### ISSUE THREAD

**Issue by Zormein** [lutris/lutris#4432]
Could someone tell me how to do a manual runtime update check. If it's possible anyway. And also what's the trigger for the check anyway. Because I could change it if it's not possible yet.

**Comment by danieljohnson2** [comment]
There's no nice way to do it, but I believe if you delete the ~/.cache/lutris/updates.json file, then restart Lutris, it will re-run the check immediately.

The check is normally done every 12 hours- or more exactly, when you start Lutris if its more than 12 hours since the last time it checked. The last-check-time is in that updates.json file.

**Comment by Zormein** [comment]
Thank you! This worked!
