### ISSUE TITLE
Error Launching Lutris (ModuleNotFoundError: No module named 'utils')

### ISSUE THREAD

**Issue by Gnatzelle** [lutris/lutris#4529]
Hi...
Since this commit > https://github.com/lutris/lutris/commit/363e5cba8e9bb9374025eeb485dd5fe6ffa7a420
Lutris won't start anymore...showing the following errors when launching from the Terminal:

Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 39, in <module>
    from lutris.game import Game, export_game, import_game
  File "/usr/lib/python3.10/site-packages/lutris/game.py", line 24, in <module>
    from lutris.runners import InvalidRunner, import_runner, wine
  File "/usr/lib/python3.10/site-packages/lutris/runners/wine.py", line 32, in <module>
    from utils.extract_icon import ExtractIcon
ModuleNotFoundError: No module named 'utils'

Hope this helps...

**Comment by galen1423** [comment]
I confirm this bug with update lutris staging

**Comment by danieljohnson2** [comment]
I think I see what the problem is. The 'extract_icon.py' file is in the ./utils directory, where other lutris components are all under ./lutris somewhere. There is, I expect, a 'utils' module installed on your systems globally and it is being found first, and it does not contain this class.

I've committed a change that moves 'extract_icon.py' to a more appropriate location. Please try the master branch and see if it is better.

You need not install it. Download it and run the ./bin/lutris script within.

**Comment by Gnatzelle** [comment]
Works again with upstream :)

**Comment by danieljohnson2** [comment]
Excellent.
