### ISSUE TITLE
user folders are always linked

### ISSUE THREAD

**Issue by bdeshi** [lutris/lutris#4613]
wine create some default links for user folders like documents downloads etc. I can remove these links in the desktop integration tab of winecfg. subsequent runs follow this preference, an don't recreate those links.

but in lutris, wine is always forced to create those links. if lutris sandboxing is enabled, links point to the sandbox's subfolders, otherwise links point to linux user folders. and if i remove links from winecfg desktop integration tab, this preference gets reset on next run. any way to make link removals stick?

**Comment by danieljohnson2** [comment]
Lutris resets those links every time a game starts, which seems heavy handed and overrides anything you do with winecfg.  It's the same issue the DPI setting had.

The fix there was to track the setting with a hidden dot-file, so if you did not change the setting Lutris would just leave the WINE prefix alone.

Try [my new branch](https://github.com/lutris/lutris/tree/dj/smarter_desktop_restoration); this creates a '.lutris_destkop_integration' file that records how the prefix was last configured by Lutris. This way it can tell when the Lutris setting changes, and only update the prefix then.

This should allow you to use winecfg to customize things.

No need to install this branch; just download it and run the 'bin/lutris' script within.

**Comment by bdeshi** [comment]
@danieljohnson2 cool! this works great, with a tiny nitpick:

when i'm creating a brand new wine prefix through lutris, `.lutris_desktop_integration`'s initial content appears to be:
```
/home/bdeshi/games/test/drive_c/users/bdeshi
```
- `bdeshi` is my linux username (what a surprise)
- `/home/bdeshi/games` is the default installation folder for wine prefixes in lutris
- `test` is the prefix name for the newly created test game entry.

my default wine runner config is to create a sandbox at `~/.local/share/lutris/wine-sandbox`. shouldn't the marker file reflect that right away?
actually running the game executable through lutris fixed the file content btw.

**Comment by danieljohnson2** [comment]
That is what I expected.

Lutris configures a brand new prefix it isn't linked to anything, but isolated to the prefix. The first time you run WINE in the prefix, Lutris updates it according to your settings. I think this should happen even for the installer, so if it wants to drop files on your desktop or something, that should work.

The file records this initial state (it's the path to the WINE profile in your prefix) so that when you do use the prefix, it will realize it needs to make changes that first time.

I think Lutris does it like this because it is not convenient to get at the game's settings, or its defaults, from where it creates the prefix initially. This is a safe initial state to start with. Just so long as it does get updated before use, it should be fine.

So this sounds good.

I'm not going to merge this right now- I think we're likely to have the release of 0.5.12 soon and this seems a bit much to cram in. I've got a PR out, so @strycore might decide to merge it anyway.
