### ISSUE TITLE
[Feature Request] minimize to tray

### ISSUE THREAD

**Issue by Translator5** [lutris/lutris#462]
How about making lutris able to be minimized to tray (or still stay in tray bar) like steam or itch?

**Comment by AlexanderRavenheart** [comment]
Implemented initial tray support in #1117

**Comment by yaomtc** [comment]
I see that this is closed based on a pull request that closes this issue... And I have a tray icon now, but I don't see an function to minimize to tray. Am I missing something? I'm using 0.5.0.1.

**Comment by AlexanderRavenheart** [comment]
It should show/hide the window when clicking on the tray icon.

**Comment by yaomtc** [comment]
Currently in Plasma, clicking the system tray icon only minimizes the window to the taskbar. The window is still present, just minimized, and not _to the tray_ like the issue said, so I'd say the issue is only partially resolved.

What this request was for: functionality like Discord and Steam have, allowing you to close the window / minimize to tray while Lutris is still running in the background. And you can bring the window back again by clicking on the system tray icon.

Currently, Discord and Linux both do the same thing whether you right-click or left-click on their tray icon: they bring up a small menu. In Discord, it's mainly "Show Discord" and Quit. Steam makes you decide which part of the Steam client you want to bring up (Store, Library, etc.)

Currently Lutris gives separate functionality to the left and right click, as it should be. However the left click would be more useful if it did more than just restoring the window from the taskbar.

**Comment by Zeioth** [comment]
I suggest to re-open this issue. Currently this feature is not supported in XFCE. The current status is:

**What works correctly:**
* Tray icon is showed correctly
* Left click on the tray icon when Lutris doesn't have the focus > Lutris gets the focus

**What doesn't work correctly:**
* Left click on the tray icon when Lutris have the focus > Nothing happens. Ideally Lutris should be hidden from the taskbar.

**Comment by 3vi1** [comment]
Under plasma, the tray icon option just adds an 'extra' tray icon, it doesn't add the 'minimize to tray' feature requested here.  That is to say, Lutris doesn't get hidden from the Task Manager panel when it is minimized, as is usual with every other app that minimizes or 'closes' to the System Tray.

Plasma users can get closer to the requested experience by disabling Lutris's own system tray icon option and running the app via 'kdocker lutris' instead, which provides a real 'minimize to tray' experience.  On the negative side, that does not provide a tray icon with a context menu like Steam.

**Comment by Likkkez** [comment]
Still cant minimize to tray properly pls reopen

**Comment by danieljohnson2** [comment]
I believe I've filled in the missing behavior with commit 8a597efba27900d8d8fd633c0557dd2d56f8835c, so I don't think this needs to be reopened.
