### ISSUE TITLE
Lutris game does not work in Steam OS (Game Mode) but works in steam desktop

### ISSUE THREAD

**Issue by Bboy486** [lutris/lutris#4663]
I added a few non-steam games in lutris since they weren't working in steam os. I added the dependencies and am able to launch from lutris. I added the games to steam using the add to steam right click shortcut. 

Tested in steam desktop and the game launches without an issue. Switch to Game mode and the game gives me an error that it cannot find the path. 

In lutris I am using the arguments to mount and see my external drive. Since lutris is calling its own arguments in steam I didn't add those argument in the launch options (I did test with lutris and the STEAM_COMPAT_MOUNT arguments and it didn't work).

I'm at a loss why it would work in desktop but not game mode. Hoping someone can help me troubleshoot this issue.

**Comment by strycore** [comment]
Since no one came to your rescue and it's been a while since this issue was posted, I'm going to go ahead and close this issue.

I've installed numerous Lutris games on 2 Steam Decks and they all launch fine on both desktop and game modes.

> In lutris I am using the arguments to mount and see my external drive

I don't see what you're referring to. There is no such thing to my knowledge.

> STEAM_COMPAT_MOUNT

I have never heard of that, this isn't needed to run Lutris games on the Deck.
