### ISSUE TITLE
How do I create a win32 prefix for my game?

### ISSUE THREAD

**Issue by eternal-sorrow** [lutris/lutris#4708]
I'm trying to install a game using "Install a Windows game from media". After I press "Install" button in the dialog, I see this in the console:

```
win64 Prefix created in /path/to/a/prefix
```

But I want my game to be installed in a win32 prefix. I was never given an option to select this for my game. I don't see such an option in the Wine runner options too. So, how do I do this?

**Comment by danieljohnson2** [comment]
I believe that can be set in the "Configuration" dialog; it is on the "Game options" tab, "Prefix architecture". But it is a little tricky- you can't really change it on a prefix that exists.

You can set it up using the Add Game button in the upper left; select "Add locally installed game". This gives you a blank game configuration to fill out.

Select the WINE runner, directory, name, all that stuff. Select the prefix architecture.

Make sure you specify your "Wine Prefix" at this time. Set also the "Executable" but set it to the setup.exe you will be running. Save the configuration.

Now, play the "game"- you will actually run the installer, and the prefix will be created with the bitness you specified.

Once the game is installed you will need to edit the configuration to set the executable to the real game, rather than the installer.

It's all rather awkward, but this is a very marginal need. 64 bit prefixes work for almost anything.

**Comment by danieljohnson2** [comment]
I'm going to fold this issue into the PR (#4706) I'm working on to improve the add games window; I'll add a "32-bit prefix" checkbox you can use to do this without all this awkwardness.
