### ISSUE TITLE
Implement file picker screen during installation

### ISSUE THREAD

**Issue by gorgobacka** [lutris/lutris#474]
Several installers using files that will be downloaded from the internet and this download starts automatically. It would be good to give the user a choice to use local files instead.

Such an option would be nice to have, specially when the internet connection isn't stable or if the user is testing something and needs to download the file again and again. However, the URL to the required file should be provided that the user can download it by himself. 

But, 'the download' should be the default solution. For example, if a file is required during installation, add a dialog where the user can click [Next] for downloading or the user needs to select [local file] while providing the URL when this option is checked.

Other option would be to add somewhere in the 'Option' menu of the program a checkbox to show 'Advanced options during installation', and the suggestion mentioned above will be displayed.

**Comment by strycore** [comment]
That's the purpose of the Personal Game Archives, it's been planned for years

**Comment by gorgobacka** [comment]
@strycore is this really the same? I thought the 'Personal Game Archives' is more like a backup system.

But if you install a new game, usually you don't know which files will be downloaded (sure... you could check the installer script first). 

My suggestion is more an option to choose, if lutris downloads the files by itself or you download it manually to 'feed' the installer.

**Comment by strycore** [comment]
The PGA feature is kinda broad. It will let you archive full installed games, but also the files used by installers. Since we'll have the option to either download the files or use the ones stored in a PGA, it makes sense to have a 3rd options that lets manually browse for files (actually this might be available before the PGA is actually finished).

The way I see it is on the first installer screen all the files would be listed. Those would be marked as "N/A" would be required to be provided by the user but it wouldn't be complicated to let users override the files that already have an URL.

**Comment by strycore** [comment]
Moving that to 0.5.2 as it's an important feature for the PGA

**Comment by strycore** [comment]
So here's the final specs for this ticket.

At install time, for every installers with a files section, we show a screen with all the files used and a button letting users relocate the files. For N/A files, the user *has* to provide a location (this lets us get rid of the current file selection step doing that)

Cached files should be indicated as such, with a checkbox allowing to not use the cached version.

**Comment by strycore** [comment]
it's done
