### ISSUE TITLE
Consider prepending path instead of setting aliases for "Open Bash Terminal"

### ISSUE THREAD

**Issue by trysten** [lutris/lutris#4772]
Spent a few hours chasing this down..

When I "Open Bash Terminal" on a game configured with a wine runner, an alias is set:
`alias wine='/home/user/.local/share/lutris/runners/wine/lutris-7.2-x86_64/bin/wine'`
Aliases don't work inside shell scripts called from this bash terminal.

When I ran [a script](https://github.com/z0z0z/mf-install/blob/master/mf-install.sh) in this terminal, it uses the system version of wine and _contaminates the game's wine prefix_. If $PATH were configured instead, this wouldn't be an issue. I can't think of any downside to prepending path instead of setting aliases. It may save someone some frustration in the future when they are troubleshooting a game.

It was not immediately obvious to me that aliases were set because `which wine` always returned the system wine, while $WINE was set to the expected executable. So calling `wine --version` gave me the expected version string, but any script calling `wine` runs the system wine on the game-specific $WINEPREFIX.

**Comment by danieljohnson2** [comment]
I've thought about this and I think I agree, so I've adjusted the bash terminal for WINE so that it adjusts the PATH. Only the bash terminal though- I think that's narrow enough not to risk major breakage ahead of a release.

I've left the aliases in there, just to be safe.

This should allow your script to work, I hope. Please give it a try with the latest master; no need to install it, just download it and run 'bin/lutris' in there, and let me know how that worked.
