### ISSUE TITLE
Every time I install a game, Lutris downloads a new version of GE-Proton

### ISSUE THREAD

**Issue by moloch1994** [lutris/lutris#4894]
After installing Lutris on my current OS (HamoniKR 6.0 based on Linux Mint 20.3), I manually downloaded GE-Proton for the first game I installed. Since then, every time I install a new game, it automatically downloads a new version of it. I don't know why, and I don't know ho to stop it. I can't find anything in the settings that regulates this. Lutris didn't use to behave like this on my previous installations. And the fact that I can't find anybody else reporting this, I have to think this must be a bug.

And no, it's not just following the scripts. Sometimes I install games manually, without the scripts, and it still does this.

![Screenshot from 2023-06-07 12-04-50](https://github.com/lutris/lutris/assets/68343381/74fb9191-6de5-49d5-88df-0dc87ccc10b7)

I have a slow internet connection that I share with other people. I can't always afford to download a new version. Not to mention this is taking up disk space for no reason. Most of the games I play are old and don't require the newest version of GE-Proton, which is usually only marginally different from previous versions.

**Comment by danieljohnson2** [comment]
We definitely want to see a debug log from this.

Also, please check that you have the directory at '~/.local/share/lutris/runners/wine/lutris-GE-Proton8-7-x86_64' and it's not empty. That's where it ought to download to, for a basic (not Flatpak) install of Lutris.

You can try setting your preferred Wine version in the runner configuration as well. There's an icon to open that next to Wine in the sidebar. If you are really getting just *new* versions of Wine, that should stop it.

**Comment by moloch1994** [comment]
Here are screenshots of the folder and my configuration (if that's the one you're referring to).
![Screenshot from 2023-06-07 12-58-34](https://github.com/lutris/lutris/assets/68343381/3c55df6e-ef19-4aa9-9f67-ca64758f791d)
![Screenshot from 2023-06-07 13-00-03](https://github.com/lutris/lutris/assets/68343381/3f10d0cd-2cc6-4549-9b2d-7d417832b0f4)

How do I produce a debug log?

**Comment by moloch1994** [comment]
Ah, I see. I'm a little surprised though. I first posted about this on reddit, and strangely everybody acted like they didn't know what was going on. And googling this also didn't give me any relevant results. @strycore  You're the first person telling me this is the normal behavior.

Well, in this case, I can't say much. Hope you guys will include the option to stop the automatic updates. At any rate, thanks for your hard work, I appreciate it.

**Comment by danieljohnson2** [comment]
@moloch1994, if this is just normal updating, you should be able to pick a version of Wine at the top of the runner options (in your screenie). Once you do, an icon appears to the right of the combo box indicating that you set it.

Save that. That should keep you using that version for installs, and you should no longer be downloading new WINEs when you install.

**Comment by moloch1994** [comment]
0.5.11

I'm sorry. I would've produced the log if I knew how. I only now how to create logs for individual games, but they don't show this kind of stuff.

**Comment by danieljohnson2** [comment]
You do this in a terminal:
```
lutris -d
```

But you are a couple of versions back now. I think you might want to update to 0.5.13.

**Comment by moloch1994** [comment]
After I do that in the terminal, I assume I must to reproduce the issue for it to appear in the log? Because that would be tricky to do right now. I'd have to try in a few days, when GE-Proton gets updated.

I suppose I will update Lutris now and try installing a game again in a few days (I'll try to check for the release of the new version of GE-Proton). If the issue persists, then I will reopen this thread and post the debug log.

**Comment by danieljohnson2** [comment]
That sounds like a good plan.

I'm sure you'll like 0.5.13. It's 37% more GNOMEy!

**Comment by strycore** [comment]
>  That should keep you using that version for installs, and you should no longer be downloading new WINEs when you install.

That's not how lutris works, there is code to update to the latest default lutris.net wine build and it's only present during the install.

This will likely get changed over time when we have a download queue for everything (runtimes, runners and game files)

**Comment by moloch1994** [comment]
So, I've been using the version 0.5.13 this whole time, and I've not run into this issue ever since. I think it's fair to consider the issue solved with the update.

**Comment by strycore** [comment]
With Lutris 0.5.14 we will fix this. Each time a new Wine build is considered the default, Lutris will download it.
I don't know for sure what the issue is with 0.5.13 but it's a support nightmare. We have people running outdated Wine builds or vanilla wine. This is not good at all. Probably one of the worst bugs we've faced.

**Comment by strycore** [comment]
And yes, I understand this is the opposite of what you want.

**Comment by strycore** [comment]
Yeah, I know. But I'm changing it back to being downloaded.

**Comment by moloch1994** [comment]
Can you maybe add an option to change this?

**Comment by strycore** [comment]
You probably don't understand how bad this bug is. People come to the Discord. They're in tears, there's saying "Why my Diablo4 don't run". And then we discover they're not using the Wine version we're supposed to ship as default. 
It is a support nightmare. It is hell. It is likely in the top 3 worst bugs ever introduced in Lutris.

**Comment by strycore** [comment]
Steam doesn't have an option to not download Proton updates. Likely because they don't want to create a support nightmare.

**Comment by moloch1994** [comment]
Yeah, but in Steam the update usually appears scheduled, and you can download it later if you want. With Lutris it means that every time I want to install a game (I have already downloaded), I have to wait for a convenient time when I can afford myself to dedicate all my internet speed to it. It's a bit of a nuisance.

**Comment by strycore** [comment]
Eventually, we'll get a download queue like Steam has. 
Steam only needs to download files of an already installed game. Lutris is different in that it will need to run Windows exes during the setup so the use of Wine comes earlier.
Before you can launch the game in Steam, it will download any required Proton update so in the end, it's kinda equivalent.
I also want to add the ability to switch Wine builds at install time so that could save you from downloading updates.

**Comment by danieljohnson2** [comment]
I think I see what happened, and it's ironic. I think it's commit e74754e6ffdfab935f77f0c43641877850fb4288.

This point of this was to make installers use the configure WINE version if the user has configured one in the WINE runner options. This lets you "switch Wine builds at install time". More or less.

The new code calls get_default_version() when you *don't* configure this setting, and it turns out this is not the strange default you desire. But it's a pretty simple fix, so I'll go ahead and commit it.

I don't think get_default_version() is doing what you want though, as it picks the first from a list as the default, and system-wide Wine install is the first, if you have that. Surely you want the newly downloaded version to be actually used?

**Comment by danieljohnson2** [comment]
OK, I'm pretty sure using some dusty distro-provided Wine will not staunch the tears of the Diablio fans, so I've committed a fix to make the default we get from the api actually be the default for unconfigured (ie, new) games and installs.

So we'll download the latest upon install, *and* use it.
