### ISSUE TITLE
How to change to a custom sources from Origin to EA

### ISSUE THREAD

**Issue by gagantous** [lutris/lutris#4912]
Is it possible to change origin layout in sources tab into EA  layout and open EA app ? because origin is not supported anymore

![image](https://github.com/lutris/lutris/assets/24579576/5878202e-2d1d-4316-8402-ced2f01d2d99)

**Comment by strycore** [comment]
Yes, it's possible but note the EA App integration (the icon in the sidebar) will only be available in the next release.

Right now, what you can do is: 
- install EA App
- Copy your games from the Origin prefix to the EA App prefix: 
 
![image](https://github.com/lutris/lutris/assets/280336/cd6c8795-d615-41d5-a85b-2a9f6d0d8396)

- Open EA App and for each of your games in Program Files/EA App, click "Install".
- EA App will see that the game is present so it will only verify the files and mark them as installed instead of re-downloading the files. This can still take a while on big games like Battlefield 1.
- Consider backing up your Origin's user folder for games that don't support cloud saves (`origin/drive_c/users/`)
