### ISSUE TITLE
backup game saves

### ISSUE THREAD

**Issue by lk-minot** [lutris/lutris#492]
I don't know if it's something that have been debate already or if there is already a similar software doing that but it would be nice to have a feature similar to steam cloud.

We could use pcgamingwiki.com for retrieve the location of save game data and something like rclone for the sync.

**Comment by strycore** [comment]
We do have plans for that in the near future. Actually, after GOG support, I think I'll be starting to work on this.

**Comment by daniel-j** [comment]
Related to #57

**Comment by lk-minot** [comment]
Oh thanks for the answer, i'd like to help i have some knowledge of python programming. In the issue #57 you are talking about discussion on the wiki but it seem empty now, is there an other place to fetch some information ?

**Comment by strycore** [comment]
That was from a long time ago, since then the wiki has been rebooted. Development discussion should happen on Github.

**Comment by basxto** [comment]
@lk-minot for now you can give [Game Backup Monitor](https://github.com/mikemaximus/gbm) a shot.

It’s using VB.net and Winforms, it’s GUI looks like Windows 95, but it is working. With yesterday’s 1.02 all issues I had so far got fixed. You can not compile it on linux, but you can run it.

I managed to raise the amount of supported linux games from 46 to 98 over the last weeks.

I think it would be faster and easier to import savegame paths from this project, since all is already contained in a machine readable xml file. Therefore I also think that it makes sense to grow GBM’s game list until lutris or another project offers a better implementation for this.

GBM just compresses the game saves, copies them to a defined folder and leaves the synchronisation up to the user (rsync, dropbox etc.). Lutris could do it the same way or offer deactivatable default synching to the website. Though, using incremental backups with rsync and hard links would make more sense than storing compressed archives of the savegames.

**Comment by duhow** [comment]
**Idea:** Tracing launched processes with `lsof`, look where they create/write files, detect possible name/extensions or make a list (Lutris script), and after 10 seconds (timeout) of file not modified, backup it.

**Comment by strycore** [comment]
this is a duplicate

**Comment by lestofante** [comment]
@strycore duplicate of?

**Comment by lk-minot** [comment]
#57
