### ISSUE TITLE
Game titles are heaviily cropped 

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#4988]
Games with long names have their names cropped in the icon view. In addition to that, they look off center.

See example:

![image](https://github.com/lutris/lutris/assets/280336/db61b30b-e259-40b5-b5ac-b9e9d055fa72)

**Comment by danieljohnson2** [comment]
I've seen something like this before, but could not reproduce it. It happened in a fresh install and went away on the next restart of Lutris.

I *suspect* this is caused by one of the performance improvements- caching text sizes in the view here. We do blow the cache on style changes, so I don't know what I missed, but if it persists we can try removing that caching and see if it fixes it. It does not buy that much performance really.

It's the caching in GridViewCellRendererText (cellrenderers.py) I am thinking of.

**Comment by strycore** [comment]
Now I'm not sure if this affects the git version or only stable. And how to reliably reproduce it. I did run into this several times though.

**Comment by danieljohnson2** [comment]
I believe it can hit the stable release, but I don't know how to repro. If we can't figure it out, we can rip out the optimization entirely, and I think that's likely to fix it. But I can't be sure.

**Comment by strycore** [comment]
I can reproduce reliably when I select the Missing section in  the sidebar (there is 1 game missing) and switch to something else.

**Comment by danieljohnson2** [comment]
I'm seeing it. It is n't the caching, it looks like it's the "Missing" badge; it's rendering everything with the smaller text for that, but the measurements are still taken with the original size and that doesn't work too well.

I'll see what I can do with this.

**Comment by danieljohnson2** [comment]
I think I got it. The 'Missing' badge code scales the text via Cairo so it matches the platform badges- but restoring the Cairo scale via cr.restore() does not restore Pango's text size. I have to add an additional call to do that. It's a little weird.

You see this only after a 'Missing' badge has been shown, and the 'Missing' sidebar will always do that.

Give it a shot, and see if it looks good to you.

**Comment by strycore** [comment]
All good now :D
