### ISSUE TITLE
Lutris doesn't startup correctly on Kubuntu

### ISSUE THREAD

**Issue by catalyst1987** [lutris/lutris#5003]
### Bug description

Lutris doesn't startup correctly.  Fails on keyerror 'apple2e'

### How to Reproduce

Install the latest version of Lutris using the deb file from github on Kubuntu 22.04.3.  Try to start Lutris and it crashes

### Expected behavior

Lutris would startup correctly

### Log output

```shell
INFO     2023-08-26 15:36:26,035 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-08-26 15:36:26,036 [startup.check_driver:65]:Using NVIDIA drivers 525.125.06 for x86_64
INFO     2023-08-26 15:36:26,036 [startup.check_driver:69]:GPU: NVIDIA GeForce GTX 1070
INFO     2023-08-26 15:36:26,037 [startup.check_driver:85]:GPU: 8086:1912 1043:8694 (i915 drivers)
INFO     2023-08-26 15:36:26,037 [startup.check_driver:85]:GPU: 10DE:1B81 1458:3701 (nvidia drivers)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 436, in do_command_line
    run_all_checks()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 194, in run_all_checks
    fill_missing_platforms()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 181, in fill_missing_platforms
    game.set_platform_from_runner()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 413, in set_platform_from_runner
    self.platform = self.runner.get_platform()
  File "/usr/lib/python3/dist-packages/lutris/runners/mame.py", line 267, in get_platform
    return machine_mapping[self.game_config["machine"]]
KeyError: 'apple2e'
INFO     2023-08-26 15:36:26,150 [application.do_shutdown:960]:Shutting down Lutris
```

### System Information

```shell
Kubuntu 22.04.3
Lutris 0.5.13
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
I wonder if this is happening because Lutris is trying to set the platform of a game before having a chance to load the platforms from MAME. I'll make a patch to avoid a crash but meanwhile, if you want to start Lutris by moving away the config of games causing the issue. Run `grep -R apple2e ~/.config/lutris/games/` and delete or move the files listed.

**Comment by danieljohnson2** [comment]
I think I see what is happening. MAME needs to generate an XML file to know its own platforms. This is done asynchronously, and until it is done MAME fails the lookup because it knows no platforms yet.

I've modified it to instead return None, which is handled via a log message already.

Download the latest master and run the bin/lutris script therein- it should start now. It'll write out an XML file that it needs and after it does (there's a log entry about this too) the 0.5.13 release should then be able to start.
