### ISSUE TITLE
Keep “ROM file” after changing runner

### ISSUE THREAD

**Issue by GrimPixel** [lutris/lutris#5071]
Every time I change the runner in “Game info”, the “ROM file” is cleared, so I have to copy-paste the path to fill it. There should be a way to keep it, so I think moving it to “Game info” is the solution.

**Comment by danieljohnson2** [comment]
Funny, none of my runners here have a "ROM file" in there; they have "Executable". The Flatpak runner does not even have that. I don't think this setting can be in ''Game Info" because of that.

But I would think you could not use the same ROM (or executable) with different runners, so you would not want to carry that setting over. How would you be using this, if you had it? What runners are you using where this makes sense?

**Comment by GrimPixel** [comment]
To see “ROM file”, you need to right-click on a game, click on “Configure”. The problem is, when I change the runner, the path stored in “ROM file” gets cleared. As a result, I need to copy the path before changing the runner and paste it after that.

**Comment by strycore** [comment]
The whole config for a game gets wiped because the naming for the ROM/exe file changes between runners. It's sometimes called exe,rom,iso or main_file. 
I'm not sure if there is much value in implementing this because a file that works in a given runner is most likely to not work in another runner. What the point of porting a value to another configuration that will be incompatible?

**Comment by GrimPixel** [comment]
There is an assumption, and the conclusion is based on that. In reality, the user just wants to change between different runners that still work, e.g. Libretro and individual runners. Why would the program allow the user to change the Runner? It's not because it can malfunction, but it can function. Because in some cases, it still works, and the user needs to perform this action in these cases.

**Comment by strycore** [comment]
That's really just a minuscule edge case. We allow to change runners because we support several runners and the fact that we sometimes have several runners that support the same files is purely coincidental. We shouldn't even have them. Lutris should have one supported runner per given platform. 

So that confirms there is little to no value in implementing such a feature. (This is something I've considered  in the past and decided against doing it.)

**Comment by GrimPixel** [comment]
There is no guarantee that for one platform, one emulator is perfect and all the other are worse than it. Not all games can run on one emulator.

I would likee to hear about other people's ideas, especially those who have experience of using multiple emulators for one platform.

**Comment by strycore** [comment]
> If Lutris keeps appointing the "best emulator" for each platform

That's been the goal since the beginning of the project, to offer the best experience possible for any given game. I was under the impression that the community would step up and propose the best choice for each platform. It turns out the Linux community would rather have tons of options to tinker with, which isn't really compatible with guiding newcomers in getting their games to work.

The addition of JSON based runners made it possible to add a lot more runners very easily, resulting in some duplicate functionality. The addition of drag and drop for ROMs on the other hand goes back the other way around and chooses the most appropriate emulator for a given platform.

Over time, I would like to make the concept of runners more transparent and focus more on platforms. That would mean the way the games are configured would change slightly and it would then be possible to keep some information between runner changes.

Right now,  if you have, for example, a game for Playstation. It wouldn't make sense to keep the ISO if you switched to FS-UAE or another non Playstation runner.

If we have a way to group runners per platform then this greatly improves the user experience. Once you select your desired platform (Say, Playstation), the runner selection would be limited to Mednafen, MAME, Duckstation, and Retroarch with a list of all supported PSX cores.
The platform selection in Mednafen, MAME and Retroarch would be removed, which would be a big improvement, especially with MAME and Retroarch which both have to deal with huge dropdowns. 

There would still  be a preferred runner pre-selected by Lutris but at least, switching to other runners won't be as hard.  It's a bit more involved than just keeping the value of the ROM file around between runners but it will be worth it.
