### ISSUE TITLE
Runtime is never downloaded on new installs

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#5208]
On a fresh install of Lutris with no existing files, the runtime is never downloaded. 
I wanted to see the new download queue in action!!

**Comment by danieljohnson2** [comment]
I see; it it was commit 9fc4ad0e64bf46fa4863b1f5a4c1143d80a30aa7 that done it. It duplicated the exception handling to make get_runtime_versions_date() return 0 if the versions file is missing.

This is a bad idea- 0 is not None, it is just a number, and code (like this!) will try to just use it- producing the wrong answer  ("don't update!") instead of a helpful trace-back. The plan, as I understood it, was to raise exceptions when valid results cannot be returned.

I've removed this 'except' and added other handling so the 'how long since you updated' code can say 'never' when the file is missing (but can that legitimately happen?).

It now queues away for me.
