### ISSUE TITLE
Lutris apparently won't run as root on Ubuntu 22.04 XFCE ?

### ISSUE THREAD

**Issue by D4n2021** [lutris/lutris#5220]
![grafik](https://github.com/lutris/lutris/assets/20766261/614305d8-4a12-43ac-af96-f3f326eb929e)

**Comment by danieljohnson2** [comment]
It won't.

Now I hate security as much as the next fellow, but I wonder what you are doing here. Why run Lutris as root anyway?

**Comment by danieljohnson2** [comment]
I'm not following. Does Termux somehow force you to run as root? What do smart phones or power users have to do with this?

**Comment by danieljohnson2** [comment]
I don't know; this seems very strange. Lutris will refuse to run as root on any distribution; what is strange to me is why you are running as root. That just seems wrong. Why would Termux be doing that?

**Comment by danieljohnson2** [comment]
I doubt it; that is installing 'proot', which I think is about setting a root directory, not a root account.

**Comment by strycore** [comment]
> Because it's the default user account that is created when installing Ubuntu?

That is incorrect, in fact Ubuntu doesn't even have a proper root account, you need to set a password to it if you want a more traditional root account. 

Looks like you successfully added another user to your phone so this issue can be closed.

Also, you might want to take a look at box86 and box64 to be able to run games. Since most games are for the x86 architecture and I suppose your phone is ARM based.

If you manage to  run some games from a phone, ping us on Mastodon or Discord.

**Comment by strycore** [comment]
So I gave AndroNix a try. The base Ubuntu + XFCE does not setup a user. I did something that prevented me from running VNC as a new user.

Then I bought the paid version of Ubuntu XFCE which comes with a user. 
Managed to get Lutris running pretty painlessly.

![20240108_022325](https://github.com/lutris/lutris/assets/280336/e058ac25-b257-48a0-ba7e-02a0e34669d8)

That said, it doesn't have hardware acceleration + it's running on VNC. Dosbox was kinda fine. FS-UAE was ok but the sound was choppy.

Then again, I have a phone that was high end 4 years ago (Galaxy S10) so maybe more recent phones are more capable.

I didn't install box64 because the whole system is considerably slower than a Raspberry Pi 5 so I'm not sure it's even worth a try, especially without GPU acceleration.

**Comment by strycore** [comment]
> What exactly is it that you did that prevented it?

Not sure, VNC started once with a regular user then refused to launch.

> And "PAID version" of Ubuntu XFCE?? Bought where?

In the AndroNix App, you can buy what they call "Modded OS". It's pretty cheap.

> I tried Box86 (through Winlator App) but my game crashes on startup. :/

That's another app I had never heard of.  I don't think this one will run Lutris though, looks like it's for running Wine games directly.
