### ISSUE TITLE
0.5.15 not processing installers from lutris.net correctly

### ISSUE THREAD

**Issue by OJ2024** [lutris/lutris#5238]
0.5.15 (deb, flatpak install or from git master) 

Select either battle.net or EA App installation scripts from lutris.net

At the point in the script where a dialogue should display confirming whether you wish to download the install file or select it locally, nothing is displayed, the script continues to create the prefix then fails when it can not find "setup" in the $GAMEDIR

This does not occur on 0.5.14.

`ERROR    2024-01-16 00:05:49,112 [errors.__init__:18]:Source does not exist: setup
{'dst': '$GAMEDIR/drive_c/', 'src': 'setup'}

ERROR    2024-01-16 00:05:49,112 [jobs.target:33]:Error while completing task <function ScriptInterpreter._iter_commands.<locals>.dispatch at 0x7f36352dfce0>: <class 'lutris.installer.errors.ScriptingError'> Source does not exist: setup
{'dst': '$GAMEDIR/drive_c/', 'src': 'setup'}
  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 31, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 327, in dispatch
    return method(params)
           ^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/installer/commands.py", line 281, in merge
    raise ScriptingError(_("Source does not exist: %s") % src, params)

ERROR    2024-01-16 00:05:49,113 [interpreter._iter_commands:302]:Last install command failed, show error
`

**Comment by danieljohnson2** [comment]
Oh, crap. This one looks bad; simple fix but this could affect a *lot* of installers.

Lutris is not picking up the file list for the game because the code to commit that list is run only for games with a service and also an installer-file specified, which is going to break a lot of custom stuff like this.

I've committed a fix; please download the master branch and run the bin/lutris script in there (no need to install). Try to install battle.net; it should get further. For me it seems to hang partway through, but maybe it will work for you?

**Comment by danieljohnson2** [comment]
That hang isn't reproducing for me outside of the debugger. I got to the login window anyway.

**Comment by danieljohnson2** [comment]
OK, 0.5.16 just went up with the fix for this.

Very sorry for all the trouble!
