### ISSUE TITLE
Cannot install lutris because of dbus

### ISSUE THREAD

**Issue by ayush-india** [lutris/lutris#5246]
i have installed lutris from the .deb.

while running it i get this error

``` 
❯ lutris
Traceback (most recent call last):
  File "/usr/games/lutris", line 58, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 39, in <module>
    from lutris.api import parse_installer_url, get_runners
  File "/usr/lib/python3/dist-packages/lutris/api.py", line 18, in <module>
    from lutris.util.display import get_gpus_info
  File "/usr/lib/python3/dist-packages/lutris/util/display.py", line 31, in <module>
    from lutris.util.graphics.displayconfig import MutterDisplayManager
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/displayconfig.py", line 4, in <module>
    import dbus
  File "/usr/lib/python3/dist-packages/dbus/__init__.py", line 73, in <module>
    import dbus.types as types
  File "/usr/lib/python3/dist-packages/dbus/types.py", line 8, in <module>
    from _dbus_bindings import (
ModuleNotFoundError: No module named '_dbus_bindings'
```

i have tried to `pip install dbus-python` but no progess

**Comment by ayush-india** [comment]
```❯ sudo apt-get install python3-dbus

[sudo] password for ayu:
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-dbus is already the newest version (1.2.16-1build1).
The following package was automatically installed and is no longer required:
  libgnutls-openssl27
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by ayush-india** [comment]
i found a work around 

just go to `/usr/games` 

and run lutris with python3.8
```python3.8 lutris```

**Comment by danieljohnson2** [comment]
I wonder what version of Python you get by default. We theoretically support back to 3.7, but that's rarely used and there have been issues.

**Comment by strycore** [comment]
What is your OS and do you have python modules installed with pip rather than your package manager?

There is a similar issue here: 

https://stackoverflow.com/questions/73149688/modulenotfounderror-no-module-named-dbus-bindings-debian-11-bullseye-python

> i have tried to pip install dbus-python but no progess

The crash is in the dbus code so yes, you have it already, but there's something wrong with what is available from dbus.

> i found a work around

It seems to indicate you have multiple versions of Python. How did you install the other ones? Pyenv?

Also note that Python 3.8 is a bit on the older side of what we support. Upgrading your distro might be a good idea. As @danieljohnson2 said, we still support 3.7 so there's no issue using 3.8 but the other dependencies might be on the older side too if your OS ships with 3.8 (for reference Ubuntu 22.04 ships 3.10)

**Comment by ayush-india** [comment]
Well i have simply installed all of my python's version

Using apt, and also installed dbus using both apt and pip.
