### ISSUE TITLE
Files not deleted when selected in Remove Game dialog

### ISSUE THREAD

**Issue by DocKDE** [lutris/lutris#5250]
I noticed that after a recent update game files are not deleted anymore when asked to do so. 
When an installation fails, the leftover files are not deleted and also when removing a game from the library manually, the game files are not deleted when selecting the appropriate option.

OS: Fedora 39
Version: 0.5.16 (Flatpak)

**Comment by danieljohnson2** [comment]
We are supposed to be moving these things to the trash now. If that does not work, perhaps there's something in the log about it.

Run ``flatpak run net.lutris.Lutris -d`` from the terminal and give us the terminal spam.

**Comment by DocKDE** [comment]
```
2024-01-18 11:21:01,271: Command 'fluidsynth' not found on your system
INFO     2024-01-18 11:21:01,687 [application.do_command_line:479]:Starting Lutris 0.5.16
INFO     2024-01-18 11:21:01,689 [startup.get_drivers:67]:Running Intel Mesa driver 23.3.2 on Mesa Intel(R) Graphics (ADL GT2) (0x46a6)
INFO     2024-01-18 11:21:01,689 [display.display_gpu_info:78]:GPU: 8086:46A6 1D05:1171 (i915 drivers)
DEBUG    2024-01-18 11:21:01,954 [lutris.get_missing_game_ids:206]:Checking for missing games
DEBUG    2024-01-18 11:21:09,716 [application.show_window:392]:Showing window UninstallMultipleGamesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f120155bd40 (LutrisWindow at 0x55adc5ea0bb0)>}
DEBUG    2024-01-18 11:21:18,761 [config.remove:210]:Removed config /home/benedikt/.var/app/net.lutris.Lutris/config/lutris/games/gothic2-gog-1705572939.yml
INFO     2024-01-18 11:21:18,761 [shortcut.remove_shortcut:104]:Removing Steam shortcut for Gothic II: Gold - L'Hiver Edition (wine)
DEBUG    2024-01-18 11:21:18,762 [system.remove_folder:370]:Trashing folder /home/benedikt/Games/gog/gothic-ii-gold-edition
DEBUG    2024-01-18 11:21:18,792 [lutris.remove_from_path_cache:177]:Removing Gothic II: Gold - L'Hiver Edition (wine) from path cache
DEBUG    2024-01-18 11:21:18,792 [lutris.get_missing_game_ids:206]:Checking for missing games
DEBUG    2024-01-18 11:21:18,795 [application.on_app_window_destroyed:419]:Removed window UninstallMultipleGamesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f120155bd40 (LutrisWindow at 0x55adc5ea0bb0)>}
ERROR    2024-01-18 11:21:18,801 [portals.report_error:76]:Failed to trash folder /home/benedikt/Games/gog/gothic-ii-gold-edition: The folder could not be moved to the trash.
NoneType: None
```

**Comment by DocKDE** [comment]
Seems like an issue with flatpak and desktop portals?

**Comment by danieljohnson2** [comment]
I think I have it. At least, this change works for me.

We need to set some additional flags to flatpak won't let us trash the file or folder. I've committed a change to do this, but it's not easy for you to test it without an updated flatpak release.

If you want to get this now, you'd need to graft the updated ``portals.py`` from the repo into the flatpak Lutris install. Probably voids the warranty.

**Comment by DocKDE** [comment]
It's not a big issue for me right now so I'll wait for the next release. Is there any idea when that'll be? 
Thanks for dealing with it!

**Comment by danieljohnson2** [comment]
Not sure about the next release; @strycore seems to favor soon, but I'm arguing to get more fixes in it.

None of the bugs in 0.5.16 so far seem *that* critical to me - but he's having a crash on startup, and when the boss has a crash on startup, that's super-critical. We'll be fixing that one first at any rate.

**Comment by strycore** [comment]
Maybe we should schedule releases to be at most 1 month apart. This would require us to change how we approach new features and probably will require us to stop pushing to master directly. 

Apparently, I'm the only person on earth still using a HDD and with a good mouse and Wayland and 1500 games in Lutris... So I guess not a lot of people will experience my crash...

**Comment by strycore** [comment]
I don't use Lutris releases anyway. When I'm on desktop, I run Lutris from the development branch. 
The only time I use Lutris stable is on Steam Deck where I run the Flatpak. But the Deck doesn't have a Razer mouse or a hard drive or 1500 Lutris games.

**Comment by danieljohnson2** [comment]
Well, the thing is that for this release cycle, all the bugs have been caused by fixes for other other bugs.

1. The Steam reload crash was from a fix for a GOG reload crash
2. 'Source not found' was a fix for 'install files doubled up', itself from a GTK/Wayland fix
3. 'run_in_background' key error was from fix for pylint warnings, which came from a fix for compositor checks not being recognized.
4. 'PersonalName' key error was (somehow) from a fix for VDF file parsing errors taking the whole Preferences dialog down.
5. 'Files not deleted in flatpak' was from the TrashPortal, which is a fix for 'Lutris deleted my home directory!'

Some of those bugs (3 and 5) had been in master for awhile before release, too.

Once the 0.5.15 changelog went up, we've been mostly avoiding feature work in master. The 'waggle of death' and 'game loading spinner' made Lutris resist the GTK/Wayland crashiness, not just UI fanciness.

The 'sync Steam playtime' feature is the exception - but while it had a bug, I fixed it before release. And then my fix was bugged and *that* is the bug the users experienced.

If you mean to never push anything to master before releases, you might as well just release early. But if you mean push fixes for issues, that's pretty nearly what we actually did. It's the fixes that got us.
