### ISSUE TITLE
Battle.net games are displayed with default banner

### ISSUE THREAD

**Issue by mendres82** [lutris/lutris#5265]
Having added Battle.net to Sources in Preferences and installed the client, after scanning for Battle.net games, all games will be displayed with a generic Blizzard banner. Opening Configuration of the games and clicking "Remove custom banner" doesn't fix the issue.

Because I already got game specific banners in the past, I tried to figure out when that behavior changed and tried to revert the changes leading to the issue. The following fix allows me to download game specific banners in Configuration again:

[battlenet.zip](https://github.com/lutris/lutris/files/14002860/battlenet.zip)

I couldn't figure out yet how to get the proper banners downloaded right when scanning and adding Battle.net games, but at least they don't show with the generic one now.

**Comment by danieljohnson2** [comment]
I'll apply a bit of that fix, but not all of it. I see what went wrong; in v0.5.14 it pulls the slug from the service game record, just in this case only, which seems to be unique for Battle.net.

But I'm pretty sure it never looked for "lutris_game" anywhere, so I do not want to take that. Also, we need to return the slug we use from this method, since that's the media we'll download.

Please try with my changes in master. Download it, and run the 'bin/lutris' script within (no need to install) and see if it works better now. I think it should.

**Comment by mendres82** [comment]
It works as expected now and obviously better than my fix, because it's retrieving the correct banner right when adding the games from Battle.net source. Thanks a lot!

Since I'm not quite familiar with the code, I guess I accidentally left the "lutris_game" line in my ... ehm... "patch" :D
