### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ricandresfriki97** [lutris/lutris#5282]
Hi , I have this issues since I upgrade to the of lutris.0.5.16 , I see , I'm not alone with this issues or bug , can someone who can fix this error , help me please? Sorry for my English odd , this language is not my mother tongue , thanks

**Comment by danieljohnson2** [comment]
Are you getting this when refreshing or logging in to Steam?

If so, this should be fixed in 0.5.17, and I hear this will be coming out soon.

As a workaround, for now you could use the master branch to update. Download it from GitHub [here](https://github.com/lutris/lutris), then run the 'bin/lutris' script inside. No need to install; just run it and log in to Steam or reload it as required. Once done, you can go back to your normal installed Lutris and the updated games should be there for you.

**Comment by ricandresfriki97** [comment]
When I refresh the runners , I think this issues affect to flatpak and others as well but I'm not 100% sure

**Comment by danieljohnson2** [comment]
I expect it to affect the flatpak release as much as any other.

**Comment by ricandresfriki97** [comment]
There's no way to change the code somehow and fix the issues?

**Comment by ricandresfriki97** [comment]
It was a python issues am I right?

**Comment by danieljohnson2** [comment]
It's a bug in the Python code. If you want to try to hand fix your installation, the fix is [in this commit here](https://github.com/lutris/lutris/commit/d6faf75fb370a004b80539466a7cd0beedcf5e5c).

You would be safer using my workaround though; if you try to hand fix your install, you might just break it.

**Comment by ricandresfriki97** [comment]
I couldn't find the path

**Comment by oMrStewie** [comment]
> I couldn't find the path

Path is located at 
/usr/lib/python3.12/site-packages/lutris/services

edit the steam.py with admin

and edit the following lines shown [here](https://github.com/lutris/lutris/commit/d6faf75fb370a004b80539466a7cd0beedcf5e5c) edit the 5 lines out an replace with the 5 green and everything should work. been searching for this fix for a while.

**Comment by strycore** [comment]
Considering this issue fixed

**Comment by BangL** [comment]
what if i told you that this issue still persist for me, even with the mentioned commit?
