### ISSUE TITLE
Drop down broken Unreal Engine 5 launched with Epic Games

### ISSUE THREAD

**Issue by popovidis** [lutris/lutris#5286]
Hi there, 

I have Epic Games downloaded with Lutris (standard Lutris installer, nothing custom) and when I launch UE the drop down menus work only if I spam click them, otherwise I see the outline flash for a second and instantly disspear. To get any thing to work inside of the drop down I have to spam click it also. I have a 3070 laptop GPU with i7 11800h on Ubuntu 23.10. 

Lutris is installed from Flatpak.

**Comment by strycore** [comment]
I'm not sure running UE5 from Lutris and EGS is the best option. I've only run Unreal Engine (4 and 5) natively, which worked fine as far as my tests went. I've  used Lutris and EGS to download stuff from the marketplace since the Linux version doesn't have that.

Really not sure what the most stable solution would be between the Linux native build (which receives less support from Epic) and the Windows version with Wine (which apparently has some rendering issues)

**Comment by popovidis** [comment]
@strycore I am running with Lutris because the native build does not run for me: https://forums.unrealengine.com/t/vulkan-error-on-linux-with-an-rtx-3070/1644015

**Comment by strycore** [comment]
![image](https://github.com/lutris/lutris/assets/280336/a9bea53d-9616-44e0-ba10-6072e91c1283)


I have it running here. Since this is on a laptop, it might be worth to try the development version of Lutris and use it to launch Unreal Engine 5. The latest code has a dropdown to quickly select between available GPUs. That way, you can make sure it is forced to run on the GeForce.

**Comment by strycore** [comment]
Even without glitches, the usefulness of Unreal Engine 5 in Wine is going to be pretty limited because it's going to look for Visual Studio and fail to find it.
