### ISSUE TITLE
Uninformative error popups

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#5295]
It's quite nice to have global exception handling in Lutris but it can produce confusing results.

![Screenshot_20240202_205921](https://github.com/lutris/lutris/assets/280336/4f45a6c3-17c0-4f62-a6f9-cdcf4647068a)

In this example, a KeyError produces a message box saying "mangohud". This is more confusing than anything. There is no title to the message box, no indication it's an error. This was probably written with the preconception that exception messages would be informative, which is far from always being the case. 

There should be an indication this is an error, like "Lutris has encountered an error". It would also be useful to add the error type in the error box. 

An even better solution would be to have a "▶ Details"  button that can be expanded to 
```
▼ Details
-----------------------------------------------------
Traceback (most recent call last):
  File "/home/strider/Projects/lutris/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/strider/Projects/lutris/lutris/gui/config/boxes.py", line 695, in on_reset_button_clicked
    self.raw_config.pop(option_key)
KeyError: 'mangohud'
ERROR    2024-02-02 20:58:51,671 [exception_backstops.error_wrapper:81]:Error handling signal 'clicked': 'mangohud'
Traceback (most recent call last):
  File "/home/strider/Projects/lutris/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/strider/Projects/lutris/lutris/gui/config/boxes.py", line 695, in on_reset_button_clicked
    self.raw_config.pop(option_key)
KeyError: 'mangohud'
```

With a "Copy to clipboard" button that copies the  stack trace. This way, the stacktrace isn't lost if Lutris wasn't opened in a terminal.

**Comment by danieljohnson2** [comment]
I think I've got everything. The backstop can provide special messages and such for particular exception types, and handles KeyError to provide more of a message. It also provides a Copy to Clipboard button, and an expander to show the traceback.

It looks like this:
![Screenshot from 2024-02-04 16-09-38](https://github.com/lutris/lutris/assets/6507403/d839a237-a7e6-4a59-8598-4126bde01f6b)

Click the expander, and you get this:

![Screenshot from 2024-02-04 16-16-55](https://github.com/lutris/lutris/assets/6507403/90d854c8-b4ae-4011-9f94-0280e58e5867)

This isn't super great because the dialog is still not resizable, so you get to scroll. But I think it's close to what you wanted.

Copy to clipboard gives you both the message and traceback, regardless of whether the details are expanded.

**Comment by strycore** [comment]
That's much better!
