### ISSUE TITLE
Crash on tab switch

### ISSUE THREAD

**Issue by keybreak** [lutris/lutris#5296]
Manjaro Stable
Easily reproducible...Although it doesn't happen each time.

**RMB - > Configure -> System options**
It usually crashes fastest, if it doesn't try switching tabs, if not crashed still - close, try opening Configure again, it surely will.

**Comment by danieljohnson2** [comment]
What version of Lutris do you have? This looks like #5092.

If you are on on 0.5.14, try a more recent Lutris. This should have been fixed in 0.5.15.

You can download the latest Lutris here and test this without installing it- just run the 'bin/lutris' script in the download, and see if it still crashes for you.

**Comment by keybreak** [comment]
Yep - that's the version i have, will wait for an update and come back to see if it's resolved :+1:

**Comment by keybreak** [comment]
@danieljohnson2 
> You can download the latest Lutris here and test this without installing it- just run the 'bin/lutris' script in the download, and see if it still crashes for you.

From the quick look of it - it's fixed.
