### ISSUE TITLE
[website] image is invalid on game title banner submitter, not matter the file

### ISSUE THREAD

**Issue by jmfergeau** [lutris/lutris#5306]
I tried everything, i just can't add a missing game title banner because "the image is invalid". Tried with png and jpg, i even tried png with the exact same dimensions that are asked... Even worse, I can't propose any other changes on a game entry because it apparently requires a game title banner to do so...

Blocked on purpose or glitch?

**Comment by strycore** [comment]
> Blocked on purpose 

I am getting sick and tired of this attitude that leads people to think that bugs or malfunctions are created "on purpose"  or "by design".

We are not evil or a bunch of fucking assholes like Apple or Facebook. We are an open source project trying the best we can to offer a service that is basically running on zero resources and 100% volunteering. 

If we want to block or limit a functionality, we put an error message stating so. Thinking open source developers would got out of their way to intentionally cripple their software is downright insulting.

The worst thing is I know **exactly** what to blame for this behavior. It's 15 years of SHIT COMPUTING, pushed by Google, Apple, Facebook and the like that actively tries to prey on its users to exploit them. This has led most of the modern software to be built with anti-features and by design defect.

For the love of all we stand for, I beg you to believe that open source developers work in a spirit of goodwill.

And don't take that personally, I wouldn't lash out on you if this wasn't the 10000th time someone suggested some bug of an open source project is by design.





For the banner issue, I haven't been able to reproduce it yet and I'm the only one currently working on the website.

**Comment by jmfergeau** [comment]
> I am getting sick and tired of this attitude that leads people to think that bugs or malfunctions are created "on purpose" or "by design".

I never said that. I just mentioned that maybe it was happening because something even worse could happen if upload was being done and then glitch happening to prevent the whole website to break. I have seen this in numerous project and there's nothing wrong to do so. (as long as you inform the users about that and, sorry my bad, i haven't checked the changelogs if anything like that was there) My apologies if you took this the wrong way, no need to yell...

And btw i tried again today and it's still doing it. Just saying `This is not a valid image format`. I can't see any other logging info in my end. It's on an unpublished page though.

~~maybe i better never report any bug again to anything...~~

**Comment by strycore** [comment]
Now you're taking this personally. As I said, I have numerous reports of issues suggesting defects are purposefully added to the software. This is never the case.

The "not a valid image format" was caused by a Pillow update which is used to process images. Now the code is updated to support the latest version and image uploads are working again.
