### ISSUE TITLE
 missing VLK icd loader

### ISSUE THREAD

**Issue by Xdavius** [lutris/lutris#5416]
Hi lutris team !

I discovered that the GPU driver loading menu has disapeared !! I'm now blocked ion lit of distro's to select using AMDVLK/Vulakn pro/Mesa On the fly, which was a Big feature for me.

I have some games that just refused to run / Not quitte optimised with Mesa, so I need to switch. Same using RT, AMDVLK Is a lot better than radv.

In some cases, selecting dGPU was also a greet option (laptop AMD/AMD for exemple) and now we just need to pass lots af parms... (using mesa layers...)

It's VERY BIG feature regression for gaming and compatibility...

For my usage, I need to downgrade lutris to 0.5.16. Cannot stay in 0.5.17 without theses functions, as some of my games refused to run with RADV, and need amdvlk (Ratchet and clank) or Vulkan pro (Detroit become human)

In some other cases, I can also experiment a better experience changing the driver.

Please, return this feature...

Thank you

**Comment by Xdavius** [comment]
![Copie d'écran_20240412_142240](https://github.com/lutris/lutris/assets/66792063/e3bd1cc6-7524-4d02-a3b0-7d246b20e801)

**Comment by Leopard1907** [comment]
Yes, that was a very useful feature because not all games runs great on Radv and amdvlk/pro option being presented there was useful. Even for testing sake.

**Comment by strycore** [comment]
DO NOT USE AMD GPU PRO / AMDVLK FOR GAMES.

**Comment by strycore** [comment]
>  need amdvlk (Ratchet and clank) or Vulkan pro (Detroit become human)

Both of those statements are demonstrably false.

**Comment by strycore** [comment]
AMD GPU Pro is NOT for gaming and never was

**Comment by strycore** [comment]
> Not quitte optimised with Mesa

Use a more recent Mesa

**Comment by strycore** [comment]
And use a more recent  kernel. The amdgpu driver is in the kernel

**Comment by strycore** [comment]
> that was a very useful feature

No it wasn't

**Comment by strycore** [comment]
AMD GPU Pro works on 3 distros and is the fastest way TO COMPLETELY FUCK UP your OS.

**Comment by Xdavius** [comment]
> And use a more recent  kernel. The amdgpu driver is in the kernel

I bleeding edge. On both debian and arch, with all tkg kernel.

Also rebundled the amdgpu firmware, upgraded etc... 

It's not the problem

**Comment by strycore** [comment]
By making it easy, it gives the impression it is an option. No it's not an option. 
AMD GPU Pro is the fastest way for people to mess their Linux install, get frustrated and return to Windows 11.

If we care about Linux gaming, AMD GPU Pro must never be associated with video games ever again.

**Comment by thesacredsin** [comment]
Wait, I thought Linux was about choice? So you are choosing that people cannot use AMD GPU Pro, nice

**Comment by strycore** [comment]
First of all, Linux isn't about choice. That's a meme created by Reddit punks who use that as a justification for making bad decisions. 

But let's say for a minute that Linux is about choice. AMD has chosen to support their closed source driver on 2 Linux distros.
I have chosen to stop offering something that is potentially dangerous to users of my software.
And you have chosen to complain about it on a closed Github ticket instead of reading the source code and coming up with a solution. 

So maybe you're right after all, maybe Linux is about choice, or maybe everything that surrounds us is about the choices we make, whether they are related to Linux or not.

**Comment by danieljohnson2** [comment]
I think maybe Linux is about choice... but it mostly the choice of the programmers.

Case in point, the easiest way to get your favorite feature idea into Lutris is to submit a PR that implements it. @strycore is remarkably open minded about those. Much less so about people just demanding that he provide them with things.

**Comment by strycore** [comment]
I have never heard a developer parrot that "Linux is about choice" meme. 

If "Linux is about choice" a clumsy way to say "Open source software is about freedom" then yeah why not. But in most cases, the LinuxAboutChoice people don't care about freedom, they want to be baby fed and nurtured by open source maintainers because they are the children of consumerism and it's difficult for them to imagine a world that works differently.

If we read the 4 freedoms directing open source software:

- The freedom to run the program as you wish, for any purpose (freedom 0).
- The freedom to study how the program works, and change it so it does your computing as you wish (freedom 1). Access to the source code is a precondition for this.
- The freedom to redistribute copies so you can help others (freedom 2).
- The freedom to distribute copies of your modified versions to others (freedom 3). By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

I would say the LinuxAboutChoice crowd either doesn't care or take those freedoms for granted. The Lutris projects values those 4 freedoms but guarantees nothing else. Like what the MIT license states: 

`THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND`.
 
To quote the islinuxaboutchoice dot com website : 

> But the chain of logic from "Linux is about choice" to "ship everything and let the user chose how they want their  to not work" starts with fallacy and ends with disaster.

I don't want to give people false hopes about merging PRs. The use of AMDGPU Pro for the purpose of gaming is a disaster in the making. We will not have in Lutris an option to switch to AMDGPU Pro because that would basically be us saying "yeah, go on, install amdgpupro, no problem at all". The only thing that would be tolerated would be a fix to allow the ICD file to be overridden in the env vars, if that doesn't work already. 
Everyone should keep in mind that the goal of Lutris is to make gaming on Linux more robust, not hand out loaded rocket launchers so people can shoot themselves in the foot.
