### ISSUE TITLE
Lutris wont load EA games to its library

### ISSUE THREAD

**Issue by ninuola** [lutris/lutris#5456]
I am able to install the EA app and launch it without issues, however, Lurtis encounters an error whenever I try to load my EA games to the Lutris Library. Please see error message below:

```
can only concatenate str (not "NoneType") to str

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/services/base.py", line 143, in do_reload
    self.load_icons()

  File "/app/lib/python3.11/site-packages/lutris/services/base.py", line 167, in load_icons
    media_urls = service_media.get_media_urls()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/services/service_media.py", line 83, in get_media_urls
    media_url = self.get_media_url(details)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/services/ea_app.py", line 66, in get_media_url
    return details["imageServer"] + details["i18n"][self.api_field]
           ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TypeError: can only concatenate str (not "NoneType") to str
```

Even though I install games and play them directly using the EA app, I prefer the tighter integration to the Lutris app. I would appreciate any guidance on resolving this issue.

Many thanks.

![Screenshot_20240427_121646](https://github.com/lutris/lutris/assets/1965655/ec69c598-cc01-4c76-ae37-d66bd18ecc8b)

**Comment by ninuola** [comment]
Please why did you close this?

**Comment by danieljohnson2** [comment]
Looks like the EA API isn't giving us small sized art for a game.

I've committed a change to tolerate this and log about the problem, which is something other sources already do.

Please download [the master branch](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within - no need to install it. Reload the EA App source, and give us the log from that. Also, check to see if you have any missing EA media; maybe only some sizes are missing or something.

(I closed it because I think I fixed it)

**Comment by ninuola** [comment]
Sorry I didn't see your post when I sent that.

Anyway I just tried running the script but I get this:

```
(deck@steamdeck bin)$ sudo ./lutris
Traceback (most recent call last):
  File "/opt/lutris/bin/./lutris", line 61, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lutris/lutris/gui/application.py", line 37, in <module>
    from lutris.api import get_runners, parse_installer_url
  File "/opt/lutris/lutris/api.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
(1)(deck@steamdeck bin)$ 
```

**Comment by danieljohnson2** [comment]
Ah, it looks like you are running on a Steam deck? I believe you have to use flatpak for that, so my just-download-it trick doesn't work.

That's unfortunate, since you can't test the fix until a new Lutris beta flatpak comes out, which may be a while since 0.5.17 just dropped.

If you have a desktop or laptop where you can install Lutris, you could try it there- even if you can't play any games on it, you can see if the artwork appears.

**Comment by ninuola** [comment]
Yes, I am running on a Steam Deck. I don't have another machine to test it on, but I guess I can live with it for now and wait until a flatpak with the fix is released.

Thank you so much for your time.
