### ISSUE TITLE
Linux Mint compatibility and support

### ISSUE THREAD

**Issue by clefebvre** [lutris/lutris#5458]
Hi everyone,

Thank you for making Lutris.

This is Clem from Linux Mint.

I heard your project no longer supported us because of compatibility issues. This is very unfortunate.

https://www.reddit.com/r/Lutris/comments/i66650/is_linux_mint_no_longer_officially_supported/
https://www.reddit.com/r/Lutris/comments/onxwkb/mint_has_been_dropped_again/

Please let me know more about these issues, so we can address them.

I look forward to getting these fixed so Lutris works in Mint just as well as anywhere else.

Thank you.

**Comment by strycore** [comment]
citrusalex replied to those Reddit threads explaining the reasoning behind removing the Mint logo from the download page. Despite this, we are still providing support to Mint users on our Discord.

My expectation is that anything that would have caused issues back in 2021 has been fixed since then so I'm not sure there's anything to do on Mint's side. 

I'm going to restore the Mint icon on the download page and if you or someone in the Mint community find some specific issue that trips up Lutris, we can work on addressing that.

**Comment by clefebvre** [comment]
Alright that's great news.

If you ever bump into issues again give me a shout on Matrix. We'll be glad to help.
