### ISSUE TITLE
Need to manually install files to /usr/share. battle.net install fails on winetricks arial install

### ISSUE THREAD

**Issue by bebing2** [lutris/lutris#5459]
Hi! Used lutris awhile ago and was so grateful to get Diablo IV and other dx12 games that are tricky to get running on a vanilla wine/vkd3d-winehq install. One note: I use LFS and don't have access to a package manager. When I do a

```
git clone https://github.com/lutris/lutris.git
cd lutris
./bin/lutris -d
```

I get

`OSError: data_path can't be found at : /usr/share/lutris`

So I manually copy lutris/share/* to /usr/share. Then ./bin/lutris -d appears to run fine and performs some installs.
But when I try to install battle.net from the lutris install script I get

```
lutris-wrapper: /home/user/.local/share/lutris/runtime/winetricks/winetricks
Started initial process 18390 from /home/user/.local/share/lutris/runtime/winetricks/winetricks --unattended arial
Start monitoring process.
Waiting for game to start (first non-excluded process started)
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
```

debug output:

```
Traceback (most recent call last):

  File "/usr/src/lutris/lutris/exception_backstops.py", line 76, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/lutris/lutris/util/jobs.py", line 128, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^

  File "/usr/src/lutris/lutris/installer/commands.py", line 444, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)

lutris.installer.errors.ScriptingError: Command exited with code 256
```

I googled, and some folks had similar problems, but the details were a bit different and their solutions did not help. I also tried installing with the local battle.net setup file, but that failed as well. I also tried using my system winetricks, and tried some other settings like unchecking prefer system libraries, but nothing helped. I have wine-staging-9.7 installed on my system and battle.net and most games run okay, but Diablo IV and Wow dx12 do not work. D2R does. So I am using lutris to run D4 and Wow dx12.
Thanks in advance for any help or input, sorry if it's a problem on my end!

**Comment by strycore** [comment]
> I use LFS and don't have access to a package manager. 

Since you use LFS, I assume that you are fully aware that you can't just run software like that, right? You have to replicate the work done by people who write packages on other distributions. You have to provide all needed dependencies for Lutris to run properly.

You're running in the data_path error because you did your git clone under /usr which will make /usr/share/lutris the data path. To properly run lutris from the source tree do your git clone elsewhere.

You are then missing dependencies that allow wine to run properly. I strongly suggest that you do a full wine + wine32 install on your system before attempting to run lutris.

**Comment by bebing2** [comment]
No need to be condescending. So with wine 9.x, you don't build 64 bit and 32 bit versions any more. I used to build 64 bit and 32 bit versions of Vulkan and VKD3D and wine. I still have the 64 bit and 32 bit versions of Vulkan and VKD3D libraries installed. Can you specify the dependencies I don't meet? I successfully was running lutris for a long time before I wiped it out when I installed Windows 10 on the same box. The directions did not specify any directory to use or not to use, so do you have a directory to recommend? If this is going make you upset you are probably better off ignoring it.

**Comment by strycore** [comment]
> No need to be condescending

You're using LFS. Open source application developers cannot offer support for  LFS for more than obvious reasons.

> Can you specify the dependencies I don't meet?

Nope, unless you send me SSH root access to your box.

> The directions did not specify any directory to use or not to use, so do you have a directory to recommend?

That's because people don't usually git clone in /usr. Anywhere outside of /usr is fine. 

> because of VKD3D-proton which is "hard" to build.

You don't need to build VKD3D, you just need a working Vulkan install. Lutris ships with VKD3D builds. 

> If this is going make you upset you are probably better off ignoring it

I'm not upset, just reminding you that as a LFS user you are expected to be able to support yourself because no one else can. This is applicable to all open source software, not just Lutris.

Your winetricks issue isn't related to Vulkan btw.

**Comment by bebing2** [comment]
Great, thanks for your help.

**Comment by strycore** [comment]
Going to close this but if you do find your missing dependency and it's not documented on our side you can reply to this ticket and I'll update the README / INSTALL files

**Comment by bebing2** [comment]
In case it helps someone else, I just installed battle.net through Steam, and then installed the DX12 games that weren't working with wine-staging through Steam and battle.net. It was painless. Just had to specify certain versions of proton.
