### ISSUE TITLE
When using Proton-GE/umu the "Launch EXE in this prefix" option is broken

### ISSUE THREAD

**Issue by insanemal** [lutris/lutris#5519]
### Bug description

Attempting to launch EXE's into pre-existing or even possibly new Wine prefix locations does not work as expected when using Proton-GE as your runner. This uses umu from what I can see. 

### How to Reproduce

1. Go to 'A game'
2. Click on 'Run exe inside this wine prefix '
3. See Absolutely nothing unless you run lutris from a terminal and can catch the error messages

### Expected behavior

It to work like it does with other Wine launchers

### Log output

```shell
lutris-wrapper: /home/mal/.local/share/lutris/runtime/umu/umu_run.py
Started initial process 865031 from /home/mal/.local/share/lutris/runtime/umu/umu_run.py /Games3/Downloads/Installer.exe
Start monitoring process.
ERROR:  BaseException
Traceback (most recent call last):
  File "/home/mal/.local/share/lutris/runtime/umu/umu_run.py", line 387, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mal/.local/share/lutris/runtime/umu/umu_run.py", line 379, in main
    build_command(env, UMU_LOCAL, command, opts)
  File "/home/mal/.local/share/lutris/runtime/umu/umu_run.py", line 251, in build_command
    raise FileNotFoundError(err)
FileNotFoundError: The following file was not found in PROTONPATH: proton
Monitored process exited.
Initial process has exited (return code: 0)
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.8.9-arch1-1
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 1700X Eight-Core Processor
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 31.3 GB
Swap: 8.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 19.0.0, DRM 3.57, 6.8.9-arch1-1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.0-devel (git-eac703f691)
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.0-devel (git-eac703f691)
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.0-devel (git-eac703f691)
Vulkan Version: 1.3.279
Vulkan Drivers: AMD Radeon RX 7900 XTX (1.3.280)
```

**Comment by danieljohnson2** [comment]
I can repro this one, though I think it's only broken for the ``GE-Proton (Latest)`` option which sticks that text where a path is expected and breaks a lot of things. Since @strycore isn't working on this at the moment, I'll work on it - though I don't understand what his plan even was.

I've added a check on the code path here that checks for ``GE-Proton (Latest)`` and substitute the proper .py file for UMU, and also omits the ``PROTONPATH`` env-var which seems to be how this is handled by the wine runner's game start code. That make it work for me.

@insanemal, please download [the latest master](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within; no  need to install. Try to run your EXE in your Proton prefix. Does it run now?

**Comment by insanemal** [comment]
Sorry yes GE-Proton is the problem one not Proton-GE. Sorry I got my names a little mixed up. 

I'll try and do that today.

**Comment by GnomeBeans** [comment]
I had the same issue only the .net 8 app I'm trying to run keeps crashing but doesn't when I switch it back to GE WINE but not if prefix is built by GE WINE first.

**Comment by insanemal** [comment]
@danieljohnson2 

I totally forgot to come back and confirm it's all working. My apologies 

@GnomeBeans that sounds like a totally different issue

**Comment by GnomeBeans** [comment]
> @danieljohnson2
> 
> I totally forgot to come back and confirm it's all working. My apologies
> 
> @GnomeBeans that sounds like a totally different issue

It is. Its working on newer wine version. I meant to confirm that your instruction worked to get proton (latest) working without OPs error.

**Comment by danieljohnson2** [comment]
Excellent. As far as I know, UMU ('GE Proton (Latest)') works for all Lutris functions in master now.

**Comment by Silverbullet069** [comment]
I have to necro this. I am having the same problem with using `GE-Proton (latest)` to "Launch EXE in this prefix". 

```
umu-launcher version 1.1.3 (3.11.9 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0])
Setting up Unified Launcher for Windows Games on Linux...
Downloading latest steamrt sniper, please wait...
SteamLinuxRuntime_sniper.tar.xz: SHA256 is OK
Verifying integrity of sniper_platform_0.20241111.107899...
sniper_platform_0.20241111.107899: mtree is OK
ERROR: The following file was not found in PROTONPATH: proton
Traceback (most recent call last):
  File "/home/silverbullet069/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py/__main__.py", line 14, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/silverbullet069/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py/__main__.py", line 9, in main
    return umu_run()
           ^^^^^^^^^
  File "/home/silverbullet069/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py/umu/umu_run.py", line 885, in main
    command: tuple[Path | str, ...] = build_command(env, UMU_LOCAL, opts)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/silverbullet069/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py/umu/umu_run.py", line 352, in build_command
    raise FileNotFoundError(err)
FileNotFoundError: The following file was not found in PROTONPATH: proton
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
```

**Comment by danieljohnson2** [comment]
I would guess you are using the 0.5.17 release that does not have the fixes.

In the latest master, you have "ge-proton" instead of "GE-Proton (Latest)", you see.

**Comment by Silverbullet069** [comment]
> I would guess you are using the 0.5.17 release that does not have the fixes.
> 
> In the latest master, you have "ge-proton" instead of "GE-Proton (Latest)", you see.

@danieljohnson2 Yeah exactly, my version is 0.5.17.

But my situation is a little more tricker. This disappearance of "GE-Proton (Latest)" is actually caused by disrupting the download and extract process of Wine TKG when installing it through [ProtonUp-Qt](https://github.com/DavidoTek/ProtonUp-Qt) into Lutris Flatpak. It stucks at 99% so I closed-and-opened it. Doing this will make Lutris Flatpak gone haywire and GE-Proton (latest) has become invisible to the eyes of Lutris Flatpak. I have succefully downloaded and extracted the Wine TKG package later and "GE-Proton (Latest) became visible again.

But again, this “GE-Proton (latest)” is bugged with Steam Overlay can't be run since it's an inside-outside sandbox communication between native Steam and Flatpak Lutris (and Games running inside Flatpak Lutris), which is out of the scope of this GitHub issue. So I might have to look into the latest master where it got its new name "ge-proton" .



I have managed to workaround this by using [ProtonUp-Qt](https://github.com/DavidoTek/ProtonUp-Qt) and install `GE-Proton9-20` into native Steam (Steam installed via `dnf`).
