### ISSUE TITLE
Add launcher support for all sources that have one

### ISSUE THREAD

**Issue by Rathmox** [lutris/lutris#5560]
Currently, only sources that require a launcher to work have a shortcut to run the launcher: Epic, EA and Ubisoft.

But GOG, itch.io, and Amazon, don't have that shortcut, while it can be very useful:
For example, playing online on GOG requires GOG Galaxy, but we don't have a straightforward way to install it and we cannot run games from lutris through GOG Galaxy.

**Comment by strycore** [comment]
you can certainly install and launch GOG galaxy from Lutris, I do it all the time when I need to update a GOG game because the process is faster than Lutris. 

Please try to create tickets that are more targeted. This is all a bit vague, especially when we already have a lot of plans to bring the Galaxy API into Lutris.
