### ISSUE TITLE
[Request] Ability to Install Windows version of a Game that has both Windows and Linux versions

### ISSUE THREAD

**Issue by lemonzest79** [lutris/lutris#5580]
Hi

I would like to be able to override the option for games from a store that has both Windows and Linux versions of a game, currently the option is to install the Linux version and no option to change, reason to change could be, preference, support, feature differences, dlc availability with a game so would this be possible to add? Current stores/platforms I noticed this with are Itch.io and GOG.com currently can't test Amazon due to error, thanks.

**Comment by danieljohnson2** [comment]
I have already implemented this for GOG and Itch.IO; you can [download the latest master](https://github.com/lutris/lutris) to try it out. Just run the ``bin/lutris`` script to try it- no need to install.

I don't have an Amazon account, and looking at the code it's not clear how to do it- the Amazon service seems to know nothing of platforms in the first place. If you are having the 'asin' error, that should be fixed in master too so you can try Amazon out as well.

**Comment by danieljohnson2** [comment]
I think this is as done as it can be, unless somebody who knows Amazon better than I wants to go for it.

But I don't think this needs to stay open just for that.
