### ISSUE TITLE
Support for ShadPS4

### ISSUE THREAD

**Issue by Howarddj** [lutris/lutris#5678]
will lutris ever support shadPS4 as a runner? 
i can add it manually but every time lutris updates it gets lost.

**Comment by strycore** [comment]
> will lutris ever support shadPS4 as a runner?

We will support it when it is usable, the use of "ever" in your question is really weird considering we're talking about an experimental emulator. You should chill more.

> every time lutris updates it gets lost. 

Well you must be something real weird then because nothing gets removed during Lutris updates

**Comment by Howarddj** [comment]
I wasn't intending to come across as hostile, I only meant it might not be feasible to support it as a runner due to the sys modules having to be dumped from a PS4 to get it to run.

**Comment by strycore** [comment]
no worry, it didn't come up as hostile just a bit impatient :smile: 

I don't know what's that about the sys modules. I've tried Sonic Mania which works fine and Bloodborne which still require a bit of work on either the emulator's renderer or the vulkan drivers but otherwise works fine too (and should work on Nvidia and AMD GPU Pro drivers). No dumping from a PS4 was required.

**Comment by DocMAX** [comment]
is it possible to add it manually as custom launcher?

**Comment by strycore** [comment]
Sure. But if it would be more helpful for everyone to have builds that can be used by everyone (and can run Bloodborne, since this is probably the most wanted game for this emulator)

**Comment by strycore** [comment]
Now implemented as a lutris runner

**Comment by moedesux** [comment]
Imagine my surprise when I was googling the same question as OP and when I saw @strycore 's reply that it was implemented just yesterday. Thanks all for your good work, really appreciated
