### ISSUE TITLE
lutris have a limited subset of gamescope options

### ISSUE THREAD

**Issue by andrew-ld** [lutris/lutris#5688]
currently with lutris permits to configure a limited subset of gamescope options.

i think that a lot of gamescope options are too complex for the newbies, maybe we need to review the gamescope options and add an specific ui element only for most used and important options, for all other options we could add a input text for custom arguments to be parsed to the gamescope arguments.

**Comment by andrew-ld** [comment]
examples of options that might be useful:
--hide-cursor-delay
--force-grab-cursor
--filter

**Comment by danieljohnson2** [comment]
We have ``--force-grab-cursor`` under the name 'Relative Mouse Mode'. You can include custom flags via the 'Custom Settings' option in the GameScope option section.

I think 0.5.17 has these already, but they are advanced options, so you need to tick the 'Advanced' switch in the header bar.

So maybe this is already done?

**Comment by strycore** [comment]
> currently with lutris permits to configure a limited subset of gamescope options.

This is by design not only for gamescope but for the entirety of the Lutris project, for every feature. 
We don't want to overwhelm users with a bloated, ugly and unusable UI by exposing every possible option of every component we use. 
We expose what makes sense and what is useful in the context of gaming. 

If you feel something useful is missing, then open a bug specifically about this feature, don;t be complaining that we don't expose everything because that's not going to happen as I don't want to make software that is total trash.

**Comment by andrew-ld** [comment]
@strycore This is exactly why I had asked to add only if necessary new options in the UI and the rest do it with a text field and the user chooses what to put if they want to

**Comment by danieljohnson2** [comment]
I think we already have what you are asking for. Have you tired the options I suggested?

**Comment by andrew-ld** [comment]
yes I confirm that there is the second part of my request, I had not noticed that by activating advanced it was possible to do that.
