### ISSUE TITLE
Modernize UI

### ISSUE THREAD

**Issue by TingPing** [lutris/lutris#570]
This is a tracking bug on modernizing the UI. This was initially started in #188 and here was a video of that design: https://dl.tingping.se/videos/lutris-screencast-2.webm

- [x] Migrate to GAction
- [x] Migrate to GMenu
- [x] Move GtkSearchEntry into a GtkRevealer
- [x] Add GtkOverlay when no games found
- [x] Move view options to a GtkPopover (much cleaner with Gtk 3.16 for GtkModelButton)
- [x] Replace GtkToolBar with GtkHeaderBar
- [x] Replace MenuBar with AppMenu
- [x] Use GtkListBox for sidebar
- [ ] Use GtkHeaderBar for all Dialogs (partially done)

Work on-going in this branch: https://github.com/lutris/lutris/tree/tingping/ui

Future ideas:

- [ ] ~~Move all filters to a GtkPopover (runners, platform)~~
- [ ] Maybe use GdTaggedEntry?
- [ ] Use GtkFileChooserNative when available
- [ ] Floating statusbar?
- [ ] Kill `Gtk.Dialog.run()` usage
- [ ] Replace remaining GtkBuilder usage with templates

**Comment by Faalagorn** [comment]
Aw, hopefully this will be optional or with an ability to use a custom skin, as I like the current skin more. Still, any innovation is good I think :)

**Comment by TingPing** [comment]
Too much has changed for it to be optional. We could support menubars on 'traditional' platforms easily but that alone I don't think is very valuable.

**Comment by Faalagorn** [comment]
Thanks for reply. Any idea how will it looks at other DEs then, or especially under tiling managers (as that's what I'm currently using; i3 with eventual plans to switch to sway)?

Maybe it's just GNOME (?) desktop featured on the video that got me uncomfortable - in particular I don't like the menu hidden on top of the bar along with the controls that aren't even used in tiling modes (no minimizing/maximizing/closing with a mouse with those) - for the same reason Steam is kinda problematic under tiling managers, though I don't have problems with Chromium which adds it bar on the top and there's no buttons for closing/maximizing/minimizing window visible under it.

For similar reason (because of the UI) I kinda avoid using GNOME programs, even if I'm generally welcome towards GNOME project (I kinda like that Ubuntu and other distros switch to it by default, too) - hopefully the UI won't be issue enough to prevent me from using Lutris :)

Anyway, looking forward for any changes, even though I think either some basic theming/skinning or ability to match look and feel to GTK/Qt/whatever toolkit user wants could be a fine addition :)

**Comment by TingPing** [comment]
It is certainly a bit out of place on a tiling wm (I think in the past there have been window shadow issues?) but everything should still be functional.

Feel free to clone that branch and try running it yourself to offer some feedback.

**Comment by TingPing** [comment]
Closed by 1d397c19a24b454e8162a84f12d30a7ea8b12683
