### ISSUE TITLE
[0.5.18] commit ee33216 breaks DLSS functionality in games

### ISSUE THREAD

**Issue by CPioGH2002** [lutris/lutris#5732]
### Update:
Thanks to [shakakibara12](https://github.com/shakakibara12), it was established that commit ee33216 breaks the DLSS functionality. Still wondering why that is though.

### (initial) Bug description

Huge fan of Lutris, still having 0.5.17 (via default repos) installed but also testing how 0.5.18 (fd32592e) has improved.

I can play games with both of them but, **on 0.5.18, the DLSS implementation stopped working since a few commits ago**. Games do still start but have anything regarding DLSS greyed out or unavailable. That is with using the same runners as on 0.5.17. Same game settings, same system.

I did check if my **Runner options** are to blame but those did not change and also have everything enabled which might be needed for DLSS to work. Still, I also used the old System options parameters like _PROTON_ENABLE_NVAPI=1_ to see if those do the trick with 0.5.18. Same result though.

Find my current 0.5.18 Runner options in the screenshot below. Maybe I'm missing something.

I did try **all available runners**, so it doesn't matter if I use "umu" releases or GE-Proton for example. The same runners which work with 0.5.17 and offer DLSS fail to do so on 0.5.18.

I also checked if a **driver update** mattered, switching from 560.35.03 ("New Feature" branch) to 565.57.01 ("Beta"). 

### How to Reproduce

1. Start game with 0.5.17 and check for DLSS options (needs a supported game and hardware, obviously), enable those
2. Check if DLSS works (altering presets, the picture and performance impact should change)
3. Try the same when using 0.5.18
4. See how DLSS game options are now disabled or unavailable with no way to enforce them

### Expected behavior

0.5.18 should behave like 0.5.17 does, allowing DLSS to work on systems with supported Nvidia cards.

### Log output
_-not relevant to this issue-_

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Ubuntu 24.10 Oracular Oriole
Arch: x86_64
Kernel: 6.11.0-9-generic
Lutris Version: 0.5.18
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 7700X 8-Core Processor
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 31.0 GB
Swap: 2.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4070 Ti SUPER/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 560.35.03
OpenGL Core: 4.6.0 NVIDIA 560.35.03
OpenGL ES: OpenGL ES 3.2 NVIDIA 560.35.03
Vulkan Version: 1.3.290
Vulkan Drivers: NVIDIA GeForce RTX 4070 Ti SUPER (1.3.280)
```

### Media (optional)

![Lutris 0 5 18 options](https://github.com/user-attachments/assets/adba304b-085d-44fa-a616-2ca26a1f2112)

### Current workaround

Well, one can stick with 0.5.17 for now, which makes sense as it's still considered the stable release while 0.5.18 is the beta.

**Comment by shakakibara12** [comment]
In my case reverting the ee332166c68ce5a04600585025c5d815b20e8835 commit fixed the issue for me. Try reverting that commit, maybe it will fix the issue.

**Comment by danieljohnson2** [comment]
This is very strange; that change was to enable people to run two programs in a prefix at once, and it seemed pretty obvious why it would do that. What this has to do with DLSS is quite obscure.

I'll take this to the Umu discord to ask WTf.

**Comment by danieljohnson2** [comment]
So I got a reply and there is an issue; that commit maybe should have used ``run`` instead of ``runinprefix``- ``runinprefix`` means Umu does not set up the prefix, and that is why DLSS does not work.

Buuuut, if we do set up the prefix is means that Lutris' effort to control stuff like the DSVK version does not work. We copy DXVK v1.2.3, and then later Umu setup copies in its own version.

I suspect something in going to have to be broken here.

I will switch it over to ``run`` for now so DLSS will work. Please try it like that and confirm that DLSS works again, as I expect.

This verb still allows you to run another program at the same time in the prefix, but does not allow you to control the DXVK version. Not ideal.

**Comment by SpoOokY1983** [comment]
Also suffering from that issue with 0.5.18. Can I fix it by adding a specific launch parameter? Or do I have to wait for a new release of Lutris?

**Comment by danieljohnson2** [comment]
I'm concerned about it; I've made further changes to this, so that the ``waitforexitandrun`` is now used initially, so proton-fixes get applied. But we can't install DXVK anymore; Proton just overwrites it. Does this break DLSS?

Perhaps you could give this a test? You could [download the latest master](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within- no need to install. Does DLSS work with Proton this way?

I hope so, but I don't feel a lot of confidence.

**Comment by SpoOokY1983** [comment]
Started the downloaded version, copy&pasted all Star Citizen settings from my Flatpak Lutris install but it does not work it all. This version does not even detect my GPU and tells me that no Vulkan support is available.

**Comment by danieljohnson2** [comment]
Ah, that's not going to work. You'd need to have installed Lutris 'natively' to get all the dependencies in, and then you could just run the master you had downloaded. There's no reasonable way to do the same for Flatpak, so far as I know.

We'll have to hope it all works out.
