### ISSUE TITLE
umu-protonfixes doesn't get called with the default PROTON_VERB

### ISSUE THREAD

**Issue by kasha695** [lutris/lutris#5786]
### Bug description

The current default PROTON_VERB is set to "run" from this commit: 6b74540

However the only time umu-protonfixes will be called is if the verb is set to "waitforexitandrun", as mentioned [here](https://github.com/Open-Wine-Components/umu-launcher/issues/79) by @R1kaB3rN

I was testing this with Dragon Age Inquisition as it has an Xinput patch to allow the controller to work, if I launched it from the terminal using umu-run the controller works as the default verb is "waitforexitandrun" but launching through lutris shows it skipping protonfixes and just launches the game.

If I set the env PROTON_VERB to "waitforexitandrun" on lutris then it correctly executes the protonfixes.

### How to Reproduce

1. Set a game on lutris with the env UMU_ID 1222690
2. Launch the game and check the logs to see no protonfixes
3. Set another env PROTON_VERB to waitforexitandrun
4. Launch again and check the logs to see the fixes applied

### Expected behavior

I assume we want the UMU_ID to trigger protonfixes but in it's current state it doesn't.

### Log output

```shell
*
```

### System Information

```shell
*
```

**Comment by danieljohnson2** [comment]
Nertz. I thought I'd got away with this one.

The problem is that Lutris thinks it can spawn new processes in a prefix already running one, and ``waitforexitandrun`` prevents this. See #5689.

We still use that for Winetricks and Wine Configuration, so perhaps you can run one of those commands first, then the game, and that'll will get your Proton fixes on.

But I think we need some intelligence- use ``waitforexitandrun`` for a prefix that has no processes running, and ``run`` if ith has any. But will that allow Lutris's choice of DXVK etc to take effect?

I didn't want to try anything this fancy just before a release, but I'd better try it now.

I guess Lutris' Umu/Proton support remains experimental after all; no Proton Fixes is not good enough.

**Comment by kasha695** [comment]
Sounds good, I can do what you recommend to get the fixes in or I'll just use the PROTON_VERB set to waiforexitandrun for now as I'm not running any extra processes in the prefix.

**Comment by danieljohnson2** [comment]
It does not look great. [Here is a branch you can try](https://github.com/lutris/lutris/tree/dj/restore_protonfixes); just download this code and run the ``bin/lutris`` script within. No need to install. I think it will run the proton fixes, and can still run another program (like task manager) at the same time.

But in my testing I can't control the DXVK version- Umu is installing its own over ours. That's a regression, and I need to think about what we can do about it.

**Comment by danieljohnson2** [comment]
The guidance I'm getting so far is that we should just trust in Umu and not try to override DXVK for it.

**Comment by kasha695** [comment]
That fix works, I'm getting protonfixes for every launch now.

I'm testing a lot of my games so if I find any that have issues with DXVK I'll make a report, but so far they've all worked; even those I've had to set a specific DXVK version before. A promising sign! :)

I'll mark this as closed as it's solved.
