### ISSUE TITLE
Runners

### ISSUE THREAD

**Issue by antikruk** [lutris/lutris#594]
Add please runners Kega Fusion and PCSXR

**Comment by strycore** [comment]
Kega Fusion is proprietary, 32bit only and abandonned.

PCSX-R is really poorly maintained and buggy when not entirely broken. We used to ship PCSX-R until a few weeks ago but it was a broken mess, glad we got rid of it.

We now provided stable and working equivalents through libretro cores.

**Comment by RobLoach** [comment]
> PCSXR

I'd recommend looking at the [beetle-psx-libretro or mednafen_psx core for RetroArch](https://wiki.libretro.com/index.php?title=Beetle/Mednafen_PSX). It has worked very well for me on the Pi3.

**Comment by strycore** [comment]
While I do believe mednafen_psx is a superior core, we default to pcsx_rearmed in the default installers because it doesn't have a hard requirement on Playstation BIOS file (although, the open source BIOS replacement fails with a lot of games).

When we have a better way for BIOS file installation, we'll default to mednafen_psx (or even better, mednafen_psx_hw)

**Comment by rodneyrod** [comment]
@strycore Is ePSXe an option maybe?

**Comment by trymeouteh** [comment]
How about making a ePSXe runner but it will require the user to install ePSXe on their system. The runner itself will not install ePSXe but allow you to run games in ePSXe from Lutris?

Also doesn't the Wine Steam runner download and install the Windows Steam client within WINE? And isn't the Steam client on Windows closed source?
