### ISSUE TITLE
Failed to install on fedora 26(python(abi) fail)

### ISSUE THREAD

**Issue by maddovr** [lutris/lutris#605]
Lutris requires python(abi) 3.5, while fedora 26 and many current rolling distro have switched to python 3.6. Is it possible to install under either versions?

**Comment by RobLoach** [comment]
Or have Python 3.6 compatibility. What errors have you been getting?

**Comment by maddovr** [comment]
avvertimento: lutris-0.4.12-6.1.noarch-1.rpm: Header V3 RSA/SHA256 Signature, ID chiave fd5b64b9: NOKEY
errore: Dipendenze fallite:
	python(abi) = 3.5 necessario a lutris-0.4.12-6.1.noarch

Basically, it fails to recognize python 3.6 abi for some reason. The package was downloaded from OBS, fedora 25 build. The system I'm currently using is fedora 26(which has made the switch to 3.6 by default) latest beta(can't use fc25 due to some hardware issues addressed in linux 4.10 and gnome 3.24).

**Comment by TingPing** [comment]
> The package was downloaded from OBS, fedora 25 build.

Well that is obviously why, F25 and F26 ship different python versions.

**Comment by strycore** [comment]
I've added Fedora 26 and Rawhide to the OBS repositories, let me know if the package causes issues.

**Comment by joplju** [comment]
Is there any kind of compatibility with using Fedora 26's packages instead of going out to a third party repository? Forgive me if I'm misunderstanding the workaround, but I'm having the same issue. When upgrading from F25 to F26, dnf noted the incompatibility and required uninstalling Lutris to upgrade.

**Comment by strycore** [comment]
> When upgrading from F25 to F26, dnf noted the incompatibility and required uninstalling Lutris to upgrade.
If that's the case then dnf doesn't know how to deal with different Python versions, I've never had such an issue with apt. But I find it surprising that dnf, doesn't handle that situation more properly.

**Comment by joplju** [comment]
Please forgive my ignorance. My problem was the static definition of the release version in your repo, which didn't get upgraded with the system update. I changed each instance of 25 to $releasever, and Lutris installed without issue. Of course, I could have just downloaded your Fedora 26 .repo file as well.

**Comment by strycore** [comment]
> Please forgive my ignorance. 

Oh, I totally ignorant when it comes to Fedora, I was just making a wild guess. 

Indeed the repo has to be manually updated, same thing goes for every other distro.

Makes me think, maybe I should implement a way to update those repos automatically from the lutris client (which wouldn't help a lot if the client can't start because of python version issues).

**Comment by strycore** [comment]
Closing the issue since the Fedora 26 package installs correctly.
