### ISSUE TITLE
Add option for xinput9_1_0 and architecture override / deprecate koku-xinput

### ISSUE THREAD

**Issue by berenm** [lutris/lutris#629]
Hello,

I recently contributed some modifications to the koku-xinput-wine library that should make it work for both 32bit and 64bit games (although it requires building the library for 64bit and 32bit, and add both to the LD_PRELOAD environment variable).

There are other changes as well that should make more games compatible with the library and correctly detect the XBox360 controller.

I tested multiple games, but not that many though, and I don't think it broke anything. It was already marked as an experimental feature, so I guess it should be OK.

Could you have a look and maybe update the packaged library in lutris?

Cheers,

**Comment by strycore** [comment]
We plan to deprecate koku-xinput-wine in the near future and remove the option entirely. Since I've added support for auto-generated x360ce configurations, I haven't found a use for koku-xinput. If there's any game that would have controller support with koku-xinput but not without, please let me know, as this would maybe make me take a different stance on this. (Actually, the only game I'm interested in having controller support working is The Witcher 3)

**Comment by berenm** [comment]
Well, IMHO the koku library is much easier to setup than x360ce, it works out of the box for the many games I tried, and every time I tried x360ce I couldn't get any satisfying experience.

With x360ce, the setup guides that I've found require the user to replace the standard xpad kernel module with xboxdrv. This alone requires additional setup, as usually xpad is usually installed loaded by default which is not the case for xboxdrv. Also I had trouble with xboxdrv which was not working correctly with multiple native Linux games, although xpad was just fine.

**Comment by berenm** [comment]
Maybe you could try the recent changes in koku by the way, Witcher 3 might just be working. All the games I tried (Batman, Overcooked, Redout, Abzu) work perfectly with my changes.

**Comment by strycore** [comment]
x360ce can be a pain to setup indeed but the new lutris feature takes care of it entirely. We keep a copy of GameControllerDB.txt and generate a fresh copy of x360ce.ini each time the game is run, based on the plugged in controllers. Before that, I would have that only x360ce config I would re-use everywhere and I think it would only work with the x360 controller. 
Now, the only step needed is pointing Lutris to the game's executable and it will take care of the rest, it will also work with any controller: XBox, PS3, SNES USB, ...
Here's a list of games I've tested using this method: https://github.com/lutris/lutris/wiki/Controller-support-in-Wine-games 
As mentioned before, any game I used koku-xinput on also works with the new method.

**Comment by berenm** [comment]
So, I wanted to give it another try but so far it's not working very well. I'm using lutris 0.4.13, with system wine installed from the wine-staging repositories (2.14 Staging), and an XBox360 USB controller.

I don't know how the x360ce feature is supposed to work, but I checked that DLLs were correctly copied right next to the games executable, and that the x360ce.ini file was actually listing my controller (named "Microsoft X-Box 360 pad (event)").

I found several categories of games after very quick testing (usually just trying the controls in the game menus):
Games that work out of the box:
- Jade Empire (GOG)
- Rayman 2: The Great Escape (GOG)
- Darksiders (Steam)

Games that work with the "x360ce-path" option:
- Mirror's Edge (GOG)
- Prince of Persia (2008) (GOG)

Games that only work with koku-xinput-wine:
- Ori and the Blind Forest: Definitive Edition (GOG)
- Batman: Arkham City GOTY (Steam)
- Batman: Origins (Steam)
- Overcooked (Steam)
- Shantae and the Pirate's Curse (Steam)
- Call of Juarez Gunslinger (Steam)

It looks like none of my Steam games were working with the "x360ce-path" config, maybe that's a configuration issue rather than incompatibility. From your list, it looks like the Batman games should be, although during my tests they didn't. Also from this list, Darksiders is just working out of the box.

The Koku library worked with every game I tried.

**Comment by strycore** [comment]
There seems to be some issues with your setup, you should get the Batman games to work with Lutris, Call of Juarez should also work but for some reason, the Y axis on the right stick is inverted.

On the other hand, Darksiders should *not* work out of the box. While the controller is recognized, starting a game will result with the camera spinning and a bunch of buttons incorrectly mapped. Darksiders requires the x360ce-path along with the x360ce-dinput option enabled.

Rayman 2 is old enough that it wouldn't use Xinput, I remember playing it and having good controller support.

To benefit from the x360ce-path option, make sure you have the correct location for the game's executable (which is not the root folder for games such as Batman), also make sure that all previous x360ce setups are removed, Lutris takes care of copying xinput1_3.dll and dinput8.dll automatically. Also make sure that you use a 32bit prefix for 32bit game, otherwise, Lutris will be confused.

**Comment by berenm** [comment]
Ok, maybe Darksiders is not working after all, I didn't played past the menu.

Regarding the Steam games not working, it's probably the wine architecture then. I used a 64bit prefix for my wine steam (yes, I have some 64bit games in Steam). And my GOG games are installed separately in a 32bit prefix. That would explain it.

There's still Ori and the Blind Forest, in a 32bit prefix that doesn't work with x360ce and that works with koku. Also, the fact that koku library works seamlessly in 32bit or 64bit prefixes is another point IMHO.

**Comment by berenm** [comment]
I managed to solve the 32bit/64bit issue by overriding the wine prefix and architecture in the games configurations.

Now most of the Steam games I tried earlier are working, except Shantae and the Pirate's Curse that does not detect the controller, and Call of Juarez that now detects the controller but is completely broken as you described.

**Comment by berenm** [comment]
For both Shantae and Ori, the x360ce DLL and the wine library override has to be renamed to xinput9_1_0.dll instead of xinput1_3.dll in order for the games to load it.

**Comment by strycore** [comment]
That's useful information! I had xinput9_1_0.dll in my original x360ce bundle but I couldn't find a use for it. Now, I now it may be useful for some games so I'll add an option like the dinput one.

**Comment by strycore** [comment]
For the prefix architecture issue, our solution is less than optimal but the alternative relies on inspecting the exe file and determining if it's a 32 or 64 bit executable. We don't even know what the game executable is, only its directory so it would involve some additional changes.
