### ISSUE TITLE
Track status of Steam games before considering them ready to run

### ISSUE THREAD

**Issue by setzer22** [lutris/lutris#658]
I have been experiencing this issue for a couple months now. Whenever I'm installing a wine steam game, the steam client closes unexpectedly halfway through the download. 

Once the game is downloaded I can play just fine, and steam seems to remain open. This only happens when I run the game but steam still has to download/update it. After some amount of time (from 1 to 10 minutes, I'd say?) the steam client dies. 

The odd part is that if I run the Wine Steam runner directly from the left menu, then the client won't die. This works as a workaround, but I have no means to launch the runner in a different prefix, so games requiring their own prefix for downloading (e.g. Dark Souls II, which needs a 64 bit prefix to download) cannot be installed.

The "Do not launch game, only open Steam" and "Stop Steam after game exits" options have no effect on this. There is also nothing on the execution log or the terminal window that runs lutris.

I am currently on Arch Linux 64 bits, lutris runtime is disabled (don't think it matters here) and I've been experiencing this issue since I installed lutris (so I tried from wine-staging 2.14 to wine-staging 2.17 versions, no differences).

**Comment by richierh** [comment]
I just have that problems either.I am using Linux Mint 18.. I don't know how to solve it, wait to someone else who have found a workaround

**Comment by soredake** [comment]
Try to disable 'Process monitor'.

**Comment by strycore** [comment]
There is no "workaround", Lutris is doing what it's programmed to do. When launching Steam games, Lutris expects the game to be installed and ready to run, we currently don't support waiting for the game to finish downloading or updating.

Disabling process monitoring breaks some of Lutris features and should probably never be used unless during debugging. 

I wanted to get this fixed in 0.4.14 but I could only get half the feature finished before shipping the new release, this will be fixed in 0.4.15, there's not much left to do now.

**Comment by soredake** [comment]
@strycore could you please give me a moderation right on lutris.net and review https://github.com/lutris/lutris/issues/680?

**Comment by strycore** [comment]
@soredake I've added you to the moderators group. I'll mark #680 for next release as well.

**Comment by soredake** [comment]
@strycore thanks!

**Comment by strycore** [comment]
Please test before the 0.4.15 release.
