### ISSUE TITLE
Prevent using system wine version if it's too old. 

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#672]
Anything older than Wine Staing 2.18 shouldn't be used by default, Wine should be considered as uninstalled when this is the case.

Users can force an old version manually and their choice should be honored.

**Comment by manuelVo** [comment]
This feels a bit wrong to me since the stable version is 2.0.2 currently. I assume it can feel a bit strange to be told the wine version in use was old when it is actually the latest (stable) release available.

Also I think if this is going to be implemented it should probably be a shifting window that adjusts according to the most recent version that exists - at least if there arent any groundbreaking changes introduced in 2.18 which justify hard coding this version.

**Comment by strycore** [comment]
Lutris considers the latest version to be the latest staging version. People will try running our installers with 2.0 or older and will wonder why stuff isn't working. I've received far too many user reports that were simply due to users using an outdated version of Wine.

As far as the Lutris project is concerned, Wine 2.0.2 isn't anything special, it's just an old version that shouldn't be used.

**Comment by manuelVo** [comment]
I'd allow for at least one version older than the current one though since keeping up with the bi-weekly release cycle can get pretty hard (especially when using additional patches like gallium-nine).

**Comment by strycore** [comment]
Oh, the old versions aren't going anywhere, it will still be possible to use Wine 2.0 or older. The only difference is when Lutris tries to detect if Wine is installed, it will return False unless a current version of Wine Staging is available.
