### ISSUE TITLE
Run Steam via FlatPak if possible

### ISSUE THREAD

**Issue by eternaleye** [lutris/lutris#677]
There's a Flatpak for Steam on Flathub, that sandboxes it (somewhat) and provides it a consistent environment without requiring multilib support on the host. It'd be great if Lutris could use that if already set up, or possibly install it if not present.

**Comment by strycore** [comment]
We should get support for Flatpak in the 0.5.x cycle

**Comment by LeandroStanger** [comment]
GNOME Game already supports Steam Flatpak https://gitlab.gnome.org/GNOME/gnome-games/commit/441bc12da1f0d176d54fb9411ccf78e78be4b6d6
![captura de tela de 2018-08-14 09-02-33](https://user-images.githubusercontent.com/26097419/44090536-dd415b56-9fa0-11e8-8f97-36959b685edb.png)

**Comment by rodneyrod** [comment]
Has there been any update on this?

**Comment by strycore** [comment]
pretty sure you can specify the Steam executable to point to the flatpak version now

**Comment by rodneyrod** [comment]
I meant for auto detection. Currently the location isn't automatically found and this isn't the case if Steam is installed through the native package manager.

Also, my library won't sync from flatpak Steam but has no problem with the native version.

**Comment by RobLoach** [comment]
If you create a shell script in your PATH for `steam` to be `flatpak run com.valvesoftware.Steam`, it'll work.

The issue is that it takes an executable, rather than a string to run it through Flatpak:
https://github.com/lutris/lutris/blob/master/lutris/runners/steam.py#L185-L191

Try creating a `steam.sh` shell script with the following....

```
#!/bin/bash
flatpak run com.valvesoftware.Steam $@
```

And point Lutris over to it.

**Comment by LeandroStanger** [comment]
@alexlarsson Could help?

**Comment by rodneyrod** [comment]
I'll give this a shot, but this setup is really manual and suboptimal, would there be a way to automate this in Lutris?

**Comment by RobLoach** [comment]
> I'll give this a shot, but this setup is really manual and suboptimal

If the above works, then it would be possible to adapt the runner to use a similar solution.

> would there be a way to automate this in Lutris somehow

Yes. The issue is that it takes an executable, rather than a string to run it through Flatpak:
https://github.com/lutris/lutris/blob/master/lutris/runners/steam.py#L185-L191

We'd need to update the runner to allow changing the way Lutris runs Steam, and detect how/where to run Steam.

> would it require a fundamental design change?

No.

**Comment by modzilla99** [comment]
@LeandroStanger I'm really sorry to bug u here, but what kind of DE are u using or what theme? It looks really sleek!

**Comment by LeandroStanger** [comment]
@modzilla99 [Endless OS](http://endlessos.com)

**Comment by modzilla99** [comment]
Thks
