### ISSUE TITLE
Add default wine versions to wine prefixes

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#720]
I have a few games installed on a prefix with Uplay and it's a pain having to change each game entry individually when upgrading Wine. I'd like for Lutris to change the Wine version, under runner options, for all games if one of them is switched.

**Comment by strycore** [comment]
Once we add Wine prefix management we'll add the possibility to attach a default wine version to a particular prefix.

**Comment by 8BitCerberus** [comment]
One option might be to do it as a Parent / Child setup. Where setting up things like Win Steam, Battle.net, GOG Galaxy, etc. would be the "parent" and you can spawn "child" launchers from them to have different games using different settings (DXVK on/off, wined3d/wined3d11 on/off, esync on/off, etc.), but they all inherit the parent prefix's runner.

Not sure how to handle, for example, DOSBox games in this way though, since GOG and Steam have many of them and you wouldn't want it handled with the Wine runner for their base prefixes. Maybe in addition to the child option, a way to split off individual games into a parent prefix of their own, separate from their parent prefix, allowing them to have their own runner (such as the case with using DOSBox for some GOG games while you are using Wine for Galaxy and other GOG games). Would be similar to duplicating the prefix, but set up as a blank environment ready for just that executable, rather than copying over the entire prefix (and any installed games/software/etc. within it.) Or it may be easier (at least less confusing UX) to just allow child launchers to change their runner, but have it obscured as an advanced option or something so someone doesn't do it accidentally.

**Comment by strycore** [comment]
@8BitCerberus this sounds similar to the way we do things already. You can apply settings to Wine Steam or Wine, and they will be applied to all games unless overridden in the game config itself.

We will have additional runners for Battle.net, Origin and Uplay as well. GOG Galaxy, probably not since we have GOG as a service (where you can import games) and not as a runner (GOG games use Linux, Wine, Dosbox and ScummVM runners)

**Comment by 8BitCerberus** [comment]
For Wine and Wine Steam and the various emulators, DOSBox, etc. that is true. I was thinking more the situation with Battle.net, GOG Galaxy, Epic Games, Uplay, Origin, etc. since those all install under the base Wine runner/category and installing different games from them means either each game shares the same Wine config, or having separate installations of the launcher for each game taking up unnecessary disk space and making maintenance an annoyance, or manually moving the games into a single prefix after installation and editing the launcher to point to the new location.

But it sounds like you're going to have them (minus GOG) separated out into their own runner/categories at some point, too? That would definitely make things more cohesive.
