### ISSUE TITLE
i18n is not fully implemented

### ISSUE THREAD

**Issue by Sebastian1978** [lutris/lutris#728]
Lutris doesn't have russian translation.

**Comment by liberavia** [comment]
There are some po-files in po-directory, but they don't seem to be really used. The only position where gettext is included is in lutris/gui/application.py but binded to a common directory (/usr/share/locale)

**Comment by strycore** [comment]
Yeah. I know.

**Comment by TingPing** [comment]
I'd set it up if Lutris ever moves to a real build system where you can reasonably build, extract, and merge translations.

**Comment by strycore** [comment]
Hopefully, we'll migrate to Meson during the 0.5 cycle.

**Comment by liberavia** [comment]
I currently try to test if at least basic string translation with gettext can be implemented with not too much effort 

I began to wrap strings of the code and tried to import and install gettext all over the lutris package. However, it's not yet working.

My first approach is in this commit:
https://github.com/liberavia/lutris/commit/f996fb6d1f205796c92062b1a0a3570439f30ce4

Hints are welcome

**Comment by TingPing** [comment]
- Installing translations in `./locale` is a bit lame
- Storing binary `.mo` files in git is a bad idea
- Data files like desktop file need merging
- Automated way to do all of that and extract translations would be nice

But most of that comes down to having a build system with `gettext` support built in.

**Comment by liberavia** [comment]
Ok, so it would be at least helpful if I do a PR with just the marking stuff then?

**Comment by TingPing** [comment]
I think so yes. Also for text like this: `<i>(Italic indicates that this option is modified in a lower configuration level.)</i>` don't have users translate the markup.

Here are some general guidelines: https://wiki.gnome.org/TranslationProject/DevGuidelines (And the [markup page specificially](https://wiki.gnome.org/TranslationProject/DevGuidelines/Avoid%20markup%20wherever%20possible))

**Comment by liberavia** [comment]
Hi there,

i removed some of the code that i did yesterday and went further searching through files for making them translatable, so that there available in a pot file without markup and whitespaces. I noticed that there is a 80 column limit that is used which often leads to strings wrapped with brackets to go over newlines. These are hard to catch for translation due to `_()` will destroy the structure. This occures for example in sysoption.py where currently I just marked the labels for now:
`    
{
        'option': 'game_path',
        'type': 'directory_chooser',
        'label': _('Main game folder'),
        'default': os.path.expanduser('~/Games'),
        'scope': ['runner', 'system'],
        'help': ("The main folder where you install your games.\n"
                 "Lutris uses it to propose you a default path when you \n"
                 "install a new game.")
    },
`

Thats also why I left out the runners path. In atari800 I tried some solution approach which is not nice, so there should be a more generic solution for handling 80 column limit and long translatable texts.  Thats my QD-Approach on this:

`
    def get_long_help_msg(self,option):
        help_messages = {}

        # main_file
        help_messages['main_file'] = _("The game data, commonly called a ROM image.") + " \n"
        help_messages['main_file'] += _("Supported rom formats: ATR, XFD, DCM, ATR.GZ, XFD.GZ")
        help_messages['main_file'] += _("and PRO.")

        # bios_path
        help_messages['bios_path'] += _("A folder containing the Atari 800 bios files.") + " \n"
        help_messages['bios_path'] += _("They are provided by Lutris so you shouldn't have to") + " "
        help_messages['bios_path'] += _("change this") + "\n"

        return help_messages.get(option, "")


    game_options = [
        {
            "option": "main_file",
            "type": "file",
            "label": _("ROM file"),
            'help': get_long_help_msg('main_file')
        }
    ]
...
snip
...
    runner_options = [
        {
            "option": "bios_path",
            "type": "directory_chooser",
            "label": "Bios location",
            'help': get_long_help_msg('bios_path')
        },
`
Hope it points to the problem.

In the end I noticed that my first approach yesterday basically did some translation for me :) :

![auswahl_022](https://user-images.githubusercontent.com/19731409/35188358-1eb19a74-fe34-11e7-8035-1bc7d24fbc43.png)

**Comment by liberavia** [comment]
I tried the following attempt to get messages and labels at least centralized:

https://github.com/liberavia/lutris/commit/41f75f982ab4e5c198f46e4fb67717668c4023e3

Any improvement suggestions?

**Comment by TingPing** [comment]
Not sure I like the idea of pulling all strings out into other files personally.

**Comment by liberavia** [comment]
What are your concerns? I mean, ok puting all the stuff into one big messages-file would be no good but we could put all the messages in a folder messages using the same structure as the lutris main package.

Would make it possible to fetch messages optional by importing in atari800.py like:
`from lutris.messages.runners import atari800 as msg`

In an IDE like PyCharm I can Ctr+Click back and forward to always get the content of the current message.

**Comment by TingPing** [comment]
I just think its ugly, less readable (not everybody uses pycharm), and doesn't have many benefits.

**Comment by liberavia** [comment]
In my eyes it improves code readability. Let's take this one for example:
![auswahl_024](https://user-images.githubusercontent.com/19731409/35236066-478bef94-ffa6-11e7-944d-1905bbba241d.png)

- Removes strings that have nothing to with programming
- Content is more separated from logic
- Centralized workspace for translation-team without harming any core code
- Less problems with 80 column limit, especially for long text

However, I'm just the guy came by a few days ago and you're bounded for long time in this project, so I wouldn't tell you. I'm a bit unsure if I should go on  like I do now. Perhaps you feel like skimming over the branch and get a feeling about the code readability with message constants. Maybe it's not that worse you think it is?:

https://github.com/liberavia/lutris/tree/internationalization/lutris

**Comment by TingPing** [comment]
> Centralized workspace for translation-team without harming any core code

Only developers should be marking strings as translatable really. Just sadly that wasn't done from the start here.

@strycore can have the final say on that though.

**Comment by strycore** [comment]
So, I've used both ways of doing i18n. But the important point is that I've used the "all strings in one place" method only in Javascript, because it lacks i18n features like gettext. 

For python code, I'm used to leaving the strings where they are and having them centralized only in the .po file. 

Our current coding standard regarding line-length is 100 characters, not 80 and there are ways to easily work with long strings, especially if they're translatable. You can write something like: 

```
s = _(
    "This is a really long string. "
    "that we cut in multiple lines "
    "thanks to Python's implicit "
    "line continuation in parenthesis."
)
```

Also:

> Centralized workspace for translation-team

Translators work with .po files, they don't have to interact with the code.

**Comment by liberavia** [comment]
Sorry for beeing a little calm in the last time. Following your wishes I did a reset on my local branch and stayed with just marking strings as mentioned above.

Of course I do understand that translators should not ever come in contact with code. That's why I used the term "Translation-Team" which should have indicated that there are even coders needed, when changing the code to be able to create po-files. 

However. Decision has been made against string centralization, so I opened up a PR:

https://github.com/lutris/lutris/pull/769

**Comment by stephanlachnit** [comment]
Btw #2725 introduces basic support for i18n. For now only the `.ui` files (which is not much tbh), but at least it's doing something and adding full i18n support is as "simple" as converting all translatable strings in the python code.

**Comment by YihaoPeng** [comment]
I have make the transaction of the `*.ui` files effective with these commits:
https://github.com/SwimmingTiger/lutris/commit/c4d2dd3b5459a5ab6033666d657e0fa2fff088fa
https://github.com/SwimmingTiger/lutris/commit/8e39f20183428f886feb14e9a05fd3fe02b1b0f2

I will continue to implement the entire i18n support.

**Comment by YihaoPeng** [comment]
Full i18n support added.

https://github.com/lutris/lutris/pull/2947

* mark almost all translatable content in python codes with `_()` or `gettext.ngettext` (for plurality).
* `meson` can extract translatable content in code to the `.po` files.
* `meson` can build and deploy translation files (`*.mo`) to the correct directory.
* `lutris` can load `.mo` translation files from the current installation location, not just `/usr/share/locale`.
* Translation is effective for all windows.

Contains a complete simplified Chinese (zh_CN) translation, the effect is as follows:

![截图录屏_20200617105040](https://user-images.githubusercontent.com/26923506/84849773-a47e4180-b088-11ea-9c91-e760300254dc.png)

**Comment by strycore** [comment]
Thank you so much, this is a very valuable addition to the projects and will be appreciated by every translator and non english user!

I'm going to close this issue since our i18n support looks pretty good now :)
