### ISSUE TITLE
[Feature Request] Make WineSteam default to 64bit arch instead of 32bit

### ISSUE THREAD

**Issue by rodneyrod** [lutris/lutris#786]
Newer games that are coming out on Steam are only supporting 64bit e.g. Planet Coaster, and since WineSteam by default opens up as a 32bit application you can't install those games without a fair amount of tinkering.

There don't seem to be compatibility reasons to keep the 32bit prefix the default so I personally think it's time to make the switch over.

**Comment by telanus** [comment]
I think tha a switch, almost like what PoL is doing, might work better. When you create a new prefix, ask do you want a 32bit or 64bit prefix.

**Comment by Sethox** [comment]
The problem here is that I think the user should be able to choose with what version/arch you can boot up with. If I start the game directly (that defaults as 64-bit) it primarily starts Steam with 64 bit and getting past the login window the game starts. But what if I just the steam application to start, I have to run the game, shut it down and use steam from there (and that's if I have the option of letting Steam to run after the game is closed).
This as default is alright, just let us users have an alternative option.

**Comment by rodneyrod** [comment]
Yeah that's what I mean. If I have to create a launcher for a 64bit only game, I have to go and create a dummy launcher that only launches Steam and change the arch from there. There really should be a way when I right click on WineSteam and launch it directly I can launch it with a 64bit prefix by default.

But I honestly don't see the reason to keep the default to 32bit. More games are 64bit only these days, and there doesn't seem to be a compatibility reason to default to 32bit either since either arch has the same compatibility anyway.

**Comment by Zeioth** [comment]
This is not a big deal because the version of your 'Steam Wine' only affects Steam. When you install a game, it can has its own wine version. Anyway, this issue is duplicated, please close it #655

**Comment by strycore** [comment]
Steam now defaults to 64bit on new installations, there was no point defaulting to 32bit.
