### ISSUE TITLE
Support A Wine Version Similar to Ge-Wine

### ISSUE THREAD

**Issue by Saroufim** [lutris/lutris#811]
https://github.com/GloriousEggroll/ge-wine supports pba, csmt, and gallium-nine as well as extra game-specific patches all at once. I think it would be a good candidate for a runner for Lutris as it is greatly beneficial for gaming.

**Comment by strycore** [comment]
I'm waiting for @GloriousEggroll to push to the lutris/wine repository and I'll publish a build.

**Comment by GloriousEggroll** [comment]
at the moment there are some changes with wine-pba that are in discussion regarding cb_heap_size and geo_heap_size which allow pba to be used with ffxiv, witcher 3, and warframe. I am waiting on those to be resolved before committing

**Comment by IngeniousDox** [comment]
A 3.5 with PBA + firerats rebase & envvar (+ gallium9) might be a good thing.

Thusfar I have no issues with it, other then that I will have to change the installers to not set CSMT anymore, since that is in vanilla.

Though if at all possible, we should get the CSMT toggle that is being discussed on the wine-staging repo.

**Comment by IngeniousDox** [comment]
Actually that toggle might not be needed for the 3.5 build, since that is the way people "upgrading" might need to use to disable staging CSMT.

**Comment by Saroufim** [comment]
Ge is now available on Lutris, however the Galluim-nine implementation does not seem to be working. The option is greyed out as well from winecfg

**Comment by GloriousEggroll** [comment]
two things:
1. g9 only works with mesa open source drivers on amd
2. g9 shows greyed out if your mesa isn't compiled with --enable-gallium-osmesa option

**Comment by Saroufim** [comment]
Installed gallium-nine through copr and it worked just fine. It's just the one provided by lutris that doesn't seem to work.

**Comment by GloriousEggroll** [comment]
this may be because wine was compiled on a system that doesnt have that
option enabled on its mesa install (the lutris build system)

**Comment by strycore** [comment]
That might be the cause indeed. Are there some extra dependencies required to get Gallium9 support? Note that we are building Wine on Ubuntu 16.04

**Comment by GloriousEggroll** [comment]
the build system needs mesa compiled with the --enable-nine option, or install it from a PPA that has it

**Comment by strycore** [comment]
@GloriousEggroll the Launchpad page for the gallium-nine PPA says: "WARNING: don't use this PPA - it is no longer updated since the github Gallium Nine project ( https://github.com/iXit/Mesa-3D ) is no longer active.
To use nine simply use the standard PPA: https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers/"

Will installing the other PPA work as well in the 16.04 containers?
