### ISSUE TITLE
Add offline detection

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#847]
Had no internet for a couple days and I noticed Lutris took a while (1:00-1:30) to open. Probably because I have my account linked. Is there any possible way to implement detection when no internet connection is present?

**Comment by nonchip** [comment]
optionally make it so it doesn't try to do any networking in a blocking call but a second thread instead? should be much cleaner&performant that way and it could then periodically try to get back online and sync the library on the fly.

**Comment by TingPing** [comment]
GNetworkMonitor provides some of that functionality async.

**Comment by nonchip** [comment]
yes, exactly the wrong parts of that functionality. you don't want to check if the network interface is up, you want to check if `lutris.net` responds. even `GNetworkMonitor::can_reach` does not check if it can actually reach something, only if it would have a route for it (which means always returns `true` as long as there's an interface with a default route).

**Comment by strycore** [comment]
Disabled my network interface and opened the client. It wasn't any slower than if it were online. 
I agree with @nonchip and think that a generic online detection wouldn't add a lot of value since each feature accessing the network has to handle failure in their own way.

**Comment by nonchip** [comment]
@strycore that's because if you disable your network interface or unplug your cable or disconnect from wifi then your kernel knows that immediately refuses to route the connection. if on the other hand your router has no uplink (and still claims to be, or is manually configured as, the default route) or the servers fail, or there's another issue with the connection somewhere on the way where your local kernel can't just go "um no there's no way for me to do that" in advance, that's when you get the long delays while it tries to still do it.

i'm afraid your test isn't enough to say the issue isn't anymore, so might wanna reopen that? especially since it was milestoned?

the obviously "right" fix here would be to just do the network thing in a background thread, but i don't know how easy it would be to refactor that into the codebase.

**Comment by tannisroot** [comment]
I tried both disconnecting my pppoe connection and making a firewall rule in my router for lutris.net that would drop requests to that domain and it had no affect whatsoever on how fast Lutris client launched.

**Comment by strycore** [comment]
I added a 30 second timer before each HTTP request and it was still ok.

**Comment by strycore** [comment]
I identified a problem when opening the "Import games" dialog, this one needs to be done in the background.

**Comment by tannisroot** [comment]
Should I close https://github.com/lutris/lutris/issues/2531 as duplicate or you will close it when you fix the issue with Import Games dialog?

**Comment by strycore** [comment]
I'll close it when I fix import games

**Comment by nonchip** [comment]
> I added a 30 second timer before each HTTP request and it was still ok.

the only explanation i have for that would be that somewhere down the line someone fixed it by making stuff multithreaded and forgot to fix this issue, or maybe it was all along but some versions of pygtk didn't play nice with the threading.

just double tested any scenarios i could come up with with the newest codebase, it definitely seems to work now.
