### ISSUE TITLE
PICO-8 Support

### ISSUE THREAD

**Issue by NQNStudios** [lutris/lutris#850]
Would there be any interest in supporting PICO-8 carts? https://www.lexaloffle.com/pico-8.php

I just discovered this project and I'm looking to potentially contribute. I'd be willing to look into this! :)

**Comment by telanus** [comment]
The only thing I see that is a bit of a stumbling block is that it's Paid Software

**Comment by RobLoach** [comment]
https://github.com/nesbox/TIC-80 is open source

**Comment by telanus** [comment]
@RobLoach would make a cool runner, tried tonight but my qbasic skills don't really transfer into python :P

**Comment by NQNStudios** [comment]
PICO-8 is paid software yeah, but carts are all also playable in exported HTML5 form so I think lutris could launch the games that way.

**Comment by daniel-j** [comment]
Sneak peek at a web-based PICO-8 runner I'm working on. You will also be able to select your local pico8 executable to use that instead of the web backend. The web backend runs .p8.png files.
![screenshot_20180627_074244](https://user-images.githubusercontent.com/1264014/41954956-40a21002-79de-11e8-9985-1bd2398cf8fe.png)

**Comment by NQNStudios** [comment]
This is marvelous!

**Comment by daniel-j** [comment]
PR submitted! https://github.com/lutris/lutris/pull/1476

**Comment by daniel-j** [comment]
Merged!
