### ISSUE TITLE
Ubisoft Connect runner

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#911]
After a bit of searching I found out how to uninstall a Uplay game and from there I got the other two.

To install: `uplay://install/111`

To launch: `uplay://launch/111`

To uninstall: `uplay://uninstall/111`

Edit: Don't know what changed but you don't need to use upc.exe anymore.

**Comment by strycore** [comment]
Nice, now we only need a list of a games with their IDs!

**Comment by AccountOneOff** [comment]
I can get a list for the games I own relatively easily but I'll have to look into the others.

**Comment by AccountOneOff** [comment]
https://github.com/Haoose/UPLAY_GAME_ID

https://github.com/d3adm4u5/UplayGameIDs/blob/master/latest.txt

**Comment by AccountOneOff** [comment]
I don't know if Uplay's overlay gives as many problems as Origin's does but here is it's location regardless: `drive_c/users/$USER/Local Settings/Application Data/Ubisoft Game Launcher/settings.yml`

    overlay:
      enabled: false
      forceunhookgame: false
      fps_enabled: false

**Comment by TheRealDannyBoy** [comment]
[I've been working on this](https://github.com/TheRealDannyBoy/lutris).  I have a "first draft" of a runner (I just modified `winesteam.py`), although I cannot test it yet since I have just started on the service.  This is the first time I've worked on a "real" project, so if you would care to look over my work, I'd be happy to accept any feedback suggestions.

**Comment by strycore** [comment]
![Screenshot from 2022-01-25 02-11-54](https://user-images.githubusercontent.com/280336/151788564-ff600a49-76d3-4e21-bb62-aa20bbf129a7.png)

The Ubisoft Connect service is implemented!
