### ISSUE TITLE
Lutris ignores application-specific overrides for d3d11 and dxgi in winecfg with "Enable DXVK" enabled

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#948]
I'm experiencing a problem running Origin with option "Enable DXVK".
When I launch latest version of Origin with "DXVK_HUD devinfo,fps,frametimes" flag, it shows up like this:
![Imgur](https://i.imgur.com/1uLYRNp.png)
Howerer, when I set overrides for d3d11 and dxgi for Origin.exe and also QtWebEngineProcess.exe, like this
![Imgur](https://i.imgur.com/LjrV0yG.png)
It does not help and Origin still displays DXVK hud. I wouldn't be bothered so much by this, but this prevents me from seeing stats in the actual game.

**Comment by Sethox** [comment]
The HUD is not displayed because of the "existing_overrides" (you don't enable the display/HUD there), it's because in the wine configuration (in Lutris own configuration) you have on environment variables structured so the HUD is displayed. Going to DXVK github own introduction, it actually explains this (not how to turn the HUD on in Lutris).

**Comment by strycore** [comment]
yeah, I don't think there's a bug here, try changing the DXVK_HUD options in the environment variables. 
also, you shouldn't need to override d3d11 in winecfg as lutris' own config will likely take precedence.

**Comment by sungerbob** [comment]
@strycore Hey, can you make support for dll overrides? I really want to not load DXVK on some game launchers.
